### DISCUSSION TITLE
Troubles with `search` operator in st2 rule definition: "did not find expected key"

### DISCUSSION THREAD

**Discussion by stevemuskiewicz** [StackStorm/st2#5389] [Documentation] [answered]
(I asked this on Slack awhile back, but guessing it got lost in the noise)

I'm trying to use the `search` operator in one of my pack rules (following https://docs.stackstorm.com/rules.html#advanced-comparison) and I'm not sure if it's just braindead-ness on my part or something else wrong but I can't seem to get the rule to validate when loading my pack (using st2 3.5.0).

I'm trying to apply the rule when any of the items of the `body.push.changes` payload has a `new` key with a `null` attribute (maybe I'm not doing that part right either, wasn't entirely clear to me if this is right for when the key itself exists and just has a `null` value vs. not existing at all).  But I'm not even sure I'm getting that far since st2 doesn't seem to like the rule as its defined.

Here's the snippet of my rule criteria:
```
    # repo pushed event
    # branch deletion (new: null)
    criteria:
        trigger.headers['X-Event-Key']:
            type: "equals"
            pattern: "repo:push"
        trigger.body.push.changes:
            type: "search"
                condition: any
                pattern:
                    item.new:
                        type: "nexists"
                        pattern: "anyvalue"
```

and here's the exception I get from st2 when I try to load the pack:
```
MESSAGE: Failed to register rule "/opt/stackstorm/packs.dev/pxops/rules/bb_repo_branch_deleted.yaml" from pack "pxops": while parsing a block mapping
  in "/opt/stackstorm/packs.dev/pxops/rules/bb_repo_branch_deleted.yaml", line 23, column 13
did not find expected key
  in "/opt/stackstorm/packs.dev/pxops/rules/bb_repo_branch_deleted.yaml", line 24, column 17 for url: http://st2api:9101/v1/packs/register
```
(line 23 coincides with the `type: search` line)

I'm not sure what the "expected key" is that st2 was looking for here.  Originally I started with no `pattern` attribute at all for `item.new` but looking at some of my development notes I think I found in the past that st2 wasn't happy without this value even though it would seem unnecessary when using the `exists` or `nexists` operators

I've reviewed the docs several times and it _thought_ I had all the right keys but maybe I'm missing something obvious?

TIA!

**Comment by erceth** [comment, marked as answer]
The example in the documents is invalid YAML. I'm still trying to figure how the expected structure. My best guess is that `condition` and `pattern` need some left spacing removed so that they are siblings with type.

```
    criteria:
        trigger.headers['X-Event-Key']:
            type: "equals"
            pattern: "repo:push"
        trigger.body.push.changes:
            type: "search"
            condition: any
            pattern:
                item.new:
                    type: "nexists"
                    pattern: "anyvalue"
```
