### DISCUSSION TITLE
Help setup passwordless sudo for stanley

### DISCUSSION THREAD

**Discussion by lm-ydubler** [StackStorm/st2#5444] [General]
Hi all, I need help setting up passwordless sudo for Stanley (Ubuntu 20.04)

First, I have a Rule successfully routing to an Action (a local shell script) that contains:
```
du -hs /tmp
find /tmp -atime +10 -delete
```
So this code successfully deletes standard files that don't require sudo, but, it doesn't delete the permission-unlocked test files in the `/tmp/` folder. So I just need instructions on how to get StackStorm/stanley to run sudo commands knowing the following:

The user `stanley` (whose password I don't know) runs the commands.

I setup the action's YAML file with the `sudo` and `sudo_password` fields (using my admin's password):
<img width="756" alt="action_yaml_params" src="https://user-images.githubusercontent.com/92544319/142032926-a9c38e9e-4f90-4f3b-a791-9388e24f6c17.png">
The pack installs successfully and the Rules/Actions have been verified to be firing.

To setup passwordless sudo for `stanley` I added the following line to the end of `/etc/sudoers`:
`stanley ALL=(ALL:ALL) NOPASSWD:ALL`

But it's still not deleting the completely unlocked files in the `/tmp/` directory so was hoping for some guidance or pointers on how to make it work.

Thanks and best

**Comment by minsis** [comment]
Can't you run `core.local` action? From there you could just create a rule with CronTimer once a day, or whatever frequency you want.

**Reply by minsis** [reply]
Here's an example off the cuff (I haven't tested it):

```yaml
---
name: clear_temp_files
pack: examples
description: Delete temp files older than 10 days
enabled: true
trigger:
    type: core.st2.CronTimer
    hour: 05
    minute: 0
    second: 0
action:
    ref: core.local
    parameters:
        cmd: find /tmp -atime +10 -delete
```
