### DISCUSSION TITLE
core.st2.IntervalTimer suddenly not triggering

### DISCUSSION THREAD

**Discussion by joeahrens** [StackStorm/st2#5507] [Q&A]
Stackstorm version 3.6.  I have a rule that is set to trigger every 300 seconds.  It has been working flawlessly until about 2 weeks ago.  I can't figure out why it will no longer trigger.  I've tried issuing a `st2ctl restart`.  I've rebooted the server.  I've recreated the rule.  It is not limited to one rule.  None of them are triggering.

**Comment by minsis** [comment]
Can you share your rule file and action?

Have you looked in the st2timersengine log file to see if there was something breaking?

**Reply by joeahrens** [reply]
```
---
  name: circuit_monitor_python
  pack: vz_uc_alert
  enabled: true

  trigger:
    type: core.st2.IntervalTimer
    parameters:
      unit: seconds
      delta: 300
  action:
    ref: vz_uc_alert.monitor_circuit
    parameters:
      timeframe: "5m"
```
