### DISCUSSION TITLE
about trigger_types field

### DISCUSSION THREAD

**Discussion by zyayun** [StackStorm/st2#5516] [Q&A]
what's the different ？

- parameters_schema 
- payload_schema 
- payload_info

```yaml
Example:
---
  class_name: "FileWatchSensor"
  enabled: true
  entry_point: "file_watch_sensor.py"
  description: "Sensor which monitors files for new lines"
  trigger_types:
    -
      name: "file_watch.line"
      pack: "linux"
      description: "Trigger which indicates a new line has been detected"
      # This sensor can be supplied a path to a file to tail via a rule.
      parameters_schema:
        type: "object"
        properties:
          file_path:  # User ``st2`` should have permissions to be able to read this file.
            description: "Path to the file to monitor"
            type: "string"
            required: true
        additionalProperties: false
      # This is the schema of the trigger payload the sensor generates
      payload_schema:
        type: "object"
        properties:
          file_path:
            type: "string"
          file_name:
            type: "string"
          line:
            type: "string"
```
