### DISCUSSION TITLE
Passing parameters from action to workflow?

### DISCUSSION THREAD

**Discussion by gnudiff** [StackStorm/st2#5539] [General]
I have just started trying to use Stackstorm, and I was wondering how to correctly make available action parameters to the (orchestra) workflow it executes.

I am trying to set up a workflow with the first step of executing a sql query.
The workflow should accept a parameter report_date, and if it is not supplied use the timestamp of execution.

The action YAML is this:

```
---
name: report_daily
pack: my_reports
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/daily_report_sql.yaml
enabled: true
parameters:
  report_date:
    required: true
    type: string
    default: "{{ action_context.timestamp }}"
```

And the workflow YAML is:

```
version: 1.0
name: my daily report
description: Get daily stats, optionally for a particular date (report_date). By default for yesterday as of time of calling.
input:
  - report_date
tasks:
  task1:
    action: sql.query
    input:
      connection: my_postgres
      query: "SELECT * from my_table WHERE 
             create_date BETWEEN  ( {{ ctx().report_date }}:timestamp - '24 hours'::interval)
                                                   AND (     {{ ctx().report_date }}:timestamp  ) "


```
But the SQL executor complains that None is not a timestamp, so apparently the ctx().report_date is not the right way to refer to this.

Could you tell me, how should it be done, please?
