### DISCUSSION TITLE
inquiry core.ask - stop workflow on boolean False response

### DISCUSSION THREAD

**Discussion by clindner85** [StackStorm/st2#5542] [Workflows] [answered]
Hi all,

i couldn't find information on this, so trying to clarify here.
Running ST2 v3.5.0

I'm trying to implement an inquiry to reach out for help if intel is missing during a workflow.

I tested the core.ask function with the "examples.orquesta-ask-basic".
The definition:
```
  get_approval:
    action: core.ask
    input:
      schema:
        type: object
        properties:
          approved:
            type: boolean
            description: "Continue?"
            required: True
    next:
      - when: <% succeeded() %>
        do: finish
      - when: <% failed() %>
        do: stop
```
I was expecting that responding True leads to success and False to fail.
But in fact, responding True and False both lead to success which would next do task finish instead of task "stop".

Is there any way to check the actual value of the response in the "when" condition? (like "when: properties.approved = False")
Or else; Am I probably misunderstanding the concept here?

Thanks
Best Regrads
Chris
