### DISCUSSION TITLE
How to use execution timestamp in workflow as default parameter?

### DISCUSSION THREAD

**Discussion by gnudiff** [StackStorm/st2#5550] [Workflows]
Is it possible to set action default parameter to be current timestamp?

I tried:

```
--
name: daily_report
pack: my_reports
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/daily_report.yaml
enabled: true
parameters:
  report_date:
    type: string

the corresponding workflow step is:

version: 1.0
name: daily report
description: Get daily stats, optionally for a particular date (report_date). 
input:
  - report_date: "{{  task().start_timestamp }}"
tasks:
  task1:
    action: core.echo message="Welcome {{ ctx().report_date }}"
    next:
      - when: <% succeeded() %>
        publish: stdout=<% result().stdout %>


```
But that outputs just "Welcome None"

**Comment by minsis** [comment]
I'm not exactly sure I understand the specific need for pulling datetime off of the task itself, but can't you just use YAQL datetime functions?

https://yaql.readthedocs.io/en/latest/standard_library.html#datetime-functions

**Comment by minsis** [comment]
Ok after seeing your other post and taking a closer look at this one I see your issue.

You have the default set, but the task() context isn't generated until one of the tasks are actually executed. So in other words you're calling `task().start_timestamp` with no tasks actually being executed. Also without digging into the code I dont even know if task().start_timestamp is populated dynamically during task execution. Although the docs do say it it can be access during task runtime.

Anyways, you'd need some kind of logic in order to use it during task runtime.
```yaml
input:
  - report_date # default is None if nothing was passed in from calling action

tasks:
  task1:
    action: core.echo message="Welcome {% ctx().report_date or task().start_timestamp %}"
```

This is untested but give it a shot.
