### DISCUSSION TITLE
action dynamic rendering yaml file

### DISCUSSION THREAD

**Discussion by zyayun** [StackStorm/st2#5616] [Packs]
`expectation`
```
---
---
name: u_create_vm
runner_type: python-script
description: Create a new VM.
enabled: true
entry_point: u_create_vm.py
parameters:
  name:
    type: string
    description: Name of a new VM.
    required: true
    default: dev-autogen-0.infra.uc.mobvoi-idc.com
    position: 1
  zone:
    type: array
    description: >+
      Zone of ucloud.
      - cn-bj2-02
      - cn-bj2-03
      - cn-bj2-04
      - cn-bj2-05
    required: true
    position: 2
    # default: cn-bj2-02
    default: "{{ st2kv.system.zone }}"
    enum:   # Cannot be implemented dynamically using Jinja
    {% for item in st2kv.system.zone %}
    - {{ item }}
    {% endfor %}

```

However, dynamic rendering is not supported
