### DISCUSSION TITLE
Unable to install StackStorm packs via volume method in K8s deployment

### DISCUSSION THREAD

**Discussion by ektasaxena04** [StackStorm/st2#5626] [Operations]
Hi,

I have created all the 3 pvc's and updated values.yaml as per https://github.com/StackStorm/stackstorm-k8s#install-custom-st2-packs-in-the-cluster

```
volumes:
    enabled: true
    packs:
      persistentVolumeClaim:
        claim-name: pvc-st2-packs
    virtualenvs:
      persistentVolumeClaim:
        claim-name: pvc-st2-virtualenvs
    configs:
      persistentVolumeClaim:
        claim-name: pvc-st2-pack-configs
```

claim for virtualnvs is not getting bind to the required pods. following mounts have been created.

```
ubuntu@Bastion:/opt/stackstorm$ ll
total 24
drwxr-xr-x 6 root root 4096 Apr 21 05:53 ./
drwxr-xr-x 9 root root 4096 Apr 20 10:50 ../
drwxrwxrwx 2 root root 4096 Apr 20 11:23 configs/
drwxrwxrwx 2 root root 4096 Apr 21 05:53 configs-helm/
drwxrwxrwx 2 root root 4096 Apr 20 10:51 packs/
drwxrwxrwx 2 root root 4096 Apr 20 11:22 virtualenvs/
```

Error :
```
Normal  WaitForPodScheduled  3m19s (x22 over 72m)  persistentvolume-controller  waiting for pods stackstorm-ha-job-st2-register-content-52rn9,stackstorm-ha-st2sensorcontainer-f4796d8b5-qm5hd,stackstorm-ha-st2actionrunner-7966ddc66d-svmgb,stackstorm-ha-st2actionrunner-7966ddc66d-hv6jv,stackstorm-ha-st2actionrunner-7966ddc66d-7gjqs,stackstorm-ha-st2client-5756b856d6-vzs75,stackstorm-ha-st2api-649489f4c9-lnz7b to be schedule.
```

All the 3 pods mentioned in the above error message are also in pending state and unable to bind the volume.

yaml for  pvc.virtualenvs
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-st2-virtualenvs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
```

Please help.

**Comment by arm4b** [comment]
@cognifloyd Any pointers to help with the initial debugging and configuration?

**Comment by cognifloyd** [comment]
Why is your PVC using `ReadOnlyMany`?

**Reply by ektasaxena04** [reply]
the error is same with ReadWriteOnce
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: stackstorm-packs-configs
  name: stackstorm-packs-configs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
```

**Reply by cognifloyd** [reply]
What about `ReadWriteMany`?

And if that doesn't work, can you create a dummy pod with your PVC to test that the PersistentVolume is working?

**Reply by ektasaxena04** [reply]
Thanks, Volume got bound to the required pods with accessmodes - ReadWriteOnce. It worked by adding labels to the pvc 

This is the yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: stackstorm-virtualenvs
  name: pvc-st2-virtualenvs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
```
Thanks a lot :)
