### DISCUSSION TITLE
runner_type: yaml_script

### DISCUSSION THREAD

**Discussion by PLPRASU** [StackStorm/st2#5629] [Q&A]
can i give runner type as yaml_script ?

**Comment by nzlosh** [comment]
YAML script is not part of the list of available runner types https://docs.stackstorm.com/actions.html#action-runners

Can you describe what yaml script is and why you would need a new runner for it?

**Reply by PLPRASU** [reply]
st2 run aws1.ec2_satrt instance_ids=i-0b52e443a1fe39dd6
.
id: 62691c8130dd951a398bfe23
action.ref: aws1.ec2_satrt
parameters: 
  instance_ids:
  - i-0b52e443a1fe39dd6
status: failed
start_timestamp: Wed, 27 Apr 2022 10:35:45 UTC
end_timestamp: Wed, 27 Apr 2022 10:35:45 UTC
result: 
  errors:
  - message: The spec is not type of list.
  output: null

**Reply by PLPRASU** [reply]
i am getting error above like that

**Comment by nzlosh** [comment]
As per the information shared via slack
```
version: 1.0
input:
   -instance_ids
tasks:
  ec2_stop:
       action: aws.ec2_stop_instances
       input:
          InstanceIds: <% ctx(instance_ids) %>
       next:
          when: <%succeeded() %>
          do: ec2_satrt
          publish: "start instance"
  ec2_satrt:
     action: aws.ec2_start_instances
     input:
         InstanceIds: <%ctx(instance_ids)  %>
```

The next section is malformed.  It expects a list, but the workflow provides a dictionary.  Take a look at the example here to see how your should write the next section https://docs.stackstorm.com/orquesta/start.html#authoring
