### DISCUSSION TITLE
Failing to send data from an action to the next

### DISCUSSION THREAD

**Discussion by LMacchi** [StackStorm/st2#5661] [Q&A] [answered]
Hi all! Super new to Stackstorm, and after reading docs, past discussion threads and googling, I still cannot figure this out.

I have this workflow:

```
version: 1.0

description: Fake description

input:
  - user
  - pwd

tasks:
  http_call:
    action: core.http method=GET username="{{ ctx().user }}" url="https://redacted?output_mode=json" verify_ssl_cert=false password="{{ ctx().pwd }}"
    next:
      - when: <% succeeded() %>
        publish:
          - my_list: "{{ result().body | jsonpath_query('entry[0].content.[var1,var2]') }}"

output:
  - my_list: {{ ctx().my_list }}
```

That works great, and I get this result:

```  
output:
    my_list:
    - 'value1'
    - 'value2'
```

Next I try to add a new step using `with` to iterate thru the same action:

```
[...]
tasks:
  http_call:
    action: core.http method=GET username="{{ ctx().user }}" url="https://redacted?output_mode=json" verify_ssl_cert=false password="{{ ctx().pwd }}"
    next:
      - when: <% succeeded() %>
        publish:
          - my_list: "{{ result().body | jsonpath_query('entry[0].content.[var1,var2]') }}"
        do:
          - validate

  validate:
    action: core.noop
    with: 
      items: <% ctx().my_list %>
    next:
      - when: <% succeeded() %>
        publish:
          - item: "<% item() %>"
    
output:
  - my_list: "{{ ctx().my_list }}"
  - item: "{{ ctx().item }}"
```

But the output indicates that `item` is empty:

```  output:
    my_list:
    - 'value1'
    - 'value2'
    item: null
```

It's worth noting that the validation will end up being more complex than that, I just simplified to try to get the data passing correctly from action to action. I also tried both YAQL and JINJA, the snippet here has a mix of both, which I've read is not in the best practices.

Doc I followed: https://docs.stackstorm.com/orquesta/languages/orquesta.html#with-items-model

I tried the `with` with and without `items:`, not sure if that makes a difference. I might have introduced some spacing errors while pasting here, but the workflows works.

I appreciate any help, docs, examples, whatever that will allow me to get unblocked.

Thanks in advance!

Edit for versions:
- st2 3.7.0, on Python 3.6.9
- Ubuntu 18.04.6 LTS x86_64
- Python 2.7.17

**Comment by LMacchi** [comment, marked as answer]
I think I got it for anyway following along:

Seems like the value inside of `item()` is available just during the command execution and not afterwards. Instead of using `core.noop`, I switched to `core.local` and did a bash validation + `succeeded()` and `failed()` controls.

My working workflow:

```
version: 1.0

description: Fake description

input:
  - user
  - pwd

vars:
  - factors: null
  - message: null


tasks:
  http_call:
    action: core.http method=GET username="{{ ctx().user }}" url="https://redacted?output_mode=json" verify_ssl_cert=false password="{{ ctx().pwd }}"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - my_list: "{{ result().body | jsonpath_query('entry[0].[var1,var2]') }}"
        do:
          - validate

  validate:
    action: core.local
    with:
      items: "{{ ctx().my_list }}"
    input:
      cmd: "[ {{ item() }} -eq 'value' ]"
    next:
      - when: "{{ failed() }}"
        do: fail

output:
  - message: "Var1 is {{ ctx().my_list[0] == 'value' }} and Var2 is {{ ctx().my_list[1] == 'value' }}"
```

Hope that helps someone some day.
