### DISCUSSION TITLE
Looping through tasks in a workflow

### DISCUSSION THREAD

**Discussion by 0lzi** [StackStorm/st2#5756] [Q&A] [answered]
I have created an action which takes type array from actions, but not sure how to loop through the input in the workflow.

### Actions
```
entry_point: "workflows/mass_vm_decommission.yml"
parameters:
  vm_names:
    type: array
    description: Name of the Virtual Machines to delete in a comma delimited string (e.g. test-001,test-002,test-003)
    required: true
```

then in the workflow

### Workflow

```
input:
  - vm_names: null

want to loop through tasks for each vm

tasks:
  task1:
      input: <% ctx().vm_names%>
something
  task2:
      input: <% ctx().vm_names%>
```
