### DISCUSSION TITLE
UI Enhancement for Array type

### DISCUSSION THREAD

**Discussion by ns-kkodiyan** [StackStorm/st2#5972] [Ideas]
In current versions of Stackstorm, any array type input parameter is displayed in the UI as a text box that requires comma separated values. 
If the input parameter type is `enum` however, I see that it displays in the UI as a single select dropdown. 
I want to preface this feature request with the note that this is definitely only a quality of life improvement. 
With that said, can we have a multi-select dropdown list for `array` type input parameter where the `items` are restricted to values as part of an `enum` block? 
For example:
```
parameters:
  array_list:
    description: "Multi selectable values for the array"
    required: true
    type: array
    items:
      type: string
      enum:
        - Value1
        - Value2
        - Value3
        - Value4
```

What I'm hoping for in this case, is that this parameter in the UI is shown as a multi select drop down and **only the selected values** are stored in the context as an array. 
That is, for the above example, if `Value1` and `Value3` are selected in the drop down, `<%ctx(array_list)%>` would return `['Value1', 'Value3']`. As opposed to the current way, where we have to type in the string "Value1, Value3" in the input before triggering the execution.

Let me know if more info is required on this. 

TIA
