### DISCUSSION TITLE
Orquesta's "do" with variable

### DISCUSSION THREAD

**Discussion by argendo** [StackStorm/st2#6051] [Workflows] [answered]
Hi!
I'm making an orquesta workflow, and i want to call next task via variable, for example, one of my tasks looks like this:
```
data_fetch:
  action: core.local_sudo
  input:
    cmd: "curl -ks -X GET 'example.com/?q=<%ctx(my_ctx)%>' > ./temp_data.json"
  next:
  - when: <% succeeded() %>
    do: <% ctx(my_variable) %>_flow
```
where `my_variable` is a string.

I need it to run different tasks in case of different values of `my_variable`.
For example: in case of value "first" i want to run `first_flow`, in case of "second" i want to run `second_flow` and so on.

Nevertheless stackstorm doesn't want to parse it as a string and move on. 

Is it even possible to do such thing or how can i route my flow in case of different values of `my_variable`?
