### DISCUSSION TITLE
Task transition condition with multiple whens

### DISCUSSION THREAD

**Discussion by xer0times** [StackStorm/st2#6104] [Workflows] [answered]
How will Orquesta process these three "when" conditions, in parallel or sequentially? If it's parallel, how can it be one at a time?

```

  switch_on_host_os:

    action: core.noop

    next:

      - when: <% ctx().hosts[ctx().loop_iteration_count]?.os = "windows" %>

        do: run_cmd_on_windows_host

      - when: <% ctx().hosts[ctx().loop_iteration_count]?.os = "linux" %>

        do: run_cmd_on_linux_host

      - when: <% ctx().hosts[ctx().loop_iteration_count]?.os = null %>

        do: ...  # How to handle non-Windows and non-Linux hosts is application-specific

```
