### DISCUSSION TITLE
Issue Handling JSON Payload in Custom StackStorm Action

### DISCUSSION THREAD

**Discussion by agomez-m** [StackStorm/st2#6209] [Q&A]
Hi everyone,

I'm having trouble handling a JSON payload in a custom StackStorm action. The action is configured to receive a payload from PagerDuty, but it seems like the payload is not being parsed correctly.

**Rule Definition:**

```
name: "custom_incident_action"
pack: "udo"
description: "regla para activar webhook de pagerduty"
enabled: true

trigger:
    type: "core.st2.webhook"
    parameters:
        url: "pagerduty_udo"

action:
    ref: "udo.custom_incident_action"
    parameters:
        payload: "{{ trigger.body }}"
```
 **Action YAML Definition:**

```
name: custom_incident_action
description: "Procesar payload de pagerduty"
runner_type: python-script
entry_point: custom_incident_action.py
enabled: true
    parameters:
        payload:
            type: object
            description: "El payload JSON del incidente"
```

**Python Script:**
```
import json
from st2common.runners.base_action import Action

class CustomIncidentAction(Action):

    def run(self, payload):
        try:
            # Parsear el payload JSON
            payload_data = json.loads(payload)

            # Extraer los datos necesarios del payload
            payload_info = payload_data.get('payload', {})
            if not payload_info:
                raise ValueError("No payload information found")

            # Acceder a la información dentro de 'payload'
            headers = payload_info.get('headers', {})
            body = payload_info.get('body', {})
            messages = body.get('messages', [])

            if not messages:
                raise ValueError("No messages found in payload")

            # Usar el primer mensaje para simplificar
            primer_mensaje = messages[0]

            # Extraer la información necesaria del primer mensaje
            event = primer_mensaje.get('event')
            summary = primer_mensaje.get('log_entries', [{}])[0].get('summary')  # Obtenemos el primer resumen del registro de entradas
            service_summary = primer_mensaje.get('service', {}).get('summary')
            incident_summary = primer_mensaje.get('incident', {}).get('summary')
            incident_url = primer_mensaje.get('incident', {}).get('html_url')

            # Imprimir (aqui supongo que habrá que hacer otra cosa para crear el udo)
            print(f"Evento: {event}")
            print(f"Resumen del registro de entradas: {summary}")
            print(f"Resumen del servicio: {service_summary}")
            print(f"Resumen de la incidencia: {incident_summary}")
            print(f"URL de la incidencia: {incident_url}")

            return True, f"Evento: {event}, Resumen del registro de entradas: {summary}, Resumen del servicio: {service_summary}, Resumen de la incidencia: {incident_summary}, URL de la incidencia: {incident_url}"

        except json.JSONDecodeError as e:
            error_message = f"Error al parsear el payload JSON: {e}"
            print(error_message)
            return False, error_message

        except KeyError as e:
            error_message = f"Clave faltante en el payload: {e}"
            print(error_message)
            return False, error_message

        except ValueError as e:
            error_message = f"Error al procesar el payload: {e}"
            print(error_message)
            return False, error_message

```
Error Received:
`TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'`

It seems like the payload is being received as None. I've verified that the PagerDuty webhook is sending the data correctly. If I manually force the action with the payload, the action parses it correctly, so the issue must be with how the rule and the action send the payload to the Python script.

Any ideas why this might be happening or what I might be doing wrong?

Thanks in advance for your help!
