### DISCUSSION TITLE
Jinja Templating in message and data for StackStorm Notifications

### DISCUSSION THREAD

**Discussion by docbyte86** [StackStorm/st2#6217] [Q&A]
Hello all!

I have the followin workflow metadata:

```yaml
---
name: named
pack: eco
description: Recover named process
runner_type: orquesta
entry_point: workflows/named.yaml
enabled: true
parameters:
  host:
    required: true
    type: string
  username:
    required: true
    type: string
  cmd:
    required: true
    type: string
  service:
    type: string
    required: true
  output:
    type: string
    required: true
  state:
    type: string
    required: true
```

Now i want to add the notify block below the metadata:

```yaml
notify:
  on-failure:
    routes:
      - critical
    message: '"Recover named process workflow failed"'
    data:
      host:
      service:
      output:
      state:
```

According to https://docs.stackstorm.com/chatops/notifications.html#jinja-templating-in-message-and-data i am allowed to use jinja templating. Now i want to use the values from the parameters, defined in the action workflow.

Example:

```yaml
---
name: named
pack: eco
description: Recover named process
runner_type: orquesta
entry_point: workflows/named.yaml
enabled: true
parameters:
  host:
    required: true
    type: string
  username:
    required: true
    type: string
  cmd:
    required: true
    type: string
  service:
    type: string
    required: true
  output:
    type: string
    required: true
  state:
    type: string
    required: true
notify:
  on-failure:
    routes:
      - critical
    message: '"Recover named process workflow failed"'
    data:
      host: "WhatEverHost"
      service: "{{action_parameters.cmd}}"
      output: "workflow failed"
      state: "CRITICAL"
```

The notify rule got triggered but results in the error below:

```json
{
  "output": null,
  "errors": [
    {
      "type": "error",
      "message": "JinjaEvaluationException: Unable to evaluate expression '{{action_parameters.cmd}}'. UndefinedError: 'action_parameters' is undefined"
    }
  ]
}
```

Can somebody support here and knows how to reuse the values from the workflow parameter values?

**Comment by fdrab** [comment]
have you tried <% ctx().get('cmd') %> ?

**Comment by docbyte86** [comment]
@fdrab 

thanks for reviewing.

Actually i tried with the results that the parameters get not resolved:

This is the payload that my rule is receiving:

```json
"message": "\"Recover named process workflow failed\"",
  "data": {
    "host": "<% ctx().get('host') %>",
    "service": "<% ctx().get('service') %>",
    "output": "<% ctx().get('output') %>",
    "state": "<% ctx().get('state') %>",
  ```
  
  Really appreciate any help and let me know if further informations are needed.

**Comment by fdrab** [comment]
sorry I can't help further, I don't use chatops :(

**Comment by nzlosh** [comment]
As far as I know, YAQL is not supported in the notification section.  I tested notification with the following definition

```
notify:
  on-failure:
    routes:
      - errbot
    message: |
      *TEST NOTIFICATION ON FAILURE*
      ```
      action parameters: {{ action_parameters }}
      action results: {{ action_results }}
      action context: {{ action_context }}
      st2kv: {{ st2kv }}
      ```
    data:
      channel: "#errbot-dev-test"
      user: "@nzlosh"
```
`#errbot-dev-test` is a channel in my slack workspace.  `errbot` route is to target the bot that is connected to slack.  I observed the following output in slack:

```
TEST NOTIFICATION ON FAILURE
 action parameters: {}
action results: {'output': {'stdout': 'The time on the localhost is Fri Jul  5 23:59:26 CEST 2024'}, 'errors': [{'type': 'error', 'message': 'Execution failed. See result for details.', 'task_id': 'task1', 'result': {'failed': True, 'succeeded': False, 'return_code': 1, 'stdout': 'The time on the localhost is Fri Jul  5 23:59:26 CEST 2024', 'stderr': ''}}]}
action context: {'user': 'st2admin', 'pack': 'test', 'rbac': {'user': 'st2admin', 'roles': ['admin']}, 'workflow_execution': '66886cbd455041576fe88068'}
st2kv: {'system': <st2common.services.keyvalues.KeyValueLookup object at 0x7f4017be90b8>}
```

As you can see the action parameter exists as an empty dictionary.  This might be due to a bug in the runner.  You could try creating a simple action using action-chains to see if the action parameters dictionary is filled in with the expected data.
