### DISCUSSION TITLE
result().result is unavailable

### DISCUSSION THREAD

**Discussion by freeyssu** [StackStorm/st2#6231] [Workflows] [answered]
This is a very simplfied workflow that I am using.
```
Task:
    ....  # do action
    next:
      - when: <% succeeded() %>
        publish:
          - all_results: <% result().result %>  # works very well
      - when: <% failed() %>
        publish:
          - all_results: <% result().result %>  # ERROR - YaqlEvaluationException: Unable to evaluate expression '<% result().result %>'. NoFunctionRegisteredException: Unknown function \"#property#result\""
```

I cannot understand why `result()` doesn't have `result` property in case of `failed()` result.
I suspect `result()` has some string in case of FAIL result which cannot be parsed by JSON parser? (e.g. `{` included in `stderr` property)
If so, how can I handle it as `stderr` includes Python exceptions and logs.
