### ISSUE TITLE
Preserve type in ActionChain publish variables

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2#1231]
Since ActionChain publishing uses Jinja the types for published variables are not preserved and everything gets a string representation.

Fix either by switch all this to YAQL or some other post-jinja magic.

**Comment by armab** [comment]
The same is for actions, right?

Wanted to edit [load.yml](https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/load.yaml):
```yaml
---
  name: "load"
  runner_type: "local-shell-cmd"
  description: "Action that reloads all st2 content."
  enabled: true
  entry_point: ""
  parameters:
    sudo:
      immutable: true
    cmd:
      immutable: true
      # this line :(
      # it's a string, man: ["actions", "aliases", "sensors"]
      default: "st2 reload{% for item in register %} --register-{{item}}{% endfor %}"
    register:
      type: "array"
      items:
        type: "string"
      default:
        - "actions"
        - "aliases"
        - "sensors"
      description: "Possible options are all, sensors, actions, rules, aliases."
    kwarg_op:
      immutable: true
```


And cried here:
```yaml
    cmd:
      immutable: true
      default: "echo '{{ register|join('-') }}'"
    register:
      type: "array"
      items:
        type: "string"
      default:
        - "actions"
        - "aliases"
        - "sensors"
```
->
`[-"-a-c-t-i-o-n-s-"-,- -"-a-l-i-a-s-e-s-"-,- -"-s-e-n-s-o-r-s-"-]`

Or I'm doing something wrong?
