### ISSUE TITLE
Global variables in yaml files

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#1651]
There are already some [environment variables available to the actions](https://github.com/StackStorm/st2/blob/master/docs/source/actions.rst#common-environment-variables-available-to-the-actions).
Most probably there will be more and more useful of these during time.

The proposal is to make those variables available in yaml files too, bringing more flexibility.
```yaml
---
name: example_action
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  cwd:
    default: "/opt/stackstorm/virtualenvs/{{ ST2_ACTION_PACK_NAME }}/bin"
    immutable: true
  cmd:
    ...
```

Btw, this approach is pretty obvious thing in [Ansible](https://docs.ansible.com/playbooks_variables.html#information-discovered-from-systems-facts), which operates with yaml files too.

**Comment by Kami** [comment]
That's related to allowing users to reference values from a datastore in the parameter default values - we decided to keep it explicit, simple and easier to debug by not allowing it.

If user wants to reference a datastore value, they need to add a task in a workflow which retrieves this value - this way it's explicit and easier to see what is going on and where value is coming from.

I hold the same opinion for using environment variable values in the parameter default values - I prefer to keep metadata simple and static. There is obviously a lot of dynamic stuff going on in the actions, workflows and rules, but I think it's better if we try to keep metadata files as "static" as possible.

**Comment by armab** [comment]
I see, thanks for explanation.

From my understanding allowing to make things in less steps without writing dirty hacks could be good.
I hope it's just matter of time :calendar:  when users would ask more and more flexibility ;)

**Comment by armab** [comment]
Here is another example I've experienced:

When pack is renamed, since it's name is hardcoded in yaml files - everything inside the pack should be renamed too.

Assume I have `st2-chatops-pack` with actions and aliases in it.
Action: `st2-chatops-pack/actions/cowsay.yaml`
Action alias: `st2-chatops-pack/aliases/cowsay.yaml`:
```yaml
---
name: chatops.cowsay
# could be:
# action_ref: {{ ST2_ACTION_PACK_NAME }}.cowsay
action_ref: st2-chatops-pack.cowsay
description: Draws a cow that says what you want
formats:
  - "cowsay {{message}}"
```

If I rename the pack I should dig into every yaml file and rename old pack name with new name: `action_ref: new-chatops-pack.cowsay`. Another example situation when I share GitHub repo which someone forked and renamed it to whatever they want.
Renaming could be annoying.
