### ISSUE TITLE
Infinite timeout in action parameters

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#1654]
The problem is that parameter `timeout: 0` in action is considered as 60 seconds and there is no option to make it "infinite", eg. no timeout.

Here is example action `actions/test_timeout.yaml`:
```yaml
---
name: test_timeout
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  timeout:
    # works as default 60 seconds
    default: 0
  cmd:
    description: "Command to run"
    immutable: true
    default: "sleep 90 && echo 'done!'"
```

Running it: 
```sh
# st2 run st2-pack-bug.test_timeout
..............................
id: 5586ca9b0a84b40a4a08a168
status: failed
result:
{
    "succeeded": false,
    "stdout": "",
    "return_code": -9,
    "failed": true,
    "stderr": "",
    "error": "Action failed to complete in 60 seconds"
}
```

Not sure if it's bug or not, but proposal is to consider `timeout: 0` as "no timeout", instead of default 60 seconds. Lots of cases when action doesn't needs any timeouts.

Because things like this in action:
```yaml
parameters:
  timeout:
    default: 99999999
```
definitely looks like there should be a better way.
