### ISSUE TITLE
String conversions in mistral workflows

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2207]
I think we need some means to convert yaml dicts (objects) to json (string) in mistral workflows
Something like `extra-vars: '<% json($.ansible_extra) %>'`
Where ansible extra would be published as something like:
```
        ansible_extra:
          channel: '<% $.rhn_channel %>'
          rset: <% $.rhn_reset %>
          skip_reg: <% $.rhn_skip_registration %>
```

I publish ansible_extra object here defined in YAML, and all I need is to either provide it as is to other action, but converted to string, or convert it to JSON representation as a string and feed it to another action.
