### ISSUE TITLE
Bug - Rules editor doesn't like non-string fields on the calling action

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2235]
If you want to pass on the field of a trigger to an action in a rule and the parameter is an integer or boolean it doesn't let you save the rule, it mangles it in the UI.

Do this:

Create a rule to listen for a webhook and call core.local

for the parameters, set the `timeout` as {{trigger.body.timeout}} (or {{trigger.body.timeout|int}}

Save the rule.

Show the rule and you will see it converted it to:

```yaml
---
uid: 'rule:core:core_local_example'
tags: []
type:
  ref: standard
  parameters:
enabled: true
name: core_local_example
trigger:
  ref: core.379ace8c-dbea-4507-8b22-d94406e426a9
  type: core.st2.webhook
  parameters:
    url: core_example
criteria:
action:
  ref: core.local
  parameters:
    cmd: date
    timeout: NaN
ref: core.core_local_example
id: 5654eae5547088110e38e023
pack: core
```
