### ISSUE TITLE
ChatOps alias parsing failure

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2#2323]
While working on a spiffy new chatops alias today, I ran across this on `pinkiepie`

```
Dec 23 16:00:58 pinkiepie hubot: [Wed Dec 23 2015 16:00:58 GMT+0000 (UTC)] ERROR Failed to retrieve commands from "http://localhost:9101": undefined is not a function
```

Well, ok. Cool. Maybe it's an issue with the API, yeah? Let's see...

```
2015-12-23 16:00:58,862 140342239031856 INFO log [-] f6e429e2-5ea9-46bc-95d3-788a42d9684f - GET /v1/actionalias (remote_addr='127.0.0.1',method='GET',status_code='200 OK',request_id='f6e429e2-5ea9-46bc-95d3-788a42d9684f',path='/v1/actionalias')
```

Nope

So, something is failing at the JS layer (?)... here's the "new" alias (https://github.com/StackStorm/st2-community/pull/10)

```
---
name: "create_issue"
pack: "st2-community"
action_ref: "st2-community.create_issue"
formats:
  - display: "create issue title {{title}} description {{description}}"
  - representation:
    - "create( (a|an))? issue( with)? title(:)? {{title}}( and)? description(:)? {{description}}"
  - "create issue title {{title}} description {{description}}"
description: "File a StackStorm issue from ChatOps"
ack:
  append_url: false
  format: "Got it. Creating that issue for you... :book:"
result:
  format: "All set!"
```

PEBKAC?

**Comment by jfryman** [comment]
Yup. PEBKAK.

YAML formatting matters...

Thanks @emedvedev 

Should be:

```
---
name: "create_issue"
pack: "st2-community"
action_ref: "st2-community.create_issue"
formats:
  - display: "create issue title {{title}} description {{description}}"
    representation:
    - "create( (a|an))? issue( with)? title(:)? {{title}}( and)? description(:)? {{description}}"
  - "create issue title {{title}} description {{description}}"
description: "File a StackStorm issue from ChatOps"
ack:
  append_url: false
  format: "Got it. Creating that issue for you... :book:"
result:
  format: "All set!"
```

Watch that format when using a `regex`. `display` and `representation` are part of the same YAML array element.
