### ISSUE TITLE
Question: How do we make Chatops notifications useful?

### ISSUE THREAD

**Issue by logikal** [StackStorm/st2#2353]
The built-in chatops notifications are pretty useless (the python dictionary of 'result' isn't useful). In order to do our own notifications in our actions or chains, we need to pass the source_channel all the way into the action, which means you always have to trigger the action via chat, which isn't great (i.e. doesn't work, since the notification action will require the source_channel even when it doesn't exist.)

How can we do the following with stackstorm?

We need to be able to check github PR statuses for things like "should I take the next step in my chain", but also be able to do the same thing via chat:

``` yaml
# Chain Example
---
  chain:
    -
      name: get_github_pr_status
      ref: foo.get_pr_status
      params:
        user: "{{user}}"
        repo: "{{repo}}"
        issue_id: "{{pr}}"
      on-success: "build_repo_ci"
    -
      name: build_repo_ci
      ref: foo.build_job
      params:
        status: "{{get_github_pr_status.result.pr_status}"
        user: "{{user}}"
        repo: "{{repo}}"
        issue_id: "{{pr}}"
```

```
# Chat example
Jane: .gh pr status http://github.com/goo/bar/pulls/3
Robot: PR "Fixes the grobblysmack" has green status.
```

Any non-chat method of calling foo.get_pr_issue should do so silently w/r/t chat, and a chat-based method of calling foo.get_pr_issue should do so with a friendly response in chat. How do?

If it's useful, @partkyle and I can hop on to slack and talk about this at length.

**Comment by Kami** [comment]
We recently introduced some ChatOps improvements in v1.2.0 (https://stackstorm.com/2015/12/08/stackstorm-1-2-0-the-new-chatops/) which allow you to format action result for chat purposes in the action alias definition - see "3. Result options" section in the blog post.

`format` alias attribute supports Jinja templating which means you could do something along those lines:

```yaml
result:
  format: "{% if execution.result.pr_status == "green" %}PR "{% execution.result.pr_name %}" has green status.{% else %}FAIL{% endif %}"
```

**Comment by logikal** [comment]
Thanks for pointing us at that, it totally pointed us in the right direction!

We're wondering if we're grabbing data the "right way". Take this alias for an action chain:

``` yaml
---
name: "github_issue_title"
description: "Get title for an issue"
action_ref: packtest.github_issue_title
formats:
  - "gh issue title {{link}}"
ack:
  format: "Aye-aye, cap'n!"
result:
  format: "Woo! {{ execution.result.tasks[-1].result.result.title }}"
```

We're really asking about the `{{ execution.result.tasks[-1].result.result.title }}`. Is this the intended way for us to grab data from a chain?

The chain, for reference:
``` yaml
---
  chain:
    -
      name: parse_link
      ref: core.local
      params:
        cmd: "/opt/stackstorm/packs/packtest/actions/parseurl {{link}}"
      on-success: "get_github_issue"
    -
      name: get_github_issue
      ref: github.get_issue
      params:
        user: "{{parse_link.stdout.user}}"
        repo: "{{parse_link.stdout.repo}}"
        issue_id: "{{parse_link.stdout.pr}}"
```
