### ISSUE TITLE
Mistral concurrency problem

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2370]
st2 version 1.2.0.8

workflow `test.yaml.meta` of a test pack named `epsilon`:
```
---
  description: "Testing concurrency"
  runner_type: "mistral-v2"
  tags: []
  enabled: true
  pack: "epsilon"
  entry_point: "workflows/test.yaml"
  uid: "action:epsilon:test"
  parameters:
    skip_notify:
      default: []
      type: "array"
      description: "List of tasks to skip notifications for."
    task:
      type: "string"
      description: "The name of the task to run for reverse workflow."
    workflow:
      type: "string"
      description: "The name of the workflow to run if the entry_point is a workbook of many workflows. The name should be in the format \"<pack_name>.<action_name>.<workflow_name>\". If entry point is a workflow or a workbook with a si
      default: "epsilon.test.main"
      immutable: true
    conc:
      default: 5
      type: "integer"
      description: "Concurrency"
    context:
      default: {}
      type: "object"
      description: "Additional workflow inputs."
  ref: "epsilon.test"
  name: "test"
```

Workflow `test.yaml` itself:
```
---
version: '2.0'
name: epsilon.test

workflows:
  main:
    type: direct
    input:
      - conc
      - hosts_array:
        - hostname01
        - hostname02
        - hostname03
        - hostname04
        - hostname05
        - hostname06
        - hostname07
        - hostname08
        - hostname09
        
    tasks:

      run_flows:
        # [262, 215]
        workflow: enumerate
        concurrency: <% $.conc %>
        with-items: host in <% $.hosts_array %>
        input:
          name: <% $.host %>

  enumerate:
    type: direct
    input:
      - name
    
    tasks:
      say:
        # [86, 399]
        action: core.local
        input:
          cmd: 'echo <% $.name %>'
```

This ends up with the following result:

![image](https://cloud.githubusercontent.com/assets/4997180/12242053/6491e5be-b85c-11e5-9f2b-a80f957de9eb.png)

Rendering this mistral's feature completely useless.
