### ISSUE TITLE
Error message `Failed to find action [action_name=core.local]` in mistral workflow execution

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2#2527]
Workflow

```
---
version: '2.0'

default.test-simplest:
  tasks:
    task1:
      # [438, 58]
      action: core.local cmd=date
```

metadata
```
{
  "name": "test-simplest",
  "runner_type": "mistral-v2",
  "tags": [],
  "enabled": true,
  "pack": "default",
  "entry_point": "workflows/test-simplest.yaml",
  "notify": {},
  "parameters": {},
  "ref": "default.test-simplest",
  "id": "56ce1506fb3b8760384b972c",
  "uid": "action:default:test-simplest"
}
```

result
```
# st2 execution re-run 56ce1092fb3b8760384b971f
...
id: 56ce1242fb3b8760384b9722
action.ref: default.test-flow
parameters: None
status: failed
start_timestamp: 2016-02-24T20:27:46.324836Z
end_timestamp: 2016-02-24T20:27:51.136697Z
result:
  extra:
    state: ERROR
    state_info: Failed to find action [action_name=core.local]
  tasks: []
```

workaround -
```
action: core.local cmd=date
```
to 
```
action: core.local
input:
    cmd: date
```
or 
```
action: core.local cmd="date"
```
Issue reported by @codyaray
