### ISSUE TITLE
Make action responses declarative

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2552]
We have 2 issues with the current action system:
* You can't return an object, you must return a dict or a list of dicts otherwise the action runner doesn't deserialise the response correctly. So every action pack has it's own way of acheiving the same thing- mapping iteritems on an instance to a dictionary.
* When writing workflows in Mistral, there is no typeahead or checking for field names in variables, same goes for jinja templates in aliases and rules

What I would really like to see is something like this in <action>.yaml

```yaml
---
name: balancer_attach_member
runner_type: python-script
description: Attach a member to a load balancer
enabled: true
entry_point: balancer_attach_member.py
parameters:
  region:
    type: string
    description: The region code
    default: dd-na  
schema:
  type: instance|list|dynamic
  fields:
    id:
      type: integer
    name:
      type: string

```
Then, the Run method of a BaseAction has a __wrapper__ function which performs a dictionary map based on the schema.

The knock on effects are:
* Mistral can be statically validated
* Jinja templates in rules and aliases can be statically validated instead of the trial and error testing that currently exists
* You can see what the response of an action looks like without having to execute it first, making developing workflows a lot faster
* You don't need to write a mapper function for every action

I appreciate this is very "unpythonic" so the schema type would be dynamic by default for people that don't want to be tied down.
