### ISSUE TITLE
Unable to "uncheck" default: True bool param when re-running from UI

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2583]
This is a minor UI usability bug. I have an action with a `default: True` boolean parameter. The rule which normally triggers this action doesn't override the parameter. When I try to re-run the action-triggered-by-the-rule from the UI, the boolean checkbox isn't checked (`True`) even though that was the value used when the action ran. Which means that I can't uncheck it to re-run the rule with a `False` parameter value.

A real-life case for this is the nightly Elasticsearch curator job runs with `should_optimize: true` but when it fails and we have to re-run manually during the day, we don't want to optimize.

![screen shot 2016-03-17 at 11 25 26 am](https://cloud.githubusercontent.com/assets/44062/13853576/4a87a958-ec35-11e5-8d97-15693024d64a.png)

![screen shot 2016-03-17 at 11 25 34 am](https://cloud.githubusercontent.com/assets/44062/13853547/2af262b8-ec35-11e5-9892-a361cf73cfbb.png)

There's some obvious workarounds (invert the option to `skip_optimize` instead of `should_optimize`, pass the parameter as part of the rule to make the checkbox show it correctly, etc). But I wanted to share the bug for others who might have less simple workarounds.

Here's the basic rule:

```

---
name: curate_elasticsearch
description: nightly management job for Elasticsearch
enabled: true

trigger:
    type: "core.st2.CronTimer"
    parameters:
        hour: 00
        minute: 15

action:
    ref: "default.curate_elasticsearch"
    parameters:
        host: "elasticsearch"
```

And the corresponding action metadata:

```

---
name: curate_elasticsearch
description: nightly management job for Elasticsearch
enabled: true

runner_type: action-chain
entry_point: 'workflows/curate_elasticsearch.yaml'

parameters:
  host:
    description: Elasticsearch host
    required: true
    type: string
  should_optimize:
    description: "True to force merge segments. Caution: this is a potentially long-running and disruptive operation"
    type: "boolean"
    default: True
```
