### ISSUE TITLE
Incorrect JSON format

### ISSUE THREAD

**Issue by kiyology** [StackStorm/st2#2608]
Hi,

I'm experiencing this issue when using stackstorm:
Here's my action config:
```
---
description: Run a local linux command
enabled: true
entry_point: workflows/mistral-basic.yaml
name: mistral-basic
pack: examples
parameters:
  payload:
    required: true
    type: object
runner_type: mistral-v2
```

Here's my workflow config:
```
version: '2.0'

examples.mistral-basic:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - payload
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: core.local cmd="node /opt/stackstorm/packs/examples/actions/yamas2-action/yamas2-action.js <% $.payload %>"
            publish:
                stdout: <% $.task1.stdout %>
                stderr: <% $.task1.stderr %>
```

Here's my rule config:
```
---
uid: 'rule:core:yamas2_action'
tags: []
type:
  ref: standard
  parameters:
enabled: true
name: yamas2_action
trigger:
  ref: core.88a53537-2989-41b8-9ec0-e23f7e75447c
  type: core.st2.webhook
  parameters:
    url: yamas2_listener2
criteria:
action:
  ref: examples.mistral-basic
  parameters:
    payload: '{{ trigger.body }}'
ref: core.yamas2_action
id: 57045099a8bf5911aa468d7d
pack: core
```

Basically I'm having a webhook and sends the payload received by the webhook to a mistral workflow action, which takes the payload as the third parameter. 
Everything works fine except that when it's executing, the double quotes inside payload JSON has been substituted by two single quotes which is causing my script to fail when parsing it as a JSON.

Here's the execution detail:
```
id: 57045246a8bf5911aa468d89
status: failed
parameters: 
  cmd: 'node /opt/stackstorm/packs/examples/actions/yamas2-action/yamas2-action.js {u''recovery_alerts'': 0, u''alerts'': [{u''status_code'': 1, u''tags'': {u''host'': u''pubs-yamas2-listener.halo.media.corp.bf1.com'', u''_threshold_name'': u''loadstone_hist'', u''hostgroup'': u''prod_ugeo_ls_all''}, u''timestamp'': 1455315900000000, u''text'': u''Data collection failure''}, {u''status_code'': 1, u''tags'': {u''host'': u''pubs-yamas2-listener.halo.media.corp.bf1.com'', u''_threshold_name'': u''lodestone'', u''hostgroup'': u''prod_ugeo_ls_all''}, u''timestamp'': 1455315900000000, u''text'': u''scoreboard file lodestone does not exist''}], u''namespace'': u''Geo'', u''bad_alerts'': 2}'
result: 
  failed: true
  return_code: 8
  stderr: "
undefined:1
```

And there's a character 'u' in front of all the beginning two single quotes of a string. 
I tried using payload as a string or object. If I use payload as a string, I don't get the character 'u', but all the double quotes are still replaced by two single quotes.

And idea why?

Thanks!
