### ISSUE TITLE
yaml override of timeout parameter not being picked up

### ISSUE THREAD

**Issue by paul-mulvihill** [StackStorm/st2#2611]
Trying to override the default "timeout" parameter for an action via the yaml file. Although my yaml values are not being collected.
I have tried adding 
```
  timeout:
    default: 5
```
As well as 1200. Although when the action runs it remains fixed at the 600 default timeout value.

Manually setting these valuse via the webui work just not via the relevant actions yaml file.

re running register has been done after each yaml adjustment to see if that makes any difference.

**Comment by Kami** [comment]
Thanks for the report.

This sounds like a bug in the way we merge runner and action parameters. We will dig in.

**Comment by Kami** [comment]
I just had a look and wasn't able to reproduced it.

I tried overriding `timeout` runner parameter in the `core.local` action and it worked just fine.

```yaml
---
description: Action that executes an arbitrary Linux command on the localhost.
enabled: true
entry_point: ''
name: local
parameters:
  cmd:
    description: Arbitrary Linux command to be executed on the remote host(s).
    required: true
    type: string
  sudo:
    immutable: true
  timeout:
      default: 5
runner_type: "local-shell-cmd"
```

```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ python ./st2client/st2client/shell.py run core.local cmd="sleep 10"
...
id: 57068ed30640fd01563133a1
status: timeout
parameters: 
  cmd: sleep 10
result: 
  error: Action failed to complete in 5 seconds
  failed: true
  return_code: -9
  stderr: ''
  stdout: ''
  succeeded: false
```

Can you please provide more context - which runner and ideally the whole action definition (you can mask private / sensitive parts).

**Comment by paul-mulvihill** [comment]
here is my yaml content
````
  name: "icsp_job_status_get"
  runner_type: "run-python"
  description: "Return Status of specified Job"
  enabled: true
  entry_point: "icsp_job_status_get.py"
  timeout:
  parameters:
    job_id:
      type: "integer"
      description: "ID for Job, blank will return all jobs listed"
      required: false
      position: 0
    monitor:
      type: boolean
      description: "Monitor Progress of The Job. False = One-time status"
      required: false
      default: false
      position: 1
    connection_details:
      type: "object"
      description: "Connection details. eg { \"host\": \"192.168.0.1\", \"user\":\"username\", \"pass\": \"secret\" }"
      required: false
      secret: true
      position: 3
    timeout:
      default: 5
````
