### ISSUE TITLE
Mistral workflow hangs when calling a task that uses another workflow but references just the workbook

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2#2737]
In workflows/workbook-hangs.yaml below, when the task calls "workflow: ec.workflow-noop" without the ".main" at the end it will cause the workflow to stay in the running state while only showing the first_task_required as completed.

If I remove the task "first_task_required", I get the error I would expect to have seen before:
"state_info": "Failed to find workflow [name=ec.workflow-noop]"

Ubuntu 14.04
mistral --version = mistral 0.1.2
dpkg -s st2mistral = 1.4.0

$ cat workflow-hangs.yaml 
```
name: workflow-hangs
pack: ec
description: 'Workflow: Hangs'
runner_type: mistral-v2
entry_point: workflows/workbook-hangs.yaml
enabled: true
```

$ cat workflows/workbook-hangs.yaml
```
name: ec.workflow-hangs
version: '2.0'
workflows:
    main:
        description: 'Workflow: hangs'
        type: direct
        tasks:
            first_task_required:
                action: core.noop
                on-success:
                    - call_workflow
            call_workflow:
                workflow: ec.workflow-noop
# call_workflow  will only work if you use ec.workflow-noop.main
```

$ cat workflow-noop.yaml
```
name: workflow-noop
pack: ec
description: 'Workflow: noop'
runner_type: mistral-v2
entry_point: workflows/workbook-noop.yaml
enabled: true
```

$ cat workflows/workbook-noop.yaml
```
name: ec.workflow-noop
version: '2.0'
workflows:
    main:
        description: 'Workflow: noop'
        type: direct
        tasks:
            start_noop:
                action: core.noop
```
