### ISSUE TITLE
Policy names can collide across packs.

### ISSUE THREAD

**Issue by tim-ireland** [StackStorm/st2#2848]
We have a situation where there are 2 custom packs, each of which have concurrency policies in place.  One pack has a concurrency policy on a workflow, the other on an action.  In addition, we happen to have given the policies the same name.  

This error was found in the logs.,

```python
StackStormDBObjectConflictError: Tried to save duplicate unique keys (E11000 duplicate key error collection: st2.policy_d_b index: policy_type_1_resource_ref_1 dup key: { : "action.concurrency", : "<pack>.<workflow>" })
```

 It was not immediately apparent that the second policy was not being loaded.  Upon further inspection, it was not listed in the output of `st2 policy list`.

It seems problematic that collisions can occur between policies of separate packs.  Perhaps the policy names should be augmented to include the pack when stored in the backend?

**Comment by Kami** [comment]
Thanks for the report.

I believe, this is a feature - you can only have one `concurrency` policy for each action (primary key is policy type + resource), but would be good for @m4dcoder to confirm it.

As far as not noticing it - we changed the `st2-register-content` script behavior on master so it will fail on failure by default. This should make errors like this more obvious and harder to miss (this change will be included in the upcoming v1.6.0 release).

**Comment by m4dcoder** [comment]
That's right.  It's by design that we enforce uniqueness on policy by type and the resource (i.e. <pack>.<action>).  Otherwise, there could be multiple conflicting policies on a given resource.

**Comment by lakshmi-kannan** [comment]
I am closing this issue as this is feature and confirmed by two engineers. If you want a different behavior, please re-open the issue.

**Comment by andrew-regan** [comment]
If resource is modeled as <pack>.<action> then I don't think we would have seen this since @tim-ireland is reporting that the conflict was a result of a policy across two different packs?

**Comment by andrew-regan** [comment]
Closed literally as I replying. :-)

**Comment by andrew-regan** [comment]
Is this expected to be supported.
PackA has a policy called MyPolicy that protects a workflow called RunSync in PackA.
PackB also has a policy called MyPolicy that protects a action called RunSync in PackB.

@tim-ireland is reporting this doesn't work because both policies are named MyPolicy even though they are working on separate actions/workflows in different packs.

**Comment by m4dcoder** [comment]
I recommend posting the two policies here.

**Comment by andrew-regan** [comment]
```
regana@Reganas-MBP ~/Development/git/plexxiconnectst2> cat packs/plexxi/policies/sync_vsphere_domain_model.yaml 
---
  name: sync_vsphere_domain_model.concurrency
  description: Limits the concurrent executions for the action.
  enabled: true
  resource_ref: plexxi.sync_vsphere_domain_model
  policy_type: action.concurrency.attr
  parameters:
    threshold: 1
    attributes:
      - vsphere_uuid
regana@Reganas-MBP ~/Development/git/plexxiconnectst2> cat packs/connect/policies/sync_vsphere_domain_model.yaml 
---
  name: sync_vsphere_domain_model.concurrency
  description: Limit concurrent execution to prevent overlapping execution
  enabled: true
  resource_ref: connect.sync_vsphere_domain_model
  policy_type: action.concurrency
  parameters:
    threshold: 1
```
