### ISSUE TITLE
Accessing action_context directly within a python-runner

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2#2912]
Often when carrying out actions to external services you want to act as the requesting user (e.g. creating releases, deployments or issues  on GitHub) however the only way to get the api user running the alias into the action is as by adding a parameter to the action as follows (the default is to prevent it failing when run via the ST2 WebUI):

```yaml
  api_user:
    type: "string"
    description: "The API user"
    default: "{{action_context.api_user|default(None)}}"
```

It would be so much easier if `action_context` was available in Python, then you could not mess around with adding parameters and just access them directly as follows:

```python
if action_context.api_user:
  do things as API user... 
else:
  do things as user....
```

And this would keep the action alot cleaner and prevent issues happening due to `api_user` not being set.
