### ISSUE TITLE
Custom Jinja2 filters (feature request)

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2956]
Allow st2 users extend the power of Stackstorm by letting them keep custom jinja2 filters in some directory that st2 would look into. That would add a bit of flexibility extending result formatting capabilities and so forth.

**Comment by lakshmi-kannan** [comment]
@emptywee Please look at https://docs.stackstorm.com/latest/reference/jinja.html#applying-filters-with-jinja and let me know if this is what you want. It looks like you want users to define custom filters in a pack. This could lead to collisions unless we namespace by pack. Then the syntax would look awful. Plus, I really think if useful jinja filters are bubbled up to platform level then we can control the filter behavior.

**Comment by emptywee** [comment]
Yeah, that's something that could be really useful. Just please make sure that the files with custom filters placed in the st2/st2common/st2common/jinja/filters/ directory are not removed during upgrade of Stackstorm installation.

**Comment by LindsayHill** [comment]
@s2ugimot Does this look like something similar to what you are after?

**Comment by s2ugimot** [comment]
@LindsayHill Yes this is exactly what I wanted

**Comment by s2ugimot** [comment]
What I wanted to do originally is to add a small custom filter which does something like `| trim | d('my_value', true)` to cleanup my action yaml definition.

What I have currently in my yaml looks like this:

```
(snip)
parameters:
  hosts:
    type: string
    immutable: true
    default: "{{ system.starrod.config.host | trim | d('ixops-mock', true) }}"
  username:
    type: string
    immutable: true
    default: "{{ system.starrod.config.user | trim | d('naptan', true) }}"
(snip)
```

Looks bit verbose and ugly. My intention here is to give a default value to the parameter if there is nothing set in `st2 key`, but the value returned by accessing none-existent key like `system.some.none-existent.key` seems to be something other than nil, so I need to pass trim first.
