### ISSUE TITLE
Arrays in mistral workflows misinterpreted when used as inputs to tasks/actions

### ISSUE THREAD

**Issue by TuxInvader** [StackStorm/st2#3011]
I have a Trigger/Rule which executes a mistral workflow with a number of input parameters. One of my inputs is called nodes, which is passed to the task like this:
```
    tasks:
        task1:
            action: vadc.vtm_set_pool_nodes
            input:
                vtm: "test"
                pool: "test_pool"
                active: <% $.nodes.split(',') %>
            publish:
                result: <% task(task1).result.result %>
```

If the nodes string has one or more values then the list is passed to the Action correctly. Inside the Action I can see:
```
DEBUG    active: [u''172.17.0.5:80'', u''172.17.0.6:80''] is <type ''list''>
```

But if the string happens to be empty, then the Action still gets a list, but it's not empty:
```
DEBUG    active: [u''[]''] is <type ''list''>
```

Cheers!
