### ISSUE TITLE
mistral workflows get stuck in Running on YAQL 'tuple out of bound' exception

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#3025]
This makes it no easy to handle such type of errors, since it doesn't go via 'on-error' path, but just keeps "running".

Meta:
```yaml
---
name: wf_stuck_in_running
parameters:
  skip_notify:
    default:
      - task
      - error
      - success
    type: array
    description: List of tasks to skip notifications for.
  task:
    type: string
    description: The name of the task to run for reverse workflow.
  workflow:
    type: string
    description: The name of the workflow to run if the entry_point is a workbook
      of many workflows. The name should be in the format "<pack_name>.<action_name>.<workflow_name>".
      If entry point is a workflow or a workbook with a single workflow, the runner
      will identify the workflow automatically.
  context:
    default: {}
    type: object
    description: Additional workflow inputs.
tags: []
description: Reproducing a bug with mistral
enabled: true
entry_point: workflows/wf_stuck_in_running.yaml
notify: {}
uid: action:c_int:wf_stuck_in_running
pack: c_int
ref: c_int.wf_stuck_in_running
runner_type: mistral-v2
```
Workflow:
```yaml
---
version: '2.0'

c_int.wf_stuck_in_running:

  tasks:
    task:
      action: core.noop
      publish:
        # generate tuple out of bound YAQL exception
        var1: <% [1,2,3].reverse().toList()[4] %>
      on-success:
        - success
      on-error:
        - error

    # expecting to hit this task and exit
    error:
      action: core.noop

    success:
      action: core.noop
```

Publishing the `var1` variable should raise an error and go via `error` task.
