### ISSUE TITLE
[st2reactor] Issue about no validation checking before dispatching trigger

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm/st2#3077]
The `dispatch` method on the `SensorService` class doens't check validation of `payload` argument which is passed to TriggerDispatcher with `payload_schema` of Trigger.

So a sensor can send a payload which is in violation of the `payload_schema` to a Trigger without warning or error, like following.

```yaml
---
class_name: 'TestSensor'
entry_point: 'test.py'
description: 'A test sensor'
poll_interval: 5
```

```python
### excerpt of test.py
class TestSensor(PollingSensor):
    def poll(self):
        payload = {
            'hoge': [1,2,3],
        }
        self._sensor_service.dispatch(trigger="linux.file_watch.line", payload=payload)
...
```

This is `payload_scheme` of `linux.file_watch.line` which is a pre-installed Trigger in StackStorm.
```
$ st2 trigger get linux.file_watch.line
...
| payload_schema    | {                                                    |
|                   |     "type": "object",                                |
|                   |     "properties": {                                  |
|                   |         "file_name": {                               |
|                   |             "type": "string"                         |
|                   |         },                                           |
|                   |         "line": {                                    |
|                   |             "type": "string"                         |
|                   |         },                                           |
|                   |         "file_path": {                               |
|                   |             "type": "string"                         |
|                   |         }                                            |
|                   |     }                                                |
|                   | }                                                    |
...
```

Then we could conforme that this invalid payload could be get from the properties of `linux.file_watch.line` as below.

```yaml
---
name: 'test-rule'
description: 'A test rule'
enabled: True
trigger:
  type: linux.file_watch.line

  action:
    ref: 'core.local'
    parameters:
        cmd: 'echo {{trigger}} >> /tmp/test'
```

And the output is here.

```
{hoge: [1, 2, 3]}
{hoge: [1, 2, 3]}
...
```

  I think the validation processing is needed to guarante that trigger output properties are based on `payload_schema` before dispatching Trigger.

Thank you.
