### ISSUE TITLE
Success instead of expected failure in Action result

### ISSUE THREAD

**Issue by skjbulcher** [StackStorm/st2#3133]
**Python runner code**

```
def run(self):
        r = requests.get('https://google.com')
        print r
        return (False, r)
```

I expect the status to be 'failed' because I am returning `False` as the tuple's status indicator, per the documentation. Actual output:

```
.
id: 585486e602ebd502e0980392
status: succeeded
parameters:
result:
  exit_code: 0
  result: None
  stderr: ''
  stdout: '<Response [200]>

    '
```

The same thing happens when I use `self` instead of `r` - the issue might happen when any object is returned as part of the tuple. The docs imply that the result can be any value:

> If the run method finishes without exceptions, the execution is successful, and the value returned by the method (any value: boolean, string, list, dict, etc.) is considered its result. Raising an exception will report the execution as failed.

**Comment by Kami** [comment]
This is weird, indeed - can you please gist the whole action python file?

Which version of StackStorm are you using?

As far as result object goes - yes, it can be any simple python type (boolean, string, list, dict, etc.), but it's better to avoid returning Python objects and other complex types since they can't always be serialized and this can cause issues.

**Comment by skjbulcher** [comment]
Stackstorm 2.1.1

Unfortunately I can't gist the file, because I was fooling around with an API and I don't have the actual file anymore. 

I understand I probably don't want to return a python object; I ran into this bug because I was verifying that my python runner was set up correctly before expanding and refining my code.

I thought it was worth filing a bug report because the exit status of the python runner should be reported correctly regardless of the return value. Otherwise it is dangerous to rely on the exit status for fear of a small bug in action code that returns an object in odd cases.

**Comment by Kami** [comment]
Correct - the type of the result shouldn't affect this (this was just a general heads up).

I can try to replicate it tomorrow, but it would be easier and better if I had actual code to try and replicate it.

**Comment by skjbulcher** [comment]
I just had the above code in my python runner; something like the following should be all you need to replicate the issue:

```
class SuccessOnFailureAction(Action):
    def run(self):
        return (False, self)
```

I'll verify that for you if I get a chance.

**Comment by skjbulcher** [comment]
OK, I just ran the following python script:

```
from st2actions.runners.pythonrunner import Action

class SuccessOnFailureAction(Action):
    def run(self, start, end, status, username):
        return (False, self)
```

which resulted in

```
.
id: 585986f102ebd50ed5fcf33c
status: succeeded
parameters:
  end: beta
  start: alph
  username: me
result:
  exit_code: 0
  result: None
  stderr: ''
  stdout: ''
```
