### ISSUE TITLE
mistral/yaql: distinct for lists of dicts fails

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#3141]
Trying to merge two lists of dicts with unique dicts only. It works perfectly when I test it on yaqluator.com, but fails in mistral workflow with st2.

Meta:
```yaml
---
name: wf_distinct_lists_of_dicts
parameters:
  skip_notify:
    default:
      - start_task
    type: array
    description: List of tasks to skip notifications for.
  task:
    type: string
    description: The name of the task to run for reverse workflow.
  workflow:
    type: string
    description: The name of the workflow to run if the entry_point is a workbook
      of many workflows. The name should be in the format "<pack_name>.<action_name>.<workflow_name>".
      If entry point is a workflow or a workbook with a single workflow, the runner
      will identify the workflow automatically.
  context:
    default: {}
    type: object
    description: Additional workflow inputs.
  list1:
    default: []
    type: array
  list2:
    default: []
    type: array
tags: []
description: Reproducing an error - unhashable type dict
enabled: true
entry_point: workflows/wf_distinct_lists_of_dicts.yaml
notify: {}
uid: action:c_int:wf_distinct_lists_of_dicts
pack: c_int
ref: c_int.wf_distinct_lists_of_dicts
runner_type: mistral-v2
```

Workflow:
```yaml
---
version: '2.0'

c_int.wf_distinct_lists_of_dicts:
  input:
    - list1: []
    - list2: [ {"name": "name1" }, {"name": "name2" }]
  tasks:

    task1:
      action: core.noop
      publish:
        res_list1: <% $.list1 + $.list2 %>

    task2:
      action: core.noop
      publish:
        res_list2: <% distinct($.list1 + $.list2) %>

```
The error I get is:
```
2016-12-22 15:58:35.790 27980 INFO workflow_trace [-] Task execution 'task2' [RUNNING -> SUCCESS] (execution_id=8dcbf598-855c-4e08-a346-36afb30513ed)
2016-12-22 15:58:35.796 27980 ERROR mistral.engine.task_handler [-] An error while publishing task variables [task_execution_id=e343fceb-e018-4f7f-ac91-d76ac0834a58]: Can not evaluate YAQL expression:  distinct($.list1 + $.list2) , data = {u'list2': [{u'name': u'name1'}, {u'name': u'name2'}], u'list1': [], u'__env': {u'st2_liveaction_id': u'585c68a9bd00ef6bb734f0d6', u'st2_execution_id': u'585c68a9bd00ef6bb734f0d7', u'__actions': {u'st2.action': {u'st2_context': {u'endpoint': u'http://0.0.0.0:9101/v1/actionexecutions', u'api_url': u'http://0.0.0.0:9101/v1', u'parent': {u'trace_context': {u'id_': u'585c67bfbd00ef6bb734f0cd'}, u're-run': {u'ref': u'585c6833bd00ef6bb734f0d1'}, u'execution_id': u'585c68a9bd00ef6bb734f0d7', u'user': u'st2admin'}, u'auth_token': u'78be999d83c54754bf7daec49b3ee705', u'notify': {}, u'skip_notify_tasks': [u'task1', u'task2']}}}, u'st2_action_api_url': u'http://0.0.0.0:9101/v1'}, u'__execution': {u'input': {u'list1': [], u'list2': [{u'name': u'name1'}, {u'name': u'name2'}]}, u'params': {u'env': {u'st2_liveaction_id': u'585c68a9bd00ef6bb734f0d6', u'st2_execution_id': u'585c68a9bd00ef6bb734f0d7', u'__actions': {u'st2.action': {u'st2_context': {u'endpoint': u'http://0.0.0.0:9101/v1/actionexecutions', u'api_url': u'http://0.0.0.0:9101/v1', u'parent': {u'trace_context': {u'id_': u'585c67bfbd00ef6bb734f0cd'}, u're-run': {u'ref': u'585c6833bd00ef6bb734f0d1'}, u'execution_id': u'585c68a9bd00ef6bb734f0d7', u'user': u'st2admin'}, u'auth_token': u'78be999d83c54754bf7daec49b3ee705', u'skip_notify_tasks': [u'task1', u'task2'], u'notify': {}}}}, u'st2_action_api_url': u'http://0.0.0.0:9101/v1'}}, u'id': u'8dcbf598-855c-4e08-a346-36afb30513ed', u'spec': {u'input': [{u'list1': []}, {u'list2': [{u'name': u'name1'}, {u'name': u'name2'}]}], u'tasks': {u'task1': {u'name': u'task1', u'publish': {u'res_list1': u'<% $.list1 + $.list2 %>'}, u'version': u'2.0', u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'type': u'direct'}, u'task2': {u'name': u'task2', u'publish': {u'res_list2': u'<% distinct($.list1 + $.list2) %>'}, u'version': u'2.0', u'action': u'st2.action', u'input': {u'ref': u'core.noop'}, u'type': u'direct'}}, u'name': u'c_int.wf_distinct_lists_of_dicts', u'version': u'2.0'}}}; error: unhashable type: 'dict'
```

Without distinct it works.
