### ISSUE TITLE
Unable to access Stackstorm variables in python script

### ISSUE THREAD

**Issue by Ben-Cirrus** [StackStorm/st2#3188]
Currently there is no way to access stackstorm variables (st2_context, etc) from within a python script.

from:
https://stackstorm-community.slack.com/archives/community/p1486447906003183

**Comment by Mierdin** [comment]
Thanks. This could be considered a feature request, but FYI you could use the `{{}}` notation in the action parameters to pass these variables into an action. E.g.:


```
action:
  ref: st2ci.st2_pkg_e2e_test
  parameters:
    hostname: st2-ent-pkg-stable-el7
    distro: RHEL7
    pkg_env: production
    release: stable
    version: "2.2.1"
    enterprise: true
    enterprise_key: "{{st2kv.system.enterprise_key_prd_stable}}"
```
