### ISSUE TITLE
Config.schema's are not applied if there are no configs in /opt/stackstorm/configs/

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2#3258]
Hi,

This a odd one, just built a new 2.2 dev instance to finish up stackstorm-networking_utils#1 and I've found that the following schema for `networking_utils`:

```yaml
isp_db:
  description: "Path to ISP GeoIP2 database"
  type: "string"
  required: true
  default: "/opt/geoip2/GeoIP2-ISP.mmdb"
city_db:
  description: "Path to City GeoIP2 database"
  type: "string"
  required: true
  default: "/opt/geoip2/GeoLite2-City.mmdb"
```

Is only applied if at least 1 config file exists in `/opt/stackstorm/configs/` (for any pack). Without this I was key errors on `isp_db` in my `geoip` action.
