### ISSUE TITLE
Failed rendering value for publish parameter "message" in task - chatops

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3261]
I have the following chatops alias.

```
---
name: 'host_search'
action_ref: 'my_core.search_hosts'
description: 'Searches for puppetized hosts in the infrastructure environment.'
formats:
  - 'host search'
  - display: 'host search <query>|<application>-<role>-<environment>'
    representation:
      - 'host search {{ query }}'
ack:
  enabled: true
  append_url: false
  format: "Alright! Let me check if that matches anything in the infrastructure environment."
result:
  format: |
    {% if execution.status == "succeeded" %}
    {% if execution.result.result | length %}
    Got something for you matching `{{ execution.parameters.query }}`!{~}
    ```
    {% for host in execution.result.result %}
    {{ host }}
    {% endfor %}
    ```

    I can tell you more about a particular host:
    ```
    host get <host>
    ```
    {% else %}
    Unfortunately I couldn't find any hosts for `{{ execution.parameters.query }}`.
    {% endif %}
    {% else %}
    Search failed for `{{ execution.parameters.query }}`.{~}
    Please check {{ execution.id }} for details. PuppetDB problems maybe?
    {% if execution.result.stderr %}*Stderr:* ```{{ execution.result.stderr }}```{% endif %}
    {% endif %}
```

"host search tomcat" => works fine
"host search all" => works fine
"host search" => should return the same as "host search all" but gives an error:

```
{
  "traceback": "  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py\", line 99, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/runners/action_chain_runner/action_chain_runner.py\", line 387, in run\n    chain_vars=self.chain_holder.vars)\n  File \"/opt/stackstorm/runners/action_chain_runner/action_chain_runner.py\", line 503, in _render_publish_vars\n    raise ParameterRenderingFailedException(msg)\n",
  "error": "Failed rendering value for publish parameter \"message\" in task \"format_execution_result\" (template string={{format_execution_result.result.message}}): 'unicode object' has no attribute 'message'"
}
```

The action returned just the same as the "host search all" command, but somehow the trigger produces this error. I can't figure out why. Is this a bug?

**Comment by smw** [comment]
My instance of this seems to have been caused by returning a json string as the results of my action using single quotes:

```
$ st2 execution get 590bfd29b0e44a00b51b7fc6
id: 590bfd29b0e44a00b51b7fc6
status: succeeded (21s elapsed)
parameters: None
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: '{ ''title'': ''Error graph'', ''url'': ''https://xxxxxxx.s3.amazonaws.com/graphs/e92b33e89f8ec914365d3266d8591511ac542ae2.png'', ''link'': ''https://grafana.xxxxxx.net/#/dashboard/db/rxxxxxxx?panelId=8&fullscreen'' }'
  succeeded: true
```

```
st2 execution get 590c00adb0e44a00b51b7fd3
id: 590c00adb0e44a00b51b7fd3
status: succeeded (21s elapsed)
parameters: None
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout:
    link: https://grafana.xxxxxx.net/#/dashboard/db/rxxxxxxx?panelId=8&fullscreen
    title: Error graph
    url: https://xxxxxx.s3.amazonaws.com/graphs/4e471b53d8f9926e6e67d67f5bfa386fc387ddf1.png
  succeeded: true
```

These are caused by stdout formatted like this, respectively:

```
./get-graph.sh
{ 'title': 'Error graph', 'url': 'https://xxxxxx.s3.amazonaws.com/graphs/f079cf7ca90716bd03379b689133fff0ee49ae8b.png', 'link': 'https://grafana.xxxxx.net/#/dashboard/db/rxxxxxxx?panelId=8&fullscreen' }
```


```
./get-graph.sh
{ "title": "Error graph", "url": "https://xxxxxx.s3.amazonaws.com/graphs/f079cf7ca90716bd03379b689133fff0ee49ae8b.png", "link": "https://grafana.xxxxx.net/#/dashboard/db/rxxxxxxx?panelId=8&fullscreen" }
```


The first throws the exception, the second doesn't.

**Comment by smw** [comment]
I wonder if the parsing of stdout into an object shouldn't be more controlled?  Actions should take a config variable pointing to the desired parser?

**Comment by emedvedev** [comment]
@pietervogelaar 
```
formats:
  - 'host search'
  - display: 'host search <query>|<application>-<role>-<environment>'
    representation:
      - 'host search {{ query }}'
```

When you use `host search`, the `query` parameter is not specified, and when you try to access it in `result.format`, it results in an error because it doesn't exist. Just speculating here, but almost sure.

```
      - 'host search {{ query="all" }}'
```

This might help you.
