### ISSUE TITLE
Failed rendering payload value into pattern

### ISSUE THREAD

**Issue by scanterog** [StackStorm/st2#3272]
Hi,

Following is a rule's example. In this snippet, I would like to compare two elements from payload. In this specific case, **host** and **master**. Log shows `UndefinedError: 'trigger' is undefined`. It looks like trigger is not being rendered.

```
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "serf"
criteria:
  trigger.body.event:
    type: "equals"
    pattern: "member-failed"
  trigger.body.host:
    type: "equals"
    pattern: "{{ trigger.body.master }}"
```

Thanks!
