### ISSUE TITLE
How can I validate if redis is used to enforce policies?

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3316]
I have an action-chain and the following policy:

```
---
name: deploy_vm.concurrency
description: Limits the concurrent executions for the deploy_vm workflow
enabled: true
resource_ref: crv_vm.deploy_vm
policy_type: action.concurrency
parameters:
  action: delay
  threshold: 1
```

As documented at https://docs.stackstorm.com/reference/policies.html I had to add Redis or ZooKeeper to the Stack. I chose Redis. I configured a coordinator_url and when I execute two deploy_vm workflows at the same time the second one gets the status "delayed" and start running as soon as the first one is finished. So that works perfectly.

However I was trying to validate If I saw some data in Redis and was curious how the key was composed and what the value was. But during the executions I got the following response everytime:

```
127.0.0.1:6379> keys "*"
(empty list or set)
127.0.0.1:6379> keys "*"
(empty list or set)
127.0.0.1:6379> keys "*"
(empty list or set)
127.0.0.1:6379> keys "*"
(empty list or set)
```

So is Redis indeed used or is something else going on? How can I validate this?
