### ISSUE TITLE
Action re-run fails when action contains a secret parameter

### ISSUE THREAD

**Issue by sidkrishna** [StackStorm/st2#3339]
**Re-runs** for actions that contain a secret param eg. password fail both from CLI and UI. This is happening most probably because the parameter gets passed as `******` instead of the actual value.  
If one changes the param from `****` to actual text, it works. 

Logs: 
```
brocade@BWC:/opt/stackstorm/packs$ st2 execution list -n 1
+--------------------------+-----------------------+--------------+------------------------+-----------------------+--------------------+
| id                       | action.ref            | context.user | status                 | start_timestamp       | end_timestamp      |
+--------------------------+-----------------------+--------------+------------------------+-----------------------+--------------------+
| 58e605f2c3540c086edb46b6 | network_essentials.ge | st2admin     | succeeded (2s elapsed) | Thu, 06 Apr 2017      | Thu, 06 Apr 2017   |
|                          | t_switch_details      |              |                        | 09:10:10 UTC          | 09:10:12 UTC       |
+--------------------------+-----------------------+--------------+------------------------+-----------------------+--------------------+
brocade@BWC:/opt/stackstorm/packs$ st2 execution re-run 58e605f2c3540c086edb46b6
...
id: 58e60699c3540c086edb46b8
status: failed
parameters:
  mgmt_ip: 10.26.7.223
  password: '********'
  username: admin
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 242, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 154, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/network_essentials/actions/get_switch_details.py", line 36, in run
    raise ValueError(e)
ValueError: AuthenticationException('Authentication failed.',)
"
  stdout: ''
```
Here, I am re-running the first action which completed successfully earlier but the re-run fails with `authentication failure`. The same behavior is seen from the UI. I've tested this with more actions/workflows as well.

**Comment by enykeev** [comment]
I can confirm the issue and in some cases it might lead to truly awful consequences. This is the action I was using for testing:

```
---
description: Action that executes an arbitrary Linux command on the localhost.
enabled: true
entry_point: ''
name: some
parameters:
  stuff:
    type: string
    secret: true
  cmd:
    description: Arbitrary Linux command to be executed on the local host.
    required: true
    type: string
    immutable: true
    default: echo {{ stuff }}
  sudo:
    immutable: true
runner_type: "local-shell-cmd"
```

and this is log of running the action

```
vagrant@st2packages-u14:~$ st2 run default.some stuff=thing
.
id: 58e709a11878c11a997bf4e7
status: succeeded
parameters:
  stuff: '********'
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: thing
  succeeded: true
vagrant@st2packages-u14:~$ st2 execution re-run 58e709a11878c11a997bf4e7
.
id: 58e709cc1878c11a997bf4ea
status: succeeded
parameters:
  stuff: '********'
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: bin boot dev etc home initrd.img lib lib64 lost+found media mnt opt proc root run sbin srv sys tmp usr vagrant var vmlinuz
  succeeded: true
```

Now imagine it's not `echo`, but `rm -Rf`.
