### ISSUE TITLE
Changing nested "result" attribute in action reporting

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3342]
In building a custom response for an action alias, I realized that actions report their results via a nested set of `result` keys:

```
vagrant@st2vagrant:/opt/stackstorm/packs/napalm$ st2 run napalm.check_consistency hostname=vsrx01
.
id: 58e7f09cc4da5f5bc3963835
status: succeeded
parameters:
  hostname: vsrx01
result:
  exit_code: 0
  result: null
  stderr: ''
  stdout: ''
```

So, in my alias response, I had to use `execution.result.result` to refer to values returned by the action.

I'm fully acknowledging that I expect that the ratio of value to effort for changing this is probably skewed towards the "not worth it" direction, but figured I'd open the issue anyways to see if it's even worth the discussion. Value:effort aside, it would be nice if the inner attribute was named `values` or something else, other than `result`. `execution.result.values` would definitely look a bit better.
