### ISSUE TITLE
Didn't receive notification after chatops.post_result succeeded

### ISSUE THREAD

**Issue by joeyjy** [StackStorm/st2#3352]
Hi guys,

I followed [official tutorial](https://docs.stackstorm.com/chatops/chatops.html)  and successfully setup st2chatops service in stackstorm.

I created a pack named mychatops and created an alias
mychatops/aliases/remote.yaml:
```
---
name: "remote_shell_cmd"
action_ref: "core.remote"
description: "Execute a command on a remote host via SSH."
formats:
  - "run {{cmd}} on {{hosts}}"
result:
  format: "action completed!"
```

reload the service:
**st2 run packs.setup_virtualenv packs=mychatops && st2ctl reload --register-all
service st2chatops restart**

then go to my rocketChat room(general) and type _!help_, it works well, but after I type _!run date on localhost_ the bot only reply me ack info: 
I'll take it from here! Your execution ID for reference is 58ee0efdfa089f3fa100311e (details available at https://stackstorm01.matrix.corp.com/#/history/58ee0efdfa089f3fa100311e/general)

I checked action history in the webui, the status of chatops.post_result showed succeeded, am I missing some configuration?

I have two default rules
mychatops/rules/notify_hubot.yaml:
```
---
name: "notify"
pack: "mychatops"
enabled: true
description: "Notification rule to send results of action executions to stream for chatops"
trigger:
  type: "core.st2.generic.notifytrigger"
criteria:
  trigger.route:
    pattern: "hubot"
    type: "equals"
action:
  ref: chatops.post_result
  parameters:
    channel: "{{trigger.data.source_channel}}"
    user: "{{trigger.data.user}}"
    execution_id: "{{trigger.execution_id}}"
```

mychatops/rules/notify_general.yaml
```
---
name: "notify_test"
pack: "mychatops"
enabled: true
description: "Notification rule to send results of action executions to stream for chatops"
trigger:
  type: "core.st2.generic.notifytrigger"
criteria:
  trigger.route:
    pattern: "general"
    type: "equals"
action:
  ref: chatops.post_result
  parameters:
    channel: "{{trigger.data.source_channel}}"
    user: "{{trigger.data.user}}"
    execution_id: "{{trigger.execution_id}}"
```

need your help :(
