### ISSUE TITLE
Is a conditional on-success possible?

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3374]
Is a conditional on-success possible? It doesn't seem to work. I think it would be a nice feature.

```
---
chain:
  - name: 'validate'
    ref: 'crv_application.validate'
    parameters:
      server_application: "{{ server_application }}"
      server_role: "{{ server_role }}"
      server_environment: "{{ server_environment }}"
      deploy_type: "{{ deploy_type }}"
    on-success: "{% if deploy_type == 'tomcat' %}get_tomcat_hosts{% else %}get_hosts{% endif %}"
    on-failure: 'notify_failure_chatops'
```
