### ISSUE TITLE
Auto-load k/v pairs during pack install

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3379]
We are developing a hierarchical code structure where we have a "base" pack that contains common workflows, actions and scripts. Workflows and actions in this pack reference keys in the k/v store for various parameters.

Next in our hierarchy are "customer" packs that mainly contain unique values for the various keys in our "base" pack.

We would like to be able to automatically load the k/v pairs for these "customer" packs during pack installation.

One thought on Slack (lakstorm) was to store the k/v data in a JSON file, then import it during pack installation. 

Also need to think about how to handle encrypted data (credentials and such)?

**Comment by nmaludy** [comment]
Thinking about this a little... (not requirements, just trying to feel out what it might look like in the end)

# Location
Datastore files would live in a packs `datastore/` directory.

# Files
Each file in the `datastore/` directory will be a YAML file containing k/v information.
Files will be loaded in sorted alphabetical order. This way the k/v's are loaded in a predictable and consistent manner.

# Formatting
Thought about this for a long time, and because we may want to encrypt data and also may want to specify the scope i've come up with the following:

```
key_name_string:
  value: abc123
key_name_dict:
  value:
    dict_key1: def456
    dict_key2: false
key_name_list:
  value:
    - Ohio
    - Michigan
    - Indiana
key_name_json:
  value: "['test', 'json', 'list']"
key_name_encrypted:
  value: fdsjflkd03u2jlkjflds9
  encrypted: true
key_name_user_scoped:
  value: user_var
  scope: user
  user: st2user
```


Just wanted to jot some ideas down.

**Comment by nmaludy** [comment]
Also thinking Jinja rendering support in the `value:` fields would be nice.

If we loaded the keys in order top-to-bottom, then Jinja rendering would allow us to reference previously loaded k/v's in future values

Example:
```
dns_domain:
  value: domain.tld
vsphere_hostname:
  value: "{{ 'usoh1vsphere1.%s' | format(st2kv.system.dns_domain) }}'
menandmice_hostname:
  value: "{{ 'usoh1menandmice1.%s' | format(st2kv.system.dns_domain) }}'
```

Not sure if that's the right Jinja syntax, but that's the general idea
