### ISSUE TITLE
Config values from workflows

### ISSUE THREAD

**Issue by diellenne** [StackStorm/st2#3388]
Would be really handy being able to read the values defined in a pack configuration file directly from a workflow definition; at the moment the only way I found to use configuration values in a workflow is to add the needed values in the output of an actions and then publish them in the workflow' in this way works but is not really a clean solution.

**Comment by LindsayHill** [comment]
@diellenne you should keep an eye on this PR https://github.com/StackStorm/st2/pull/3183 - I think that will address your requirements?

**Comment by diellenne** [comment]
If it's also supporting Mistral, yes! :)

**Comment by jaf-jaf** [comment]
it would be a useful feature for our workflows too

**Comment by nmaludy** [comment]
As a workaround, until this is implemented, you can use the `config_context` in your workflow's action metadata to a default value from the config

Example:

``` yaml
parameters:
    config_username:
        type: "string"
        description: "Username from the pack's config"
        required: true
        immutable: true
        default: "{{ config_context.username }}"
```
