### ISSUE TITLE
How can I retrieve the user who executed an action inside that action?

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3391]
So I have an action with runner_type: ‘python-script’.

```
from st2actions.runners.pythonrunner import Action


class DeleteVm(Action):
    def run(self, name):

    # Get the username of the user who executed this action
    # ....what code here?
```

**Comment by jjm** [comment]
I don't believe this is possible, if you look at #2912 you can see some ways of dealing with not being able to access the actions context in an action as part of requesting this feature.

**Comment by pietervogelaar** [comment]
In this case I don't want to add a parameter to use {{action_context.user}}, because that can be overridden. So it would be very nice if I can retrieve the actual user who executed the action.

**Comment by jjm** [comment]
You could possibility mark it as `immutable` to prevent anyone changing it. I _may_ have talked to @Kami or @emedvedev about this on Slack before raising the issue for the feature request, but it was last year.

**Comment by pietervogelaar** [comment]
I'm not aware that StackStorm parameter could be marked immutable, but that would also be sufficient indeed.

**Comment by pietervogelaar** [comment]
Cool, that seems possible https://docs.stackstorm.com/actions.html, `immutable: true`. I'm going to try it out.

**Comment by pietervogelaar** [comment]
Yes, this works very nice. Thanks!

```
---
name: 'delete_vm'
runner_type: 'python-script'
description: "Deletes a VM in VMWare vSphere."
enabled: true
entry_point: "delete_vm.py"
parameters:
  name:
    description: VM name
    required: true
    position: 0
  initiator:
    description: The user who executed this action
    required: true
    immutable: true
    default: '{{ action_context.user }}'
```

It also works when this action is used in a workflow:

```
---
chain:
  - name: 'delete_vm'
    ref: 'crv_vm.delete_vm'
    parameters:
      name: "{{ hostname }}"
```
