### ISSUE TITLE
Can't access action.stdout in 'notify' scope

### ISSUE THREAD

**Issue by hagay3** [StackStorm/st2#3403]
I'm trying to build action-chain workflow and I have a desire to use action.stdout within notify scope.
notify scope is the way to notify other systems (slack/hipchat) about action that just happened.
The thing is that apparently the variable is not accessible inside the notify scope, I just get {{some-variable}} name and not the variable content.

Example:
```
       -
        name: "check_down_endpoints"
        ref: "cassandra.check_down_endpoints"
        parameters:
            consul_servicename: '{{alert_body.commonLabels.servicename}}'
        on-failure: "fail_on_more_than_one_node"
        notify:
          on-success:
              routes:
                - hipchat
              message: "[StackStorm][SUCCESS] Workflow bla bla passed"
    -

        name: "Second-Action"
        ref: "core.remote_sudo"
        parameters:
            cmd: "<some command in here>"
            hosts: "{{check_down_endpoints.stdout.node}}"
            timeout: 1200
        on-success: "check"
        on-failure: "fail"
        notify:
          on-failure:
            routes:
              - hipchat
            message: "fail: {{action_parameters.hosts}}"
    -
```

When trying to get access to variable {{check_down_endpoints.stdout}} in here, I just get the variable name itself with brackets.

If this is meant to be it's really disappointing, there is a way to workaround that?
By the way didn't find what more action_context variables that is available - to those vars I can reach.
Also action_parameters are accessible so its good but still lack of information like stdout of other actions.

```
        notify:
          on-failure:
            routes:
              - hipchat
            message: "fail: {{check_down_endpoints.stdout}}"
``` 
message output in chat:  "fail: {{check_down_endpoints.stdout}}"
Not the variable content as expected.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1494999864478724

**Comment by hagay3** [comment]
I have another issue with the notify scope, rule is defined with parameters that generated out of the webhook trigger payload. Then I cant access to those parameters inside notify scope.

Rule:
```
action:
    parameters:
        hostname: '{{trigger.body.commonLabels.instance}}'
        alertname: '{{trigger.body.commonLabels.alertname}}'
    ref: cassandra.cassandra_restart_chain_meta
criteria: {}
description: 'cassandra restart'
enabled: true
name: '****'
pack: ****
ref: *****
tags: []
trigger:
    parameters:
        url: *****
    type: core.st2.webhook
type:
    parameters: {}
    ref: standard
```

Action chain meta:
```
---
# Action definition metadata
name: "cassandra_restart_chain_meta"
description: "********"

# `runner_type` has value `action-chain` to identify that action is an ActionChain.
runner_type: "action-chain"

# `entry_point` path to the ActionChain definition file, relative to the pack's action directory.
entry_point: "workflows/cassandra_restart_chain.yaml"

enabled: true
parameters:
  hostname:
    required: true
    type: string
  alertname:
    type: string
```

And there is no way inside notify scope to access "alertname" variable.

Action Chain :
```
        notify:
          on-failure:
            routes:
              - hipchat
            message: "alert: {{alertname}}"
```

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1495052818792965

**Comment by hagay3** [comment]
I fought this one for a while.
Eventually used the key value store, first stored the json as string:
```/usr/bin/st2 key set alert "{'alert' : 'test1'}" ```

Then in action definition passed in default the value:
```
alert:
    type: 'string'
    required: false
    default: "{{st2kv.system.alert}}"
```
