### ISSUE TITLE
unexpected token while trying to pass json content inside a variable

### ISSUE THREAD

**Issue by hagay3** [StackStorm/st2#3419]
Hi,
I'm trying to pass json variable to a script , tried to use string and object types with no luck.
Ended up with a failure on the json variable and stackstorm mentioned the content.
Tried also to write the variable in few ways (no luck on this one also):
'{{ var }}'
'{{var}}'
"{{ var }}"
"{{var}}"

Error while the var type is object:
```746: unexpected token at '{u'commonLabels': {u'service': u'test123'}, u'alertname': u'alertname111'}''```

Error while the var type is string:
```746: unexpected token at '{'alertname': 'some-alertname', 'commonLabels': {'service': 'service12'}}'```

Action chain looks like that
```
chain:
  -
      name: "check1"
      ref: "core.local_sudo"
      parameters:
          cmd: "echo ss"
      on-failure: "check2"
      on-success: "check2"
      publish:
        message: "[SUCCESS] Test123 "
  -
      name: "check2"
      ref: "hipchat.send-message-formatted"
      parameters:
          message:   "{{message}}"
          alertbody: '{{ alertbody }}'

```

Action chain meta:
```
---
# Action definition metadata
name: "send-message-test-meta"
description: "Send test message to hipchat"

# `runner_type` has value `action-chain` to identify that action is an ActionChain.
runner_type: "action-chain"

# `entry_point` path to the ActionChain definition file, relative to the pack's action directory.
entry_point: "workflows/send-message-action-chain-test.yaml"


enabled: true
parameters:
  alertbody:
    type: object

```

Rule:
```
---
name: "notify_hipchat_test"
pack: "hipchat"
description: "Rule to notify hipchat"
enabled: true
trigger:
    parameters:
        url: hipchat_test
    type: core.st2.webhook
criteria: {}

action:
  ref: "hipchat.send-message-test-meta"
  parameters:
    alertbody: '{{ trigger.body }}'

```
