### ISSUE TITLE
Feature Request: support multiple, independently configured, sensor instances.

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#3438]
Please add the ability to have one sensor running more than once with separate configuration. Others have already worked on this feature as (See PR #1739), but the PR was closed due to (I think) inactivity of the @manasdk the initial author.

I am writing a PollingSensor where it would be very nice to have separate configuration for multiple instances of the same sensor. For instance, I have some number of servers with a service that needs to be polled for changes. However some servers are with one hosting provider (one set of configuration), and some in a different hosting provider. I would like one instance of my sensor for each hosting provider, and possibly one instance per server.

Though there are only a few today of these servers today, that number could become elastic in the future. Also, it would be nice to have separate config for different environments (production vs testing vs dev) without maintaining separate instances of stackstorm. Plus that would allow me to have one environment (say dev) using a higher version of the service than another (say production) with different sensor instances to make sure integrations work as expected.

Also, I think it would make sense for the sensors in [git](https://github.com/StackStorm-Exchange/stackstorm-git), [github](https://github.com/StackStorm-Exchange/stackstorm-github), and other packs (I wish bitbucket had a sensor) to allow watching multiple things with perhaps different credentials. Then if there are any issues with one sensor (say misconfiguration, credentials stop working, api version changes for one instance but not another, or something) it won't affect the other sensors.

**Comment by koenbud** [comment]
This feature is exactly what I am looking for too. I have sensors that do statistical analysis and I need to run multiple similar sensors, but with a different set of parameters. I want to avoid repeating code in multiple sensors.

I am new to StackStorm, so I am not fully familiar with the design principles, but one of the solutions that came to mind is to allow configuration parameters in the sensor metadata yaml file. In the sensor python script the parameter self._config would then contain a merge the pack and the sensor configuration, where the sensor configuration would take precedence. You can then create multiple sensors that point to the same python sensor script.

Example where I have added a configuration node:

```yaml
---
  class_name: "SampleSensor"
  entry_point: "sample_sensor.py"
  description: "Sample sensor that emits triggers."
  configuration:
    foo: "bar"
    timeout: "60"
  trigger_types:
    -
      name: "event"
      description: "An example trigger."
      payload_schema:
        type: "object"
        properties:
          executed_at:
            type: "string"
            format: "date-time"
            default: "2014-07-30 05:04:24.578325"
```
