### ISSUE TITLE
pillar args cannot be set more than 1?

### ISSUE THREAD

**Issue by sujuanliu** [StackStorm/st2#3443]
When running a custom salt state via st2 CLI, i got the following errors. If running the follow st2 CLI with one pillar args,  it will execute sucessfully.  It looks pillar data cannot be greater than 1 argument.

**Successful:**
st2 run salt.local module=state.apply args=adduser,pillar='{"uname": "test"}'

```
status: succeeded
parameters: 
  args:
  - adduser
  - 'pillar={"uname": "test"}'
  module: state.apply
result: 
  exit_code: 0
  result:
    return:
    - iZ23ljlgvuaZ:
        file_|-Change homedir mode_|-/home/newuser1_|-directory:
          __id__: Change homedir mode
          __run_num__: 3
          changes:
            group: newuser_group
          comment: Directory /home/newuser1 updated
```

**Not Successful:**
st2 run salt.local module=state.apply args=adduser,pillar='{"uname": "test", "ugroup": "test"}'

```
status: succeeded
parameters: 
  args:
  - adduser
  - 'pillar={"uname": "test"'
  - '"ugroup": "test"}'
  module: state.apply
result: 
  exit_code: 0
  result:
    return:
    - iZ23ljlgvuaZ: **Passed invalid arguments to state.apply: apply_() takes at most 1 argument (10 given)**

    .. versionadded:: 2015.5.0

    This function will call :mod:`state.highstate
    <salt.modules.state.highstate>` or :mod:`state.sls
    <salt.modules.state.sls>` based on the arguments passed to this function.
    It exists as a more intuitive way of applying states.

    .. rubric:: APPLYING ALL STATES CONFIGURED IN TOP.SLS (A.K.A. :ref:`HIGHSTATE <running-highstate>`)

    To apply all configured states, simply run ``state.apply``:
```
