### ISSUE TITLE
Jinja templating broken in action notify section

### ISSUE THREAD

**Issue by cwkatzmann** [StackStorm/st2#3487]
When I run an action and try to reference any of its output values in jinja template format, the literal string of the template itself is used. For example, the message output is `"@channel: Action run by {{action_context.user}} succeeded. Cmd run was {{cmd}}."`

The documentation demonstrates this feature here: https://docs.stackstorm.com/chatops/notifications.html#jinja-templating-in-message-and-data

**Comment by lakshmi-kannan** [comment]
@cwkatzmann When referring to the output and parameters, are you using {{ action_parameters.cmd }} and {{ action_parameters.output }}. The context "action_parameters" is required.

**Comment by lakshmi-kannan** [comment]
Related: https://github.com/StackStorm/st2/issues/3403

**Comment by nmaludy** [comment]
@lakshmi-kannan i've been doing some digging on this and noticed the same thing.

@cwkatzmann original problem came from the following action yaml:

```
---
name: "guest_wifi"
runner_type: "local-shell-cmd"
parameters:
  cmd:
    type: "string"
    default: "cat /home/stanley/guest_wifi.txt"
notify:
  on-complete:
    routes:
    - chatops_override
    message: "{{action_results.stdout}}"
```


I did some digging and printed out the Jinja context before rendering the message and noticed that `action_results` is empty:
```
st2notifier.log:2017-06-16 16:00:24,003 44250928 INFO notifier [-] nmaludy: context = {'action_context': {u'user': u'st2admin'}, 'action_results': {}, 'action_parameters': {u'cmd': u'cat /etc/hosts'}, 'st2kv': {'system': <st2common.services.keyvalues.KeyValueLookup object at 0x2b0e250>}}
```
