### ISSUE TITLE
detailed execution output does not show published vars for action-chain workflows

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#3518]
Given this action-chain:
```yaml
chain
  -
    name: 'test_publish'
    ref: 'core.noop'
    publish:
      something: 'register this'
```

`st2 execution get -d <workflow id>` doesn't show the published vars. A mistral workflow shows 'published' entry for each task that publishes something. It would be nice if action-chains did the same.
