### ISSUE TITLE
Actions in Mistral workflow succeed, but workflow marked as failed

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3549]
> Recording this for posterity, as I ran into this once shortly after I started working on StackStorm, and would have loved to see this myself.

I was tinkering with `mistral-basic` workflow in the `examples` pack, and converted some of it to use Jinja instead of YAQL. After running it, however, I noticed that - while my action execution succeeded, the workflow itself returned a failure:

```
vagrant@st2vagrant:/opt/stackstorm/packs/napalm$ cat /opt/stackstorm/packs/examples/actions/workflows/mistral-basic.yaml
version: '2.0'

examples.mistral-basic:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - cmd
    output:
        stdout: "{{ _.cmd }}"
    tasks:
        task1:
            action: core.local cmd="{{ _.cmd }}"
            publish:
                stdout: "{{ task('task1').result.stdout }}"
vagrant@st2vagrant:/opt/stackstorm/packs/napalm$ st2 run examples.mistral-basic cmd="echo Helllo"
...
id: 595dd67bc4da5f0521ea90c7
action.ref: examples.mistral-basic
parameters:
  cmd: echo Helllo
status: succeeded
start_timestamp: 2017-07-06T06:19:39.787181Z
end_timestamp: 2017-07-06T06:19:44.716185Z
+--------------------------+------------------------+-------+------------+-------------------------------+
| id                       | status                 | task  | action     | start_timestamp               |
+--------------------------+------------------------+-------+------------+-------------------------------+
| 595dd67cc4da5f0521ea90ca | succeeded (0s elapsed) | task1 | core.local | Thu, 06 Jul 2017 06:19:40 UTC |
+--------------------------+------------------------+-------+------------+-------------------------------+
```
