### ISSUE TITLE
Feature Request: expose pack config to rules/triggers

### ISSUE THREAD

**Issue by ytjohn** [StackStorm/st2#3576]
Today, I wanted to add an IntervalTimer trigger, and I wanted to have the delta set in configuration.

I think it would be advantageous to allow end-users of my pack to set the interval delta (and unit) in configuration instead of having to edit the pack's yaml file.

```
trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    unit: "{{config_context.rule1_unit}}"
    delta: {{config_context.rule1_delta}
```

related to #3183
