### ISSUE TITLE
EL6/EL7 failure 'SSL3_GET_SERVER_CERTIFICATE' after recent pip upgrade [staging-unstable]

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3596]
This affects `staging-unstable` packages for now. Recent massive pip versions upgrade (#3538) broke `EL6`/`EL7` builds with e2e tests with the following error:

```
[root@st2-ent-pkg-unstable-el7 stanley]# st2 run core.http url=https://google.com/
.
id: 5971d6acd549c538fa717614
status: failed
parameters: 
  url: https://www.google.com
result: 
  error: '("bad handshake: Error([(''SSL routines'', ''SSL3_GET_SERVER_CERTIFICATE'', ''certificate verify failed'')],)",)'
  traceback: "  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py\", line 105, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/runners/http_runner/http_runner.py\", line 93, in run\n    result = client.run()\n  File \"/opt/stackstorm/runners/http_runner/http_runner.py\", line 217, in run\n    verify=self.verify\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py\", line 58, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py\", line 502, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py\", line 612, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\n"
```

After reverting back to revision before #3538 upgrade everything is OK:
```
[root@st2-ent-pkg-unstable-el7 stanley]# st2 run core.http url=https://google.com/
.
id: 5971d94ed549c543310da786
status: failed
parameters: 
  url: https://google.com/
result: 
  body: "<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>301 Moved</TITLE></HEAD><BODY>\n<H1>301 Moved</H1>\nThe document has moved\n<A HREF=\"https://www.google.com/\">here</A>.\r\n</BODY></HTML>\r\n"
  headers:
    Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
    Cache-Control: public, max-age=2592000
    Content-Length: '220'
    Content-Type: text/html; charset=UTF-8
    Date: Fri, 21 Jul 2017 10:37:02 GMT
    Expires: Sun, 20 Aug 2017 10:37:02 GMT
    Location: https://www.google.com/
    Server: gws
    X-Frame-Options: SAMEORIGIN
    X-XSS-Protection: 1; mode=block
  parsed: false
  status_code: 301
```

Probably related to `requests` pip upgrade: https://github.com/StackStorm/st2/pull/3538/files#diff-a5f1fcca145ad8adf14b1a41a811b878R15

Latest good revision for `EL7` is: https://packagecloud.io/StackStorm/staging-unstable/packages/el/7/st2-2.4dev-38.x86_64.rpm
