### ISSUE TITLE
Feature Request - Ability to execute Mistral on-success tasks sequentially

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3619]
We have a workflow: 
```
version: '2.0'
encore.check_hostname:
  description: >
    This is a workflow to determine if the hostname that is trying to be used has already been used
  type: direct
  input:
    - session
    - connection
    - server
    - username
    - password
    - port
    - transport
    - hostname
    - dns_name
  tasks:
    main:
      action: std.noop
      on-success:
        - login: "{{ not _.session }}"
        - get_dns_zone

    login:
      action: menandmice.login
      input:
        connection: "{{ _.connection }}"
        server: "{{ _.server }}"
        username: "{{ _.username }}"
        password: "{{ _.password }}"
        port: "{{ _.port }}"
        transport: "{{ _.transport }}"
      publish:
        session: "{{ task('login').result.result.session }}"

    get_dns_zone:
      action: menandmice.get_dns_zones
      input:
        session: "{{ _.session }}"
        server: "{{ _.server }}"
        filter: "type:master name:^{{ _.hostname }}.{{ _.dns_name }}.$"
      publish:
        dns_zone_ref: "{{ task('get_dns_zone').result.result.dnsZones.dnsZone[0].ref}}"
```

We expect that the tasks in `main`'s `on-success` block are executed sequentially.

Unfortunately, it appears that mistral defaults to executing these tasks in parallel. Below is an example output. Running this same workflow multiple times produces unpredictable results due to the parallel execution.

```
..................
id: 597a17c519e13d0b4f330872
action.ref: encore.check_hostname
parameters: 
  dns_name: xxx.xx.xx
  hostname: xxx
  password: '********'
  server: xxx.xx.xx
  username: administrator
status: failed
result_task: login
result: 
  exit_code: 0
  result:
    session: abc123
  stderr: ''
  stdout: ''
start_timestamp: 2017-07-27T16:41:41.583210Z
end_timestamp: 2017-07-27T16:42:21.134424Z
+--------------------------+-------------------------+--------------+--------------------------+-------------------------------+
| id                       | status                  | task         | action                   | start_timestamp               |
+--------------------------+-------------------------+--------------+--------------------------+-------------------------------+
| 597a17d119e13d0b4f330876 | failed (18s elapsed)    | get_dns_zone | menandmice.get_dns_zones | Thu, 27 Jul 2017 16:41:53 UTC |
| 597a17d119e13d0b4f330877 | succeeded (19s elapsed) | login        | menandmice.login         | Thu, 27 Jul 2017 16:41:53 UTC |
+--------------------------+-------------------------+--------------+--------------------------+-------------------------------+
```

I've tried setting `concurrency: 1` as a shot in the dark, but as @lakshmi-kannan pointed out, this only works for tasks that have a `with-items:` block.

Our "use case" for having this `main` block is to have a general, high level, overview of what the workflow is actually doing for simple (mostly) linear workflows.

**Comment by m4dcoder** [comment]
The feature request can be accomplish if you rewrite the workflow like below.  Since get_dns_zone depends on session, use conditions in the on-success to handle appropriate transition.  If you want tasks to happen sequentially, you have to use the on-success properly at each tasks.  Making the array in on-success to run sequentially is not consistent w/ the workflow language principle because it's then possible to just put all the tasks under on-success of the first task node.

```
main:
    on-success:
        - login: "{{ not _.session }}"
        - get_dns_zone: "{{ _.session }}"
login:
    on-success:
        - get_dns_zone
get_dns_zone:
    ....
```
