### ISSUE TITLE
Feature Request - Chatops Parameters

### ISSUE THREAD

**Issue by mickmcgrath13** [StackStorm/st2#3621]
It'd be super nice if we could do this:
```
---
name: get-items
pack: mypack
description: "Mypack: Get items"
action_ref: "mypack.get-items"
formats:
  - display: "mypack get all items"
    representation:
      - "mypack get all items"
parameters:
  - with_subitems: 
      default: True
```
