### ISSUE TITLE
Sub Packs

### ISSUE THREAD

**Issue by mickmcgrath13** [StackStorm/st2#3698]
It might be nice to be able to separate a pack into sub-packs.  These sub-packs would still be part of a pack and would allow devs to break up a service into smaller logical groups.

One good example that could potentially benefit from this is the [AWS Pack](https://github.com/StackStorm-Exchange/stackstorm-aws).  

It has [so many actions](https://github.com/StackStorm-Exchange/stackstorm-aws/tree/master/actions), and maybe each service could be its own sub-pack?

**Comment by nmaludy** [comment]
I think this is related to https://github.com/StackStorm/st2/issues/3336

**Comment by warrenvw** [comment]
@mickmcgrath13 In #community, you also mentioned something to the effect that sub-packs could support permissions. Could you add some details if this is a feature you think we should consider?

**Comment by mickmcgrath13** [comment]
I'm thinking of something like:

```
packs/aws
  - acm
    - actions
    - aliases
  - apigateway
    - actions
    - sensors
    - etc
```
not a fully formed thought (with that, you couldn't have a sub-pack called "actions" for example)...

@nmaludy With that info, are you still thinking it's related to #3336 ?  If so, maybe explain a bit more how they're related?

**Comment by nmaludy** [comment]
@mickmcgrath13 I'm thinking that the "sub-packs" would actually be full fledged packs themselves (and installed independently if desired).

With dependency resolution the "super pack" or "parent pack" can declare a bunch of "sub packs" as dependencies. Example:

```
---
packs:
  aws_aaa:
    url: https://github.com/StackStorm-Exchange/stackstorm-aws_aaa.git
  aws_bbb:
    url: https://github.com/StackStorm-Exchange/stackstorm-aws_bbb.git
  aws_ccc:
    url: https://github.com/StackStorm-Exchange/stackstorm-aws_ccc.git
  aws:
    url: https://github.com/StackStorm-Exchange/stackstorm-aws.git
    dependencies:
      - aws_aaa
      - aws_bbb
      - aws_ccc
 ```
