### ISSUE TITLE
Action Aliases and Workflows not Properly Sending Results

### ISSUE THREAD

**Issue by silverbp** [StackStorm/st2#3699]
When creating an Action Alias that references a Workflow Action instead of a regular Action.

It doesn't abide by the result you specify: 

```
result:
  format: "hello world"
```

Instead you get the default result posted to slack for each action executed in the workflow which is not what we want.

**Comment by LindsayHill** [comment]
Could you provide the complete action alias, workflow definition and metadata?

Sounds like you may need to skip notifications - see https://docs.stackstorm.com/chatops/notifications.html#how-do-i-skip-notifications-for-tasks-in-workflow-or-chain

**Comment by silverbp** [comment]
Hm, nice, I think that will resolve part of my issue, but if the Action Alias is this
```
---

name: deploy_artifacts
pack: ems
description: "Deploy Artifacts"
action_ref: "ems.deploy_artifacts"
formats:
  # - "deploy packages in {{ environment }}"
  - "deploy artifacts in {{ environment }}"
ack:
  format: "Deploying Artifacts..."
  append_url: false
result:
  format: "{% execution.result.result.message %}"
```

and my workflow is something like this
```
