### ISSUE TITLE
Policy to rate-limit action executions

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3720]
According to https://docs.stackstorm.com/reference/policies.html, we have `concurrency` and `retry` policies.

And while concurrency is useful, it's not enough in some cases. 
> This example comes as a note from SREcon 17 Dublin where we configured demo: Twitter sensor to listen on all [#srecon tweets](https://twitter.com/search?q=%23srecon&src=typd) and change LED colors on every tweet.
[> Click here for photo](https://camo.githubusercontent.com/b097e46678884f4f3b89f3e8f5e31019e8ae7c10/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4449646f61683057734141536736723f666f726d61743d6a7067)
The problem is that sometimes there were too many tweets/per second and we definitely didn't want to change the LED colors with such a high rate. Here limiting executions/per time period could be very useful.

The proposal is to implement rate-limiting policy so we could limit the action executions based on time `executions/second`, `executions/time interval` and cancel everything that exceeded the rate limit window.

#### Proposed policy example
```yaml
---
name: rate-limit-http-downloads
description: > Run max 3 'core.http' actions/second
               and cancel everything that exceeds the limit
enabled: true
resource_ref: core.http
# alternative: 
# policy_type: action.limit
policy_type: action.rate_limit
parameters:
    # maximum number of executions per time interval window
    threshold: 3
    # 100ms, 1s, 315s, 15m, 1h
    interval: 1s
    # cancel actions exceeding the 3 actions/s limit
    action: cancel
```

I believe this is typical and pragmatic instrument that might be very popular in a wild.
