### ISSUE TITLE
task(<task_name>).result in mistral workflow with loop tasks

### ISSUE THREAD

**Issue by hujunya** [StackStorm/st2#3765]
version:
```
# st2 --version
st2 2.0.1

# mistral --version
mistral 2.1.1
```

workflow:
```
version: "2.0"
name: test.loop_wf
description: Loop test

workflows:

    main:
        type: direct
        tasks:

            task0:
                action: core.noop
                on-success:
                    - task1

            task1:
                action: core.local
                input:
                    cmd: "date"
                publish:
                    date: <% task(task1).result.stdout %>
                on-success:
                    - task2

            task2:
                action: core.local
                input:
                    cmd: "echo <% $.date %>"
                on-success:
                    - task1

```

run:
![image](https://user-images.githubusercontent.com/3195755/30847026-8e6b96da-a2cc-11e7-9579-b9710cd7108f.png)

The result of task1 has changed when it run again:
![image](https://user-images.githubusercontent.com/3195755/30847706-0ae0db38-a2cf-11e7-8481-c3c9ff30c32b.png)

`<% task(task1).result.stdout %>` always get the result of task1 when it first run. It doesn't refresh when the task1 run again.

Is this a bug ?
How can I get the new result of task1 when it run again ?
