### ISSUE TITLE
multiple alias formats not working

### ISSUE THREAD

**Issue by bartwalczak1** [StackStorm/st2#3770]
I am trying to put multiple formats in single alias

following this --> https://docs.stackstorm.com/chatops/aliases.html#multiple-formats-in-a-single-alias

here's alias I've put together

 ```
---
name: "get_ip_address"
pack: "core"
description: "get_ip_address"
action_ref: "core.get_ip_address"
formats:
      - "get ip {{tag_key}} {{tag_value}} {{tag_key2}} {{tag_value2}}"
      - "get ip {{tag_key}} {{tag_value}}"
ack:
  format: "Thinking...\n Execution id: '{{execution.id}}'"
  enabled: false
  append_url: false
result:
  extra:
    slack:
      color: "#00AA00"
      pretext: "Here's your response {{execution.context.api_user}}"
      title: "title"
      text: "optional text"
  format: |
    {{ execution.result.stdout}}
```

when I hit `!st2 get ip ec2_tag_cluster qa-blue` I am getting result, but when I hit `!st2 get ip ec2_tag_cluster qa-blue a b`

I am getting `st2 command 'get ip ec2_tag_cluster qa-blue a b' not found.  Check help with !st2help`

in st2help I can see two formats listed

 ```
!st2 get ip {{tag_key}} {{tag_value}} {{tag_key2}} {{tag_value2}} -- get_ip_address
!st2 get ip {{tag_key}} {{tag_value}} -- get_ip_address
```
