### ISSUE TITLE
{{ env }} not usable

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2#3791]
I'm not sure if it's me doing stupid things or not undertanding how this all works, but...
Looking at the [actions documentation](https://docs.stackstorm.com/actions.html#built-in-parameters), it looks like I should be able to use {{ env }} in my jinja expression, but this is actually failing:

```
---
description: T
enabled: true
entry_point: 't.sh'
name: t
runner_type: local-shell-script
parameters:
    t:
        type: "string"
        description: "T"
        required: true
        default: "action: {{ action_context }} execid: {{ env }}"
        position: 1
...
```

The t.sh script just echoes its given parameters

Results in this:
```
stdout: 'action: {u''trace_context'': {u''id_'': u''59e6019ca013de643478a987''}, u''pack'': u''oiobuild'', u''re-run'': {u''ref'': u''59e60302a013de643478a98b''}, u''user'': u''stanley''} execid: None'
```

What I want to do is use execution ID in a "notify" to let user have a back link to st2:

```
notify:
  on-success:
    message: "To find more details, go to: https://stackstorm.openio.io/#/history/{{ env.ST2_ACTION_EXECUTION_ID }}/general"
```

I didn't find any help in the doc, een if the `env()` one, from [here](https://docs.stackstorm.com/mistral_jinja.html#mistral) looked promizing...

What am I missing ?
