### ISSUE TITLE
Mistral tasks() function errors when used in input: section

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3801]
## Problem

When coding a Mistral workflow i'm unable to utilize the built-in function `tasks()` anywhere in the `input:` section. Upon doing so i get the following error:

```
| result          | {                                                            |
|                 |     "traceback": "  File "/opt/stackstorm/st2/lib/python2.7  |
|                 | /site-packages/st2api/controllers/v1/actionexecutions.py",   |
|                 | line 180, in _schedule_execution                             |
|                 |     liveaction_db.context)                                   |
|                 |   File "/opt/stackstorm/st2/lib/python2.7/site-              |
|                 | packages/st2common/util/param.py", line 230, in              |
|                 | render_live_params                                           |
|                 |     _validate(G)                                             |
|                 |   File "/opt/stackstorm/st2/lib/python2.7/site-              |
|                 | packages/st2common/util/param.py", line 145, in _validate    |
|                 |     raise ParamException(msg)                                |
|                 | ",                                                           |
|                 |     "error": "Dependecy unsatisfied in tasks"                |
|                 | }                                                            |
```

This backtrace is also present in the st2api logs.

## Steps to reproduce

Simply run the following action/workflow

``` yaml
---
description: "Reproduce errors when running tasks() function in a mistral workflow"
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-tasks-error-simple.yaml
name: mistral-tasks-error-simple
pack: examples
parameters:
  str:
    required: false
    type: string
```

``` yaml
version: '2.0'

examples.mistral-tasks-error-simple:
    description: "Reproduce errors when running tasks() function in a mistral workflow"
    type: direct
    input:
        - str
        
    output:
      tasks_published_jinja: "{{ _.tasks_published_jinja }}"
      tasks_published_yaql: "{{ _.tasks_published_yaql }}"
        
    tasks:

        # this works
        tasks_in_publish:
            action: std.noop
            publish:
                tasks_published_jinja: "{{ tasks(execution().id) }}"
                tasks_published_yaql: <% tasks(execution().id) %>
            on-success:
                - tasks_in_input_jinja
                #- tasks_in_input_yaql
                #- tasks_in_input_jinja_plain
                #- tasks_in_input_jinja_variable
                
        # this breaks
        tasks_in_input_jinja:
            action: core.local
            input:
                cmd: "echo '{{ tasks(execution().id) }}'"

        # this breaks
        # tasks_in_input_yaql:
        #     action: core.local
        #     input:
        #         cmd: "echo '<% tasks(execution().id) %>'"
                
        # this breaks
        # tasks_in_input_jinja_plain:
        #     action: core.local
        #     input:
        #         cmd: "{{ tasks(execution().id) | string }}"

        # this breaks
        # tasks_in_input_jinja_variable:
        #     action: core.local
        #     input:
        #         cmd: "echo '{{ _.published_jinja }}'"
```

## Debugging notes

I've tried several different combinations of YAQL and Jinja in the input stanza using the `tasks()` function but all fail in the same manner. My attempts are show as commented out tasks in the workflow YAML.

If you notice i've also tried publishing the variable at a previous task, then utilizing the published variable later in `tasks_in_input_jinja_variable` and this also fails in the exact same way. It's very weird, because if you just run the first task with the `publish:` it works just fine. It's only when you start working in the `input:` section that it begins to break.

**Comment by nmaludy** [comment]
## More debugging - Graphs

I modified `render_live_params()` to look like the following:

```
def render_live_params(runner_parameters, action_parameters, params, action_context):
    '''
    Renders list of parameters. Ensures that there's no cyclic or missing dependencies. Returns a
    dict of plain rendered parameters.
    '''
    config = get_config(action_context.get('pack'), action_context.get('user'))

    G = _create_graph(action_context, config)

    [_process(G, name, value) for name, value in six.iteritems(params)]
    _process_defaults(G, [action_parameters, runner_parameters])

    # BEGIN NICKS DEBUGGING ADDITIONS
    from networkx.readwrite import json_graph
    import time

    millis = int(round(time.time() * 1000))
    graph_path = "/var/log/st2/st2_nx_link_data_{}.json".format(millis)
    data = json_graph.node_link_data(G)
    json_str = json.dumps(data, default=_graph_to_dict)
    with open(graph_path, "w") as f:
        f.write(json_str)
    # END NICKS DEBUGGING ADDITIONS

    _validate(G)

    context = _resolve_dependencies(G)
    live_params = _cast_params_from(params, context, [action_parameters, runner_parameters])

    return live_params
```

This allowed me to print out the "graphs" that were generated during the next run.

Here is the graph that failed with the "tasks" no that has no corresponding `value` or `template`.

```
{
  "directed": true,
  "graph": {
  },
  "nodes": [
    {
      "id": "config_context",
      "value": {
      }
    },
    {
      "id": "tasks"
    },
    {
      "id": "env",
      "value": null
    },
    {
      "template": "echo '[{'state_info': None, 'workflow_execution_id': u'd85aa54a-1b02-4001-8b39-3045356e3b17', 'state': 'SUCCESS', 'name': u'tasks_in_publish', 'result': {u'failed': False, u'stderr': u'', u'return_code': 0, u'succeeded': True, u'stdout': u'hello world'}, 'published': {}, 'type': u'ACTION', 'id': u'f670a124-0f4e-49e7-9fed-fb1941b86694', 'spec': {u'version': u'2.0', u'name': u'tasks_in_publish', u'on-success': [u'tasks_in_input_jinja'], u'action': u'st2.action', u'input': {u'ref': u'core.local', u'parameters': {u'cmd': u\"echo 'hello world'\"}}, u'type': u'direct', u'publish': {u'published_jinja': u'{{ tasks(execution().id) | string }}'}}}]'",
      "value": null,
      "id": "cmd"
    },
    {
      "id": "action_context",
      "value": {
        "mistral": {
          "workflow_execution_id": "d85aa54a-1b02-4001-8b39-3045356e3b17",
          "action_execution_id": "e8e9255f-8101-4cda-8233-84f8e9b1a613",
          "task_name": "tasks_in_input_jinja",
          "task_id": "fa2db7bd-f4bb-4638-9a41-8e64f4a183af",
          "task_tags": null,
          "workflow_name": "examples.mistral-tasks-error-simple",
          "callback_url": "/v2/action_executions/e8e9255f-8101-4cda-8233-84f8e9b1a613"
        },
        "user": "st2admin",
        "parent": {
          "user": "st2admin",
          "execution_id": "59ea44dfa814c03d3e3c9a9a",
          "pack": "examples"
        },
        "pack": "core"
      }
    },
    {
      "id": "st2kv",
      "value": {
        "system": {
          "KeyValueLookup": "st2kv.system"
        }
      }
    },
    {
      "id": "kwarg_op",
      "value": "--"
    },
    {
      "id": "timeout",
      "value": 60
    },
    {
      "id": "execution"
    },
    {
      "id": "sudo",
      "value": false
    },
    {
      "id": "cwd",
      "value": null
    }
  ],
  "links": [
    {
      "source": 1,
      "target": 3
    },
    {
      "source": 8,
      "target": 3
    }
  ],
  "multigraph": false
}
```

Also notice that the `execution` node has no `value:`.

And finally at the bottom there are two `links`... both of those are links from `tasks(1) -> cmd(3)` and `execution(8) -> cmd(3)` .... very interesting.

**Comment by nmaludy** [comment]
## More debugging - Trying task() function

So i wondering why this works with the `task()` function but not the `tasks()` function... turns out i can also get it to break using the `task()` function...

## Broken task()

``` yaml
version: '2.0'

examples.mistral-tasks-error-simple:
    description: "Reproduce errors when running tasks() function in a mistral workflow"
    type: direct
    input:
        - str
        - test_array:
            - abc
            - def
        
    output:
      published_jinja: "{{ _.tasks_published_jinja }}"
      #published_yaql: "{{ _.tasks_published_yaql }}"
        
    tasks:

        # this works
        tasks_in_publish:
            action: core.local
            input:
                cmd: "echo 'hello world'"
            publish:
                published_jinja: "{{ task('tasks_in_publish') }}"
            on-success:
                - tasks_in_input_jinja
                #- tasks_in_input_yaql
                #- tasks_in_input_jinja_plain
                
        # this breaks
        tasks_in_input_jinja:
            action: core.local
            input:
                cmd: "echo '{{ _.published_jinja }}'"
```

## Working task()

However if i change it to `published_jinja: "{{ task('tasks_in_publish').result }}"` somehow this fixes it and works just fine

``` yaml
version: '2.0'

examples.mistral-tasks-error-simple:
    description: "Reproduce errors when running tasks() function in a mistral workflow"
    type: direct
    input:
        - str
        
    output:
      published_jinja: "{{ _.tasks_published_jinja }}"
      #published_yaql: "{{ _.tasks_published_yaql }}"
        
    tasks:

        # this works
        tasks_in_publish:
            action: core.local
            input:
                cmd: "echo 'hello world'"
            publish:
                published_jinja: "{{ task('tasks_in_publish').result }}"
            on-success:
                - tasks_in_input_jinja
                #- tasks_in_input_yaql
                #- tasks_in_input_jinja_plain
                
        # this works (with the .result added above)
        tasks_in_input_jinja:
            action: core.local
            input:
                cmd: "echo '{{ _.published_jinja }}'"
```

**Comment by nmaludy** [comment]
So, it looks like https://github.com/StackStorm/st2/blob/master/st2common/st2common/util/param.py#L116-L117 is returning back the `task()`, `tasks()`, and `execution()` functions because it's not loaded in the Jinja environment.

**Comment by nmaludy** [comment]
## Working if we only use Mistral actions

If i restrict the workflow to just using Mistral actions `std.echo` this works just fine:

```
version: '2.0'

examples.mistral-tasks-error-simple:
    description: "Reproduce errors when running tasks() function in a mistral workflow"
    type: direct
    input:
        - str
        
    output:
      published_jinja: "{{ _.published_jinja }}"
        
    tasks:

        # this works
        tasks_in_publish:
            action: std.echo
            input:
                output: "hello world"
            publish:
                published_jinja: "{{ tasks(execution().id) }}"
            on-success:
                - tasks_in_input_jinja
                
        # this break
        tasks_in_input_jinja:
            action: std.echo
            input:
                output: "{{ _.published_jinja }}"
```
