### ISSUE TITLE
mistral workflow using with-items successfully completes but produces no 'history' 

### ISSUE THREAD

**Issue by deterrak** [StackStorm/st2#3838]
Running an example mistral workflow demo exits successfully but produces no output in the history page. Environment is version 2.5.

### Here is the example workflow.

````
---
version: '2.0'

default.simple-workflow:
    description: foo
    type: direct
    output:
        out: <% $.out2 %>

    tasks:
        task1:
            with-items: x in ["1","2"]
            action: std.echo output=<% $.x %>
            publish:
                out1: <% task(task1).result %>
            on-success:
                - task2

        task2:
            with-items: y in ["3","4"]
            action: std.echo output=<% $.y %>
            publish:
                out2: <% task(task2).result %>
````

On the history page, instead of the normal task by task output / state a dark grey row is displayed under the top-level task even though the workflow executed successfully. 

### Action output is
````
{
  "extra": {
    "state_info": null,
    "state": "SUCCESS"
  },
  "tasks": [
    {
      "state_info": null,
      "name": "task1",
      "created_at": "2017-11-08 18:45:54",
      "updated_at": "2017-11-08 18:45:55",
      "id": "7b3ce605-478e-46fb-a5a7-b4db6af89b67",
      "workflow_execution_id": "7f61e6f7-915e-429d-aab4-bcc5a4fd4d12",
      "state": "SUCCESS",
      "result": [
        "1",
        "2"
      ],
      "published": {
        "out1": [
          "1",
          "2"
        ]
      },
      "input": null,
      "workflow_name": "default.simple-workflow"
    },
    {
      "state_info": null,
      "name": "task2",
      "created_at": "2017-11-08 18:45:55",
      "updated_at": "2017-11-08 18:45:55",
      "id": "29567532-2878-43a8-ab27-e3bade9f961f",
      "workflow_execution_id": "7f61e6f7-915e-429d-aab4-bcc5a4fd4d12",
      "state": "SUCCESS",
      "result": [
        "3",
        "4"
      ],
      "published": {
        "out2": [
          "3",
          "4"
        ]
      },
      "input": null,
      "workflow_name": "default.simple-workflow"
    }
  ],
  "out": [
    "3",
    "4"
  ]
}
````

### Here is the 'code' view of the workflow from the history page
````
{
  "status": "succeeded",
  "start_timestamp": "2017-11-08T18:45:53.071403Z",
  "log": [
    {
      "status": "requested",
      "timestamp": "2017-11-08T18:45:53.174000Z"
    },
    {
      "status": "scheduled",
      "timestamp": "2017-11-08T18:45:53.378000Z"
    },
    {
      "status": "running",
      "timestamp": "2017-11-08T18:45:53.478000Z"
    },
    {
      "status": "succeeded",
      "timestamp": "2017-11-08T18:46:00.230000Z"
    }
+ 129 more lines
{
  "status": "succeeded",
  "start_timestamp": "2017-11-08T18:45:53.071403Z",
  "log": [
    {
      "status": "requested",
      "timestamp": "2017-11-08T18:45:53.174000Z"
    },
    {
      "status": "scheduled",
      "timestamp": "2017-11-08T18:45:53.378000Z"
    },
    {
      "status": "running",
      "timestamp": "2017-11-08T18:45:53.478000Z"
    },
    {
      "status": "succeeded",
      "timestamp": "2017-11-08T18:46:00.230000Z"
    }
  ],
  "runner": {
    "runner_module": "mistral_v2",
    "uid": "runner_type:mistral-v2",
    "name": "mistral-v2",
    "enabled": true,
    "query_module": "mistral_v2",
    "runner_parameters": {
      "skip_notify": {
        "default": [],
        "type": "array",
        "description": "List of tasks to skip notifications for."
      },
      "task": {
        "type": "string",
        "description": "The name of the task to run for reverse workflow."
      },
      "context": {
        "default": {},
        "type": "object",
        "description": "Additional workflow inputs."
      },
      "workflow": {
        "type": "string",
        "description": "The name of the workflow to run if the entry_point is a workbook of many workflows. The name should be in the format \"<pack_name>.<action_name>.<workflow_name>\". If entry point is a workflow or a workbook with a single workflow, the runner will identify the workflow automatically."
      }
    },
    "id": "5a022605b2ee325a31cbf84f",
    "description": "A runner for executing mistral v2 workflow."
  },
  "elapsed_seconds": 7.142046,
  "web_url": "https://EWC-v2.5/#/history/5a0350e1b2ee32071a79067e/general",
  "result": {
    "extra": {
      "state_info": null,
      "state": "SUCCESS"
    },
    "tasks": [
      {
        "state_info": null,
        "name": "task1",
        "created_at": "2017-11-08 18:45:54",
        "updated_at": "2017-11-08 18:45:55",
        "id": "7b3ce605-478e-46fb-a5a7-b4db6af89b67",
        "workflow_execution_id": "7f61e6f7-915e-429d-aab4-bcc5a4fd4d12",
        "state": "SUCCESS",
        "result": [
          "1",
          "2"
        ],
        "published": {
          "out1": [
            "1",
            "2"
          ]
        },
        "input": null,
        "workflow_name": "default.simple-workflow"
      },
      {
        "state_info": null,
        "name": "task2",
        "created_at": "2017-11-08 18:45:55",
        "updated_at": "2017-11-08 18:45:55",
        "id": "29567532-2878-43a8-ab27-e3bade9f961f",
        "workflow_execution_id": "7f61e6f7-915e-429d-aab4-bcc5a4fd4d12",
        "state": "SUCCESS",
        "result": [
          "3",
          "4"
        ],
        "published": {
          "out2": [
            "3",
            "4"
          ]
        },
        "input": null,
        "workflow_name": "default.simple-workflow"
      }
    ],
    "out": [
      "3",
      "4"
    ]
  },
  "context": {
    "rbac": {
      "user": "st2admin",
      "roles": [
        "system_admin"
      ]
    },
    "pack": "default",
    "user": "st2admin",
    "mistral": {
      "workflow_name": "default.simple-workflow",
      "execution_id": "7f61e6f7-915e-429d-aab4-bcc5a4fd4d12"
    }
  },
  "action": {
    "runner_type": "mistral-v2",
    "name": "simple-workflow",
    "parameters": {},
    "tags": [],
    "enabled": true,
    "entry_point": "workflows/simple-workflow.yaml",
    "notify": {},
    "uid": "action:default:simple-workflow",
    "pack": "default",
    "ref": "default.simple-workflow",
    "id": "5a0350cfb2ee32071a79067c",
    "description": "simple workflow"
  },
  "liveaction": {
    "runner_info": {
      "hostname": "EWC-v2",
      "pid": 1154
    },
    "parameters": {},
    "action_is_workflow": true,
    "callback": {},
    "action": "default.simple-workflow",
    "id": "5a0350e1b2ee32071a79067d"
  },
  "id": "5a0350e1b2ee32071a79067e",
  "end_timestamp": "2017-11-08T18:46:00.213449Z",
  "execution_time": 8
}
````

**Comment by Mierdin** [comment]
`std.echo` is a Mistral action, not a StackStorm action. Since these executions are performed outside of StackStorm, the best StackStorm can do is give you the output - but it cannot show the individual tasks, since from StackStorm's perspective, they don't exist. It's like the workflow just ran without tasks (even though this isn't true on the Mistral side).

See that the output on the CLI is just as confused (no tasks at all):

```
vagrant@st2vagrant:~$ st2 run testpack.simple-workflow
....
id: 5a036662c4da5f3441be0089
action.ref: testpack.simple-workflow
parameters: None
status: failed
result_task: task2
result: - '3'
- '4'
start_timestamp: 2017-11-08T20:17:38.639523Z
end_timestamp: 2017-11-08T20:17:44.965581Z
result: - '3'
- '4'
```

A better option would be to use StackStorm action refs so they execute within StackStorm's actionrunner. Here's a changed workflow that should be close to what you want:

# StackStorm-Friendly Workflow

```
---
version: '2.0'

testpack.simple-workflow:
    description: foo
    type: direct
    output:
        out: <% $.out2 %>

    tasks:
        task1:
            with-items: x in ["1","2"]
            action: core.local cmd="echo <% $.x %>"
            publish:
                out1: <% task(task1).result %>
            on-success:
                - task2

        task2:
            with-items: y in ["3","4"]
            action: core.local cmd="echo <% $.y %>"
            publish:
                out2: <% task(task2).result %>
```

# Result with Tasks

```
vagrant@st2vagrant:~$ st2 run testpack.simple-workflow
...
id: 5a0367b1c4da5f3441be00ad
action.ref: testpack.simple-workflow
parameters: None
status: succeeded
result_task: task2
result: - failed: false
  return_code: 0
  stderr: ''
  stdout: 3
  succeeded: true
- failed: false
  return_code: 0
  stderr: ''
  stdout: 4
  succeeded: true
start_timestamp: 2017-11-08T20:23:13.161102Z
end_timestamp: 2017-11-08T20:23:19.177352Z
+--------------------------+------------------------+-------+------------+-------------------------------+
| id                       | status                 | task  | action     | start_timestamp               |
+--------------------------+------------------------+-------+------------+-------------------------------+
| 5a0367b1c4da5f3441be00b0 | succeeded (0s elapsed) | task1 | core.local | Wed, 08 Nov 2017 20:23:13 UTC |
| 5a0367b1c4da5f3441be00b2 | succeeded (0s elapsed) | task1 | core.local | Wed, 08 Nov 2017 20:23:13 UTC |
| 5a0367b3c4da5f3441be00b4 | succeeded (0s elapsed) | task2 | core.local | Wed, 08 Nov 2017 20:23:15 UTC |
| 5a0367b3c4da5f3441be00b6 | succeeded (0s elapsed) | task2 | core.local | Wed, 08 Nov 2017 20:23:15 UTC |
+--------------------------+------------------------+-------+------------+-------------------------------+
```

This should also work in the WebUI as a result.
