### ISSUE TITLE
Inconsistent newlines for execution output

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3855]
I thought this was documented in another issue but I can't find it, so recording here. Sorry if duplicate.

For the last few months I've noticed that some executions respect newlines, and others do not (and in turn, record the literal `\n` in its place).

For long outputs like in our CI where the st2 bootstrap script is used, this makes troubleshooting **awful**.

It doesn't even seem to be specific to certain runners. For instance, both actions below use `python-script`, yet the `stderr` for the first execution renders newline characters, and the second does not.

```
vagrant@st2vagrant:~$ st2 run packs.setup_virtualenv packs=napalm
......................
id: 5a07a4f0c4da5f054cf2fe22
status: succeeded
parameters:
  packs:
  - napalm
result:
  exit_code: 0
  result: 'Successfuly set up virtualenv for the following packs: napalm'
  stderr: 'st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "napalm" (/opt/stackstorm/packs/napalm)

    st2.actions.python.SetupVirtualEnvironmentAction: INFO     Virtualenv path "/opt/stackstorm/virtualenvs/napalm" doesn''t exist

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "napalm" in "/opt/stackstorm/virtualenvs/napalm"

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/napalm" using Python binary "/opt/stackstorm/st2/bin/python"

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy /opt/stackstorm/virtualenvs/napalm" to create virtualenv.

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement six>=1.9.0,<2.0 with command /opt/stackstorm/virtualenvs/napalm/bin/pip install six>=1.9.0,<2.0.

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing pack specific requirements from "/opt/stackstorm/packs/napalm/requirements.txt"

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirements from file /opt/stackstorm/packs/napalm/requirements.txt with command /opt/stackstorm/virtualenvs/napalm/bin/pip install -U -r /opt/stackstorm/packs/napalm/requirements.txt.

    st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Virtualenv for pack "napalm" successfully created in "/opt/stackstorm/virtualenvs/napalm"

    '
  stdout: ''
vagrant@st2vagrant:~$ st2 run napalm.ping hostname=192.168.16.25 destination=192.168.16.25
.
id: 5a07a546c4da5f054cf2fe25
status: failed
parameters:
  destination: 192.168.16.25
  hostname: 192.168.16.25
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 259, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 155, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/napalm/actions/ping.py\", line 10, in run\n    with self.get_driver(**std_kwargs) as device:\n  File \"/opt/stackstorm/packs/napalm/actions/lib/action.py\", line 37, in get_driver\n    found_device = self.find_device_from_config(hostname, driver, credentials, port)\n  File \"/opt/stackstorm/packs/napalm/actions/lib/action.py\", line 88, in find_device_from_config\n    raise Exception(message)\nException: Configuration Error: Please provide a pack config and ensure it's loaded  with `st2ctl reload --register-configs`\n"
  stdout: ''
```

I don't recall this being as bad of a problem as it is now, and I'd like to spend some time understanding how/when these newline characters are interpreted and give it some TLC to ensure this behavior is much more predictable than it is now.

Any effort against this issue should consider all action runners, and all potential output fields.
