### ISSUE TITLE
st2 2.5.0 debug output not showing task inputs for workflows

### ISSUE THREAD

**Issue by AndyMoore** [StackStorm/st2#3866]
when you run a workflow in debug (-dj) task inputs always show as null in the output. inputs are still passed to tasks, but in more complicated workflows it makes it harder to debug issues

example:

wftest.meta.yaml

```
---
  name: "wftest"
  runner_type: "mistral-v2"
  enabled: true
  entry_point: "workflows/wftest.yaml"
  pack: "bitesize"
  parameters:
    p1:
      type: "string"
```

workflows/wftest.yaml 
```
version: '2.0'
bitesize.wftest:
  description: test a wf
  input:
    - p1
  type: direct
  tasks:
    t1:
      action: core.local
      input:
        cmd: "echo <% $.p1 %>"
```

output:

```st2 run bitesize.wftest p1=aaa -dj 

{
    "action": {
        "ref": "bitesize.wftest"
    }, 
    "context": {
        "user": "testu"
    }, 
    "end_timestamp": "2017-11-16T13:03:33.588165Z", 
    "id": "5a0d8c9f38d0d73abf7c3906", 
    "parameters": {
        "p1": "aaa"
    }, 
    "result": {
        "extra": {
            "state": "SUCCESS", 
            "state_info": null
        }, 
        "tasks": [
            {
                "created_at": "2017-11-16 13:03:28", 
                "id": "46dce651-f2e0-4d81-bb5a-b829b0dd0421", 
                "input": null, 
                "name": "t1", 
                "published": {}, 
                "result": {
                    "failed": false, 
                    "return_code": 0, 
                    "stderr": "", 
                    "stdout": "aaa", 
                    "succeeded": true
                }, 
                "state": "SUCCESS", 
                "state_info": null, 
                "updated_at": "2017-11-16 13:03:28", 
                "workflow_execution_id": "cb4fd562-606b-41d7-85e2-92b7c7cccc0d", 
                "workflow_name": "bitesize.wftest"
            }
        ]
    }, 
    "start_timestamp": "2017-11-16T13:03:27.732612Z", 
    "status": "succeeded"
}
```
