### ISSUE TITLE
vars won't resolve in action chain notify section

### ISSUE THREAD

**Issue by panasaan** [StackStorm/st2#3880]
This is an example:

```yaml
 vars:
     myvar: "var_content"
     -
     name: "action"
     ref: "core.local"
     parameters:
         cmd: >
                 echo "Echoing a var: {{my_var}}" -> THIS WORKS
     notify:
         on-success:
             routes:
                 - slack
             message: "Echoing a var: {{my_var}}" -> THIS NOT WORKS
```
