### ISSUE TITLE
--inherit-env for packed actions

### ISSUE THREAD

**Issue by kfirstri** [StackStorm/st2#3888]
Hello,

I'm writing a new action that runs a bash file (runner type - local-shell-script)
my YAML file -
```yaml
---
name: create_ns
runner_type: local-shell-script
description: Create a new namespace
enabled: true
entry_point: 'shell/create_ns.sh'
parameters:
  name: 
    type: string
    position: 1
  cluster: 
    type: string
    default: 'dev'
    position: 2
  sudo:
    default: true
    immutable: true
  env:
    default:
      KUBECONFIG: "/path/to/file"
    immutable: true
```
In the stackstorm container i have a KUBECONFIG env variable, so what i'm really looking for is a way to pass environmant variable inside the execution.

i've seen in the documentation that --inherit-env passes the variables inside the execution, which is good, and if i use the CLI (`st2 run pack.create_ns -e) it works great! what i don't understand is how to specify it **inside** the YAML configuration?

Other methods i thought of - 
 - Passing the environment as a parameter - won't work because i can't use {{ env }} (yaml files are static)
 - Maybe chaining it somehow? not sure exactly with what..
