### ISSUE TITLE
Spawning multiple events via action

### ISSUE THREAD

**Issue by guptasakshi01** [StackStorm/st2#3930]
Hi,

I want  to trigger multiple events as new threads in stackstorm via an action. 
Example: workflow1 will trigger workflow2 and workflow3 parallely, i.e. asynchronously.

**Comment by nmaludy** [comment]
I had a similar request in Slack this morning.

## Use Case

There is a action/workflow that is executed and based on some logic may cause an "event" (trigger) to occur. Depending on the trigger that is emitted another workflow may match it via a rule and then execute.

## Outcome

This allows for "de-coupling" of actions/workflows. It has the benefit in something like a public pack where we may want others to subscribe to some sort of event that our pack is generating. In this case the public pack cannot know about or invoke an action in a private pack. If the public pack was able to emit a trigger, then the private pack could have a rule that matches the trigger and invoke its custom action.

## Mock up

```yaml
      emit_trigger:
        action: core.trigger
        input:
          trigger: "custom.event.vm_created"
          payload: "{{ _.payload }}"
```
