### ISSUE TITLE
RBAC:resource_uid format to execute all actions

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [StackStorm/st2#4024]
Hello,

I wanted to apply a particular permission (for eg: action_execute) on all actions.
So how do I provide the resource_uid in permission grants(yaml file in /opt/stackstorm/rbac/roles)? I am expecting something like this (resource_uid: "action:*:*") so that it provides permission for all.

Thanks

**Comment by LindsayHill** [comment]
I don't believe there is a way to define a permission that applies to all resources. I think it needs to be done on a per-action or per-pack basis.

It is _possible_ that you may be able to do this:
```yaml
---
    name: "actions"
    description: "Role which grants permission to execute all actions"
    enabled: true
    permission_grants:
        -
            # Grant action_execute on all resources
            permission_types:
               - "action_execute"
```

I haven't tested this though.

**Comment by LindsayHill** [comment]
So yes, the way to do this is something like the last section in the example role definition here: https://docs.stackstorm.com/rbac.html#defining-roles-and-permission-grants

Don't specify any resource, just do this:

```yaml
---
    name: "sample"
    description: "Role which allows executing any action"
    enabled: true
    permission_grants:
        -
            permission_types:
               - "action_execute"
```
