### ISSUE TITLE
st2api being bogged down by MongoEngine

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4030]
Working recently with a bunch of large workflows and seeing the `st2api` service using 100% CPU.

I turned on a wsgi profiler (https://medium.com/@maxmaxmaxmax/measuring-performance-of-python-based-apps-using-gunicorn-and-cprofile-ee4027b2be41) and am seeing profile stacktraces like so:

```yamll
2018-03-08 19:59:43,333 100167760 ERROR wsgi_profiler [-] 
[4525] [INFO] [POST] URI /v1/actionexecutions
2018-03-08 19:59:43,333 100167760 ERROR wsgi_profiler [-] [4525] [INFO]          21554881 function calls (20361663 primitive calls) in 60.828 seconds

   Ordered by: internal time, cumulative time
   List reduced from 1272 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  3888837    4.593    0.000    4.651    0.000 {isinstance}
    45770    3.272    0.000   25.510    0.001 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/document.py:36(__init__)
   374817    2.745    0.000    8.031    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/fields.py:123(__set__)
874662/830081    2.720    0.000   12.477    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/document.py:144(__setattr__)
53587/1799    2.446    0.000   11.942    0.007 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/dereference.py:163(_attach_objects)
1452191/1255348    2.137    0.000    6.932    0.000 {getattr}
  1052620    2.072    0.000    4.654    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:382(__getitem__)
   874913    1.789    0.000    2.500    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/common.py:5(_import_class)
879819/506309    1.747    0.000   12.198    0.000 {setattr}
   640806    1.711    0.000    5.291    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:396(get)
  1901626    1.603    0.000    1.603    0.000 {method 'get' of 'dict' objects}
   466160    1.531    0.000    4.158    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:410(iteritems)
45637/1056    1.477    0.000   48.524    0.046 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/document.py:672(_from_son)
53587/1799    1.432    0.000    4.081    0.002 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/dereference.py:80(_find_references)
     59/0    1.337    0.023    0.000          /opt/stackstorm/st2/lib/python2.7/site-packages/pymongo/auth.py:482(authenticate)
   187230    1.191    0.000    1.191    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:454(__getattr__)
    45770    1.177    0.000    1.417    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:435(create)
155175/1491    1.032    0.000   30.454    0.020 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/fields.py:299(to_python)
   878632    1.032    0.000    1.032    0.000 {hasattr}
   421229    0.874    0.000    0.874    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:463(__setattr__)
   421229    0.863    0.000    2.633    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:389(__setitem__)
   281293    0.810    0.000    4.409    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/fields.py:113(__get__)
    88774    0.808    0.000    1.567    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:113(__getitem__)
    55696    0.711    0.000    4.900    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:426(__len__)
   222834    0.693    0.000    0.693    0.000 {method 'replace' of 'datetime.datetime' objects}
   466160    0.668    0.000    1.014    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/datastructures.py:424(<genexpr>)
    47312    0.647    0.000   18.743    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/base/fields.py:252(__get__)
114474/82442    0.637    0.000    1.464    0.000 /usr/lib64/python2.7/copy.py:145(deepcopy)
    44602    0.622    0.000    1.341    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/st2common/fields.py:67(_datetime_to_microseconds_since_epoch)
    89078    0.610    0.000    1.621    0.000 /opt/stackstorm/st2/lib/python2.7/site-packages/st2common/fields.py:52(_microseconds_since_epoch_to_datetime)
```

And general times reaching 100+ seconds as i let it go for longer and longer

```
[6397] [INFO] [POST] URI /v1/actionexecutions Total time: 100.877137899
```

This is reproduced using the following action workflow:

```yaml
---
description: Run a local linux command
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-nested.yaml
name: mistral-nested
pack: examples
parameters:
  cmd:
    required: true
    type: string
    default: "ls"
  timeout:
    type: integer
    default: 60
```

```yaml
version: '2.0'

examples.mistral-nested:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - cmd
        - timeout
        - task_names:
            - 'snmp'
            
    output:
      stdout: "{{ _.stdout }}"
        
    tasks:
      main:
        action: core.local
        input:
          cmd: "{{ _.cmd }}"
        publish:
          stdout: "main {{ task('main').result.stdout }}"
        on-complete:
          - nested_workflow_1

      nested_workflow_1:
        with-items: "x in {{ range(0, 250, 1) }}"
        action: examples.mistral-jinja-workbook-complex
        input:
          vm_name: "{{ _.cmd }}_{{ _.x }}"
        publish:
          stdout: "{{ task('nested_workflow_1').result }}"
```

**Comment by nmaludy** [comment]
Maybe this has something to do with it?  https://stackoverflow.com/questions/35257305/mongoengine-is-very-slow-on-large-documents-comapred-to-native-pymongo-usage

I'm sure the parent workflow is very large with all of the results all in one big workflow object.

**Comment by bigmstone** [comment]
And here I was wondering what I was going to do in the morning. ;)

**Comment by jbrownsc** [comment]
I also am hitting this issue with 100s of items in a list.  Let me know if there is anything I can provide to help troubleshoot.  @nmaludy was kind enough to share his strategy for dealing with this, but would love to get a bump on getting a fix into st2.

**Comment by Kami** [comment]
Did you encounter this issue when hitting that API endpoint using WebUI (or some other method)?

https://github.com/StackStorm/st2/pull/4300 should help with WebUI performance a lot once that PR is merged and one WebUI starts utilizing it (should be in the next release).

Besides that, I hope to have a look at this exact issue when I get a chance (likely late next week).

**Comment by nmaludy** [comment]
@Kami i hit this issue by running a Mistral workflow with a _lot_ of `with-items`

**Comment by jbrownsc** [comment]
This isn't so much a "UI rendering slow" issue and more of a "My workflow slows down as the number of executions increases" issue.  We use with-items to handle deployment, so with 5-10 items running subworkflows, we have great performance, with 50 items, we have bad performance :-)

**Comment by jbrownsc** [comment]
Here is a good quantification of the issue.  Notice in a 50 item, with-items execution, how each iteration takes longer and longer.   If you go to 100, 200, etc... As @nmaludy said, the st2api calls can be seen increasing in latency in the logs.  The larger the task size (output specifically, the longer it takes) in the workflow

```
st2 execution get 5b8442b6cd0fbf5236e3ad00 | grep nested_workflow_1
result_task: nested_workflow_1
| + 5b8442b7cd0fbf5236e3ad03  | succeeded (12s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:28:07 UTC |
| + 5b8442c4cd0fbf5236e3ad17  | succeeded (12s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:28:20 UTC |
| + 5b8442d2cd0fbf5236e3ad2b  | succeeded (12s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:28:34 UTC |
| + 5b8442dfcd0fbf5236e3ad3f  | succeeded (12s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:28:47 UTC |
| + 5b8442eccd0fbf5236e3ad53  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:29:00 UTC |
| + 5b8442fbcd0fbf5236e3ad67  | succeeded (12s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:29:15 UTC |
| + 5b844308cd0fbf5236e3ad7b  | succeeded (13s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:29:28 UTC |
| + 5b844316cd0fbf5236e3ad8f  | succeeded (13s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:29:42 UTC |
| + 5b844325cd0fbf5236e3ada3  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:29:56 UTC |
| + 5b844334cd0fbf5236e3adb7  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:30:12 UTC |
| + 5b844344cd0fbf5236e3adcb  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:30:28 UTC |
| + 5b844353cd0fbf5236e3addf  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:30:43 UTC |
| + 5b844363cd0fbf5236e3adf3  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:30:59 UTC |
| + 5b844373cd0fbf5236e3ae07  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:31:14 UTC |
| + 5b844382cd0fbf5236e3ae1b  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:31:30 UTC |
| + 5b844391cd0fbf5236e3ae2f  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:31:45 UTC |
| + 5b8443a1cd0fbf5236e3ae43  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:32:01 UTC |
| + 5b8443b0cd0fbf5236e3ae57  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:32:16 UTC |
| + 5b8443c0cd0fbf5236e3ae6b  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:32:32 UTC |
| + 5b8443cfcd0fbf5236e3ae7f  | succeeded (16s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:32:47 UTC |
| + 5b8443e0cd0fbf5236e3ae93  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:33:04 UTC |
| + 5b8443f0cd0fbf5236e3aea7  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:33:20 UTC |
| + 5b844400cd0fbf5236e3aebb  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:33:36 UTC |
| + 5b84440fcd0fbf5236e3aecf  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:33:51 UTC |
| + 5b84441fcd0fbf5236e3aee3  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:34:06 UTC |
| + 5b84442ecd0fbf5236e3aef7  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:34:22 UTC |
| + 5b84443fcd0fbf5236e3af0b  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:34:38 UTC |
| + 5b84444ecd0fbf5236e3af1f  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:34:54 UTC |
| + 5b84445dcd0fbf5236e3af33  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:35:09 UTC |
| + 5b84446dcd0fbf5236e3af47  | succeeded (14s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:35:25 UTC |
| + 5b84447dcd0fbf5236e3af5b  | succeeded (16s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:35:40 UTC |
| + 5b84448dcd0fbf5236e3af6f  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:35:57 UTC |
| + 5b84449dcd0fbf5236e3af83  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:36:13 UTC |
| + 5b8444aecd0fbf5236e3af97  | succeeded (19s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:36:29 UTC |
| + 5b8444c1cd0fbf5236e3afab  | succeeded (16s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:36:49 UTC |
| + 5b8444d2cd0fbf5236e3afbf  | succeeded (16s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:37:06 UTC |
| + 5b8444e4cd0fbf5236e3afd3  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:37:23 UTC |
| + 5b8444f5cd0fbf5236e3afe7  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:37:41 UTC |
| + 5b844507cd0fbf5236e3affb  | succeeded (15s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:37:59 UTC |
| + 5b844518cd0fbf5236e3b00f  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:38:15 UTC |
| + 5b844529cd0fbf5236e3b023  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:38:33 UTC |
| + 5b84453bcd0fbf5236e3b037  | succeeded (16s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:38:51 UTC |
| + 5b84454ccd0fbf5236e3b04b  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:39:08 UTC |
| + 5b84455ecd0fbf5236e3b05f  | succeeded (16s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:39:26 UTC |
| + 5b844570cd0fbf5236e3b073  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:39:43 UTC |
| + 5b844581cd0fbf5236e3b087  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:40:01 UTC |
| + 5b844593cd0fbf5236e3b09b  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:40:19 UTC |
| + 5b8445a6cd0fbf5236e3b0af  | succeeded (18s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:40:37 UTC |
| + 5b8445b8cd0fbf5236e3b0c3  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:40:56 UTC |
| + 5b8445cacd0fbf5236e3b0d7  | succeeded (17s elapsed) | nested_workflow_1 | examples.mistral-jinja-      | Mon, 27 Aug 2018 18:41:14 UTC |
root@8ade7d214c04:/tmp/st2/contrib/examples/actions/workflows#
```

**Comment by Kami** [comment]
I'll try to reproduce this issue today.

The weird thing is that POST operation takes a long time - "[6397] [INFO] [POST] URI /v1/actionexecutions Total time: 100.877137899".

POST aka schedule action execution operation is quite simple so there is no reason it should take that long (it inserts a couple of objects into the database and publishes a message on the messages bus).

It's likely that some other API operation (e.g. GET) is hogging it down, or that there is some weird contention going on on the message bus or similar.

**Comment by Kami** [comment]
After some digging in - I wonder if the issue lies somewhere else and not in the st2api.

If I run the workflow above which uses Mistral to run a lot of actions in a short time-frame, I noticed large CPU utilization by mistral-server and partially, st2rulesengine.

st2rulesengine utilization is expected, because each execution results in at least one trigger instance.

So could this issue simple be due to resource exhaustion caused by mistral-server hogging most of the available CPU?

**Comment by Kami** [comment]
@nmaludy @jbrownsc 

I tried to replicate this issue on a single server setup.

After some more instrumentation and digging in, I noticed the same behavior as reported above.

When scheduling a lot of executions in a short time-frame through Mistral workflow, mistral-server starts hogging a lot of CPU and as such, everything else (including st2api) slows down due to the lack of resources.

10 - 20 tasks work relatively fine, but as soon as I move above 30 or so, things start to get very slow (and I noticed very high server CPU utilization aka server basically being bogged down). Things gets even worse if I change with-item action from core.local to some Mistral workflow action because it causes additional load on Mistral.

@nmaludy Are you running all of the StackStorm components on a single server? 

In short - I don't think there is any quick or easy code change we can do - the root cause seems to be related to inefficiencies in Mistral and there is nothing we can do atm, besides advising users to dedicate more resources to Mistral and other StackStorm components (ideally running StackStorm services across multiple correctly sized servers).

@m4dcoder See above.

One of our "benchmarks" for Orquesta should also be orquesta workflow with a lot of `with-items` operations and verifying it has good / reasonable performance.

**Comment by m4dcoder** [comment]
I don't think this is with-items only.  This seems like a known issue with the scheduler in mistral.  If you are executing a lot of concurrent workflows thru mistral, mistral will try to schedule all the workflows and tasks at once. As tasks are completed, it will schedule the next tasks immediately. Soon, there're a lot of tasks waiting to be executed and each workflow will take longer and longer to complete because there's not enough st2 action runners to execute them. At this point in the lifecycle for mistral, since it's going to be deprecated soon, we don't intend to put a lot of time into fixing the scheduler. However, @Kami we have a line item on our roadmap to address this in orquesta, our new workflow engine.

The workaround on mistral here is to define a concurrency policy in st2 @ https://docs.stackstorm.com/reference/policies.html#concurrency for the workflow being executed by the with-items task.  Also, please note that if you average the completion time of the workflow execution in the with-items, the average time to completion is more or less the same.  The same amount of work (or tasks) get completed over time as a function of the number of system resources and st2 action runners.

**Comment by jbrownsc** [comment]
@m4dcoder I have tested this with a concurrency policy, and the same issues exists.  I'm OK with saying this is a won't fix for Mistral, but the core issue of st2api being slow seems like it will exist with Orquestra too, right?  

@Kami with regards to the performance in st2api, the POST calls to st2api should not be taking 3-5 seconds correct?  
{noformat}
2018-09-04 19:18:40,894 140660106998480 INFO logging [-] 08eb4db0-523f-4d10-a2f7-ee6c6ffe6e66 - 201 3988 4573.698ms (content_length=3988,request_id='08eb4db0-523f-4d10-a2f7-ee6c6ffe6e66',runtime=4573.698,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:43,374 140660124260944 INFO logging [-] 7a137ae4-47ee-44a9-b64e-f0c7cc12dc1e - 201 3988 4626.373ms (content_length=3988,request_id='7a137ae4-47ee-44a9-b64e-f0c7cc12dc1e',runtime=4626.373,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:44,462 140660107001360 INFO logging [-] 7a121281-20a5-4071-9440-6e9e6eda5d19 - 201 3988 6002.316ms (content_length=3988,request_id='7a121281-20a5-4071-9440-6e9e6eda5d19',runtime=6002.316,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:44,491 140660106999760 INFO logging [-] 10c27e29-7ea8-4279-b02f-ef933a6883ef - 201 3988 6562.452ms (content_length=3988,request_id='10c27e29-7ea8-4279-b02f-ef933a6883ef',runtime=6562.452,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:44,634 140660124261104 INFO logging [-] 444e88f0-8b5e-474f-a5a2-cac5961689ec - 201 3988 5301.957ms (content_length=3988,request_id='444e88f0-8b5e-474f-a5a2-cac5961689ec',runtime=5301.957,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:44,720 140660106998480 INFO logging [-] 527f6af9-9bed-450a-ad8e-f8009376fb68 - 201 3988 3363.479ms (content_length=3988,request_id='527f6af9-9bed-450a-ad8e-f8009376fb68',runtime=3363.479,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:48,806 140660107001040 INFO logging [-] 789239ac-277f-47ab-87fb-60289625e112 - 201 3988 4801.581ms (content_length=3988,request_id='789239ac-277f-47ab-87fb-60289625e112',runtime=4801.581,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:49,820 140660106999920 INFO logging [-] 654f3164-5860-4406-932b-d659edd18fba - 201 3988 5800.771ms (content_length=3988,request_id='654f3164-5860-4406-932b-d659edd18fba',runtime=5800.771,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:49,855 140660124260944 INFO logging [-] f4e36f80-3762-4bf3-8363-1ea9e08f5e8f - 201 3988 5836.541ms (content_length=3988,request_id='f4e36f80-3762-4bf3-8363-1ea9e08f5e8f',runtime=5836.541,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:49,999 140660100791344 INFO logging [-] 12a4ff02-3a55-471b-988e-98bf72b56ef8 - 201 3988 4796.937ms (content_length=3988,request_id='12a4ff02-3a55-471b-988e-98bf72b56ef8',runtime=4796.937,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:50,028 140660100791664 INFO logging [-] 5e0d0812-7911-4b77-938d-dec01df0a7f7 - 201 3988 4824.118ms (content_length=3988,request_id='5e0d0812-7911-4b77-938d-dec01df0a7f7',runtime=4824.118,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:53,794 140660106998000 INFO logging [-] be911c6a-e888-4a8f-95e5-53146d983ee6 - 201 3988 3271.721ms (content_length=3988,request_id='be911c6a-e888-4a8f-95e5-53146d983ee6',runtime=3271.721,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:54,913 140660100788624 INFO logging [-] 9258e4bc-d473-42c4-b637-90c94ceb104e - 201 3988 5142.16ms (content_length=3988,request_id='9258e4bc-d473-42c4-b637-90c94ceb104e',runtime=5142.16,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:55,988 140660100791504 INFO logging [-] bdc16a90-3dc6-4719-a930-5bc260d72337 - 201 3988 6218.387ms (content_length=3988,request_id='bdc16a90-3dc6-4719-a930-5bc260d72337',runtime=6218.387,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2018-09-04 19:18:56,035 140660107000240 INFO logging [-] 9785f5fb-493d-44d6-910b-12c6aeaa0e4c - 201 3988 5516.225ms (content_length=3988,request_id='9785f5fb-493d-44d6-910b-12c6aeaa0e4c',runtime=5516.225,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
{noformat}

**Comment by jbrownsc** [comment]
Here is the workflow I'm testing with

with-items-test.yaml
```
---
name: "with-items-test"
description: "For testing things in Mistral"
runner_type: mistral-v2
entry_point: workflows/with-items-test.yaml
enabled: true
parameters:
  workflow:
    default: voltron.with-items-test.main
```

workflows/with-items-test.yaml
```
version: '2.0'
name: 'voltron.with-items-test'
description: Noop

workflows:
  main:
    type: direct
    tasks:
      with_items_test:
        with-items: "blah in {{ range(0,250) }}"
        concurrency: 5
        workflow: another_workflow

  another_workflow:
    type: direct
    tasks:
      test_1:
        action: core.local
        input:
          cmd: echo test_1
        on-success:
          - test_2

      test_2:
        action: core.local
        input:
          cmd: echo test_2
        on-success:
          - test_3

      test_3:
        action: core.local
        input:
          cmd: echo test_3
        on-success:
          - test_4

      test_4:
        action: core.local
        input:
          cmd: echo test_4
        on-success:
          - test_5

      test_5:
        action: core.local
        input:
          cmd: echo test_5
```

**Comment by m4dcoder** [comment]
@jbrownsc we don't support concurrency policies on inline subworkflow (i.e. subworkflow in a mistral workbook).  Try to make `another_workflow` into another st2 action.  Then write a concurrency policy on `another_workflow` that limits 5 executions at a time as a baseline.

**Comment by jbrownsc** [comment]
Here is the new workflow.

with-items-test.yaml
```
---
name: "with-items-test"
description: "For testing things in Mistral"
runner_type: mistral-v2
entry_point: workflows/with-items-test.yaml
enabled: true
parameters:
  workflow:
    default: voltron.with-items-test.main
```

with-items-test-subworkflow.yaml
```
---
name: "with-items-test-subworkflow"
description: "For testing things in Mistral"
runner_type: mistral-v2
entry_point: workflows/with-items-test-subworkflow.yaml
enabled: true
parameters:
  workflow:
    default: voltron.with-items-test-subworkflow.main
```

workflows/with-items-test.yaml
```
version: '2.0'
name: 'voltron.with-items-test'
description: Noop

workflows:
  main:
    type: direct
    tasks:
      with_items_test:
        with-items: "blah in {{ range(0,250) }}"
        concurrency: 5
        action: voltron.with-items-test-subworkflow
```

workflows/with-items-test-subworkflow.yaml
```
version: '2.0'
name: 'voltron.with-items-test-subworkflow'
description: Easy-peasy subworkflow

workflows:
  main:
    type: direct
    tasks:
      test_1:
        action: core.local
        input:
          cmd: echo test_1
        on-success:
          - test_2

      test_2:
        action: core.local
        input:
          cmd: echo test_2
        on-success:
          - test_3

      test_3:
        action: core.local
        input:
          cmd: echo test_3
        on-success:
          - test_4

      test_4:
        action: core.local
        input:
          cmd: echo test_4
        on-success:
          - test_5

      test_5:
        action: core.local
        input:
          cmd: echo test_5
```
