### ISSUE TITLE
Improve error messages when Mistral task does not get required inputs

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#4031]
If a task in a Mistral workflow has required inputs, but those inputs are not provided, the error message is not particularly helpful.

Here's an example workflow:
```yaml
---
description: Run core.local via workflow
enabled: true
runner_type: mistral-v2
entry_point: workflows/cmd_workflow.yaml
name: cmd_workflow
pack: default
parameters:
  cmd:
    required: false
    type: string
  workflow:
    default: default.cmd_workflow.main
    immutable: true
    type: string
```

And here's the workflow definition:

```yaml
---
version: '2.0'

default.cmd_workflow:

  input:
    - cmd
  tasks:
    task1:
      # [374, 321]
      action: core.local
      input:
        cmd: <% $.cmd %>
```
Note that we are calling `core.local`, which has a required parameter `cmd`.

If we register this action, and run it with a `cmd:` parameter, it works as expected:

```shell
extreme@EWC:~$ st2 run default.cmd_workflow cmd=id
...
id: 5aa317c499c96b638d4188bf
action.ref: default.cmd_workflow
parameters:
  cmd: id
status: succeeded
result_task: task1
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: uid=1001(stanley) gid=1001(stanley) groups=1001(stanley)
  succeeded: true
start_timestamp: Fri, 09 Mar 2018 23:24:52 UTC
end_timestamp: Fri, 09 Mar 2018 23:24:58 UTC
+--------------------------+------------------------+-------+------------+----------------------------+
| id                       | status                 | task  | action     | start_timestamp            |
+--------------------------+------------------------+-------+------------+----------------------------+
| 5aa317c499c96b638d4188c2 | succeeded (0s elapsed) | task1 | core.local | Fri, 09 Mar 2018 23:24:52  |
|                          |                        |       |            | UTC                        |
+--------------------------+------------------------+-------+------------+----------------------------+
extreme@EWC:~$
```

However, if we run it without providing `cmd`, the error message is overly complicated:

```shell
extreme@EWC:~$ st2 run default.cmd_workflow
...
id: 5aa317f599c96b638d4188c4
action.ref: default.cmd_workflow
parameters: None
status: failed
result_task: task1
result:
  content:
    faultstring: None is not of type 'string'
  cookies: {}
  elapsed: 0.052204
  encoding: null
  headers:
    Access-Control-Allow-Credentials: 'true'
    Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token,St2-Api-Key,X-Request-ID
    Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
    Access-Control-Allow-Origin: http://127.0.0.1:3000
    Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count,X-Request-ID
    Connection: keep-alive
    Content-Length: '53'
    Content-Type: application/json
    Date: Fri, 09 Mar 2018 23:25:41 GMT
    Server: gunicorn/19.7.1
    X-Request-ID: 6e7d45ee-4d8f-4c84-ae67-558d3dc1e5c3
  history: []
  reason: Bad Request
  status: 400
  url: http://127.0.0.1:9101/v1/actionexecutions
start_timestamp: Fri, 09 Mar 2018 23:25:41 UTC
end_timestamp: Fri, 09 Mar 2018 23:25:47 UTC
result:
  content:
    faultstring: None is not of type 'string'
  cookies: {}
  elapsed: 0.052204
  encoding: null
  headers:
    Access-Control-Allow-Credentials: 'true'
    Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token,St2-Api-Key,X-Request-ID
    Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
    Access-Control-Allow-Origin: http://127.0.0.1:3000
    Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count,X-Request-ID
    Connection: keep-alive
    Content-Length: '53'
    Content-Type: application/json
    Date: Fri, 09 Mar 2018 23:25:41 GMT
    Server: gunicorn/19.7.1
    X-Request-ID: 6e7d45ee-4d8f-4c84-ae67-558d3dc1e5c3
  history: []
  reason: Bad Request
  status: 400
  url: http://127.0.0.1:9101/v1/actionexecutions
extreme@EWC:~$
```

The key line is `faultstring: None is not of type 'string'`, but that's not obvious at first, and it's unclear what it's referring to. 

In the Web UI this does not render well either. It's not obvious that it's related to calling the first task.

I'm not sure how best to improve this, but it feels like we could make this more obvious to users somehow.
