### ISSUE TITLE
ERROR while creating a rule

### ISSUE THREAD

**Issue by PyCoderAmsa** [StackStorm/st2#4032]
I am trying to create a rule through CLI and below is my YAML file (aws_rule1.yaml)
```yaml
---
name: "aws_rule1"
pack: "default"
description: ""
enabled: true
trigger:
  ref: "aws.sqs_new_message"
criteria:
  trigger.queue:
    type: "iequals"
    pattern : "testqueue"
action:
  ref: "linux.file_touch"
  parameters:
    file: "file1.txt"
```

The command that I am running is:
`st2 rule create /opt/stackstorm/packs/default/rules/aws_rule1.yaml`
and the error I get is this one:

ERROR: expected string or buffer

What's wrong?
