### ISSUE TITLE
Rendering Object from Jinja within ActionChain

### ISSUE THREAD

**Issue by hreeder** [StackStorm/st2#4096]
Attempting to do this:
```yaml
- name: "lookup_netbox_role"
    ref: "netbox.ipam_get_roles"
    publish:
      role_my_block: "{{ lookup_netbox_role.result.raw.results | selectattr('slug', 'equalto', 'platform_my_block') | list | first }}"
      role_my_other_block: "{{ lookup_netbox_role.result.raw.results | selectattr('slug', 'equalto', 'platform_my_other_block') | list | first }}"
    on-success: "assign_superblock"
```
The Jinja2 expression filters down the result of my action to something like this: `{'id': 10, 'name': 'Platform_My_Block', 'weight': 1000, 'slug': 'platform_my_block'}` however this is published as a string.

Further into my chain I attempt to access the id with `{{ role_my_block.id }}` and I'm told `"Failed to run task \"assign_superblock\". Parameter rendering failed.. Failed rendering value for action parameter \"role\" in task \"assign_superblock\" (template string={{ role_my_block.id }}): 'unicode object' has no attribute 'id'"`
