### ISSUE TITLE
Publish variables of a Mistral action in an ActionChain throws an exception

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4101]
## High Level

Initially reported on Slack by @hreeder .

When trying to `publish` a variable in an ActionChain for a Mistral action, where the `publish` statement references the current action context, the publish fails.

### Mistral Action Metadata

```yaml
---
description: Test WF
enabled: true
runner_type: mistral-v2
entry_point: workflows/testwf.yaml
name: testwf
pack: examples
```

### Mistral Workflow

```yaml
version: '2.0'

examples.testwf:
  type: direct
  output:
    data: "{{ _.stdout }}"
  tasks:
    echo_task1:
      action: core.local
      input:
        cmd: "echo task1"
      publish:
        stdout: "{{ task('echo_task1').result.stdout }}"
```

### ActionChain Action Metadata

```yaml
---
name: testac
description: test action chain
runner_type: action-chain
entry_point: chains/testac.yaml
enabled: true
pack: examples
```

### ActionChain

```yaml
---
chain:
  - name: "chain_echo"
    ref: "examples.testwf"
    publish:
      my_data: "{{ chain_echo.data }}"
```

## Error

```shell
[root@stackstorm ~]# st2 run examples.testac
.
id: 5ae9ef4ba814c0066130b634
action.ref: examples.testac
parameters: None
status: failed
error: Failed rendering value for publish parameter "my_data" in task "chain_echo" (template string={{ chain_echo.data }}): 'dict object' has no attribute 'data'
traceback:   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 119, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 295, in run
    return self._run_chain(action_parameters)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 531, in _run_chain
    chain_vars=self.chain_holder.vars)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 655, in _render_publish_vars
    raise action_exc.ParameterRenderingFailedException(msg)

start_timestamp: Wed, 02 May 2018 17:03:07 UTC
end_timestamp: Wed, 02 May 2018 17:03:08 UTC
+--------------------------+---------------------+------------+-----------------+-----------------+
| id                       | status              | task       | action          | start_timestamp |
+--------------------------+---------------------+------------+-----------------+-----------------+
| 5ae9ef4ba814c004477f5d32 | failed (0s elapsed) | chain_echo | examples.testwf | Wed, 02 May     |
|                          |                     |            |                 | 2018 17:03:07   |
|                          |                     |            |                 | UTC             |
+--------------------------+---------------------+------------+-----------------+-----------------+
```

## Workaround

If you split up the `publish` into the next task, then it works.

```yaml
---
chain:
  - name: "chain_echo"
    ref: "examples.testwf"
    on-success: "publish_data"
    
  - name: "publish_data"
    ref: "core.local"
    parameters:
      cmd: echo ''
    publish:
      my_data: "{{ chain_echo.data }}"
```

```shell
[root@stackstorm ~]# st2 run examples.testac
..
id: 5ae9efc1a814c0066130b63a
action.ref: examples.testac
parameters: None
status: succeeded
result_task: publish_data
result: 
  failed: false
  return_code: 0
  stderr: ''
  stdout: ''
  succeeded: true
start_timestamp: Wed, 02 May 2018 17:05:05 UTC
end_timestamp: Wed, 02 May 2018 17:05:08 UTC
+-----------------------------+------------------------+--------------+-----------------+-----------------+
| id                          | status                 | task         | action          | start_timestamp |
+-----------------------------+------------------------+--------------+-----------------+-----------------+
| + 5ae9efc2a814c0045b3a78b6  | succeeded (1s elapsed) | chain_echo   | examples.testwf | Wed, 02 May     |
|                             |                        |              |                 | 2018 17:05:06   |
|                             |                        |              |                 | UTC             |
|    5ae9efc2a814c0066130b63d | succeeded (0s elapsed) | echo_task1   | core.local      | Wed, 02 May     |
|                             |                        |              |                 | 2018 17:05:06   |
|                             |                        |              |                 | UTC             |
|   5ae9efc3a814c0045b3a78b8  | succeeded (0s elapsed) | publish_data | core.local      | Wed, 02 May     |
|                             |                        |              |                 | 2018 17:05:07   |
|                             |                        |              |                 | UTC             |
+-----------------------------+------------------------+--------------+-----------------+-----------------+
```
