### ISSUE TITLE
Not able to run child workflow from master workflow

### ISSUE THREAD

**Issue by nkv16786** [StackStorm/st2#4108]
I am running a child workflow `run_cmd_ssh` via another workflow `invoke_item`.

But it is not getting executed saying 

```
"Failed to run task [error=Failed to find workflow [name=run_cmd_ssh] [namespace=], wf=.invoke_item, task=execute_workflow]:
Traceback (most recent call last):
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/task_handler.py\", line 63, in run_task
    task.run()
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py\", line 158, in wrapper
    result = f(*args, **kwargs)
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py\", line 374, in run
    self._run_new()
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py\", line 158, in wrapper
    result = f(*args, **kwargs)
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py\", line 403, in _run_new
    self._schedule_actions()
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py\", line 481, in _schedule_actions
    timeout=self._get_timeout()
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py\", line 158, in wrapper
    result = f(*args, **kwargs)
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/actions.py\", line 538, in schedule
    wf_spec_name=self.wf_name
  File \"/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/utils.py\", line 91, in resolve_workflow_definition
    (wf_spec_name, namespace)
WorkflowException: Failed to find workflow [name=run_cmd_ssh] [namespace=]",
```

So i debugged and found out that in mistral database in table:-**workflow_definitions_v2** . 

```sql
SELECT name FROM workflow_definitions_v2;
               name
----------------------------------
 std.create_instance
 std.delete_instance
invoke_item
```

  `run_cmd_ssh` was not present but when i ran `run_cmd_ssh` separately it got added to the table  

```sql
SELECT name FROM workflow_definitions_v2;
               name
----------------------------------
 std.create_instance
 std.delete_instance
invoke_item
 run_cmd_ssh
```
and it started working from master workflow also.

Is this expected behavior?

Also `st2ctl reload` should add the workflows entry into the `workflow_definitions_v2 table`? or do we have any separate command to handle this?

**Comment by LindsayHill** [comment]
Thanks for the report. What does your workflow definition look like?

**Comment by LindsayHill** [comment]
I am unable to reproduce this. 

These are the steps I tried:

```shell
vagrant@st2vagrant:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
vagrant@st2vagrant:~$ st2 --version
st2 2.7.1, on Python 2.7
vagrant@st2vagrant:~$
```

I first created these workflows:

`/opt/stackstorm/packs/default/actions/parent.yaml`:

```yaml
---
description: Parent Mistral Action
enabled: true
runner_type: mistral-v2
entry_point: workflows/parent.yaml
name: parent
parameters:
  cmd:
    required: true
    type: string
  timeout:
    type: integer
    default: 60
```

`/opt/stackstorm/packs/default/actions/workflows/parent.yaml`:

```yaml
version: '2.0'

default.parent:
    description: Parent workflow that calls child
    type: direct
    input:
        - cmd
        - timeout
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: default.child cmd=<% $.cmd %> timeout=<% $.timeout %>
            publish:
                stdout: <% task(task1).result.stdout %>
                stderr: <% task(task1).result.stderr %>
```

`/opt/stackstorm/packs/default/actions/child.yaml`:

```yaml
---
description: Child Mistral Action
enabled: true
runner_type: mistral-v2
entry_point: workflows/child.yaml
name: child
parameters:
  cmd:
    required: true
    type: string
  timeout:
    type: integer
    default: 60
```

`/opt/stackstorm/packs/default/actions/workflows/child.yaml`:

```yaml
version: '2.0'

default.child:
    description: Child workflow to run arbitrary command
    type: direct
    input:
        - cmd
        - timeout
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: core.local cmd=<% $.cmd %> timeout=<% $.timeout %>
            publish:
                stdout: <% task(task1).result.stdout %>
                stderr: <% task(task1).result.stderr %>
```

I then registered all actions and workflows with `sudo st2ctl reload --register-all`. This completed without errors.

I then ran the parent workflow:

```shell
vagrant@st2vagrant:~$ st2 run default.parent cmd=id
..
id: 5ae33cdfc4da5f06a163e0cf
action.ref: default.parent
parameters:
  cmd: id
status: failed
result_task: task1
result:
  extra:
    state: SUCCESS
    state_info: null
  stdout: uid=1002(stanley) gid=1003(stanley) groups=1003(stanley)
  tasks:
  - created_at: '2018-04-27 15:08:16'
    id: e0f580a8-3608-44ad-9b3a-a68de8702957
    input: null
    name: task1
    published:
      stderr: ''
      stdout: uid=1002(stanley) gid=1003(stanley) groups=1003(stanley)
    result:
      failed: false
      return_code: 0
      stderr: ''
      stdout: uid=1002(stanley) gid=1003(stanley) groups=1003(stanley)
      succeeded: true
    state: SUCCESS
    state_info: null
    updated_at: '2018-04-27 15:08:17'
    workflow_execution_id: 2cdf0f1e-35d6-4889-a730-ac5717a9e0cd
    workflow_name: default.child
start_timestamp: Fri, 27 Apr 2018 15:08:15 UTC
end_timestamp: Fri, 27 Apr 2018 15:08:18 UTC
+-----------------------------+------------------------+-------+---------------+----------------------------+
| id                          | status                 | task  | action        | start_timestamp            |
+-----------------------------+------------------------+-------+---------------+----------------------------+
| + 5ae33ce0c4da5f06a163e0d2  | succeeded (2s elapsed) | task1 | default.child | Fri, 27 Apr 2018 15:08:16  |
|                             |                        |       |               | UTC                        |
|    5ae33ce0c4da5f06a163e0d4 | succeeded (1s elapsed) | task1 | core.local    | Fri, 27 Apr 2018 15:08:16  |
|                             |                        |       |               | UTC                        |
+-----------------------------+------------------------+-------+---------------+----------------------------+
vagrant@st2vagrant:~$ st2 --version
```

This all appears to be working as expected.

Please provide a minimal set of workflows and the exact steps you go through to reproduce this problem.
