### ISSUE TITLE
How to handle exception in publishing variable

### ISSUE THREAD

**Issue by prabakar1978** [StackStorm/st2#4205]
##### SUMMARY

If the publish variables is having exception then how it should be handled.

Example Yaml

```yaml
version: '2.0'

menandmice.wf_add_dns_zone:
  description: >
    A sample workflow that demonstrates how to create a master DNS zone
    and several slave zones on slave servers.
    type: direct
  input:
    - session
    - server
    - zone_name
    - master_server
    - slave_servers
  output:
    master_server_ref: "{{ _.master_server_ref }}"
    master_server_ip: "{{ _.master_server_ip }}"
  tasks:
    get_master_server:
      action: menandmice.get_dns_servers
      input:
        session: "{{ _.session }}"
        server: "{{ _.server }}"
        filter: "name: {{ _.master_server }}"
      publish:
        master_server_obj: "{{ task('get_master_server').result.result.dnsServers.dnsServer[0] }}"\
      on-success:
        - parse_master__server

    parse_master_server:
      action: std.noop
      publish:
        master_server_ref: "{{ _.master_server_obj.ref }}"
        master_server_ip: "{{ _.master_server_obj.address }}"

example:
        master_server_obj: "{{ task('get_master_server').result.result.dnsServers.dnsServer[0] }}"\
```

if dnsServer is not coming as list then exception is raising in the background.  How this error need to be handled.  I tried error handling. It is working fine for action but it is not handling when I am sending wrong variable in the publish
