### ISSUE TITLE
napalm.facts https error

### ISSUE THREAD

**Issue by mmihir82** [StackStorm/st2#4228]
##### SUMMARY
Hello
Getting error when fetching the napalm.facts

##### ISSUE TYPE
```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='leafsw01', port=22): Max retries exceeded with url: /ins (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 404 Not Found',)))
```

##### STACKSTORM VERSION
Paste the output of `st2 --version`:
`st2 2.7.2, on Python 2.7`

##### OS / ENVIRONMENT / INSTALL METHOD
3.10.0-693.21.1.el7.x86_64

##### STEPS TO REPRODUCE

Not sure why it is using proxy, under config/napalm.yaml this is what I have configured:
```
devices:
  - hostname: leafsw01
    driver: nxos
    port: 22
    credentials: ro
```
Command run: `st2 run napalm.get_facts hostname=leafsw01`
