### ISSUE TITLE
Multiple Inquiries in a workflow lead to pausing state frequently

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#4286]
##### SUMMARY

This is related to #4135, #4137, #4138 and #4028

A single workflow:

workflow
	- action1
	- core.ask1
	- action2
	- core.ask2
	- action3
	
When core.ask1 comes the flow's status is changed to paused successfully. Respond to the inquiry and the flow status is changed to running and action2 is executed.
When core.ask2 comes the flow's status is changed to pausing. I test this many times and this issue is reproduced frequently even waiting for more than one hour. The flow is always pausing and core.ask2 status is pending.

It cannot be resumed in pausing state so I have to update in db.action_execution_d_b and change pausing to paused.
After that responding to the inquiry lead to:
ERROR: 500 Server Error: Internal Server Error
MESSAGE: Internal Server Error for url: http://127.0.0.1:9101/exp/inquiries/5b62842175ac351947192909

Finally I have to use st2 execution resume command to resume it. I also saw this in 2.6.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.7.2, on Python 2.7

##### OS / ENVIRONMENT / INSTALL METHOD
RHEL7.2 Stackstorm upgraded from 2.6

**Comment by dbillor** [comment]
Experiencing same issue have to manually resume to fix it. Very frustrating

**Comment by m4dcoder** [comment]
Is this written as action chain or as mistral workflows?

**Comment by dbillor** [comment]
on my side mistral

**Comment by m4dcoder** [comment]
Here is what I tested on Mistral and I'm not able to reproduce.

The following is the workflow I mocked that runs the core.ask, core.noop, core.ask, and core.noop sequentially.
```
version: '2.0'

sandbox.mistral_consecutive_inquiries:
    tasks:
        task1:
            action: core.ask
            input:
                schema:
                    type: object
                    properties:
                        approved:
                            type: boolean
                            description: "Continue?"
                            required: True
            on-success:
                - task2

        task2:
            action: core.noop
            on-success:
                - task3

        task3:
            action: core.ask
            input:
                schema:
                    type: object
                    properties:
                        approved:
                            type: boolean
                            description: "Really?"
                            required: True
            on-success:
                - task4

        task4:
            action: core.noop
```

Here's the execution result and the inquiry responses.

```
ubuntu@cadmus:~/st2$ st2 run sandbox.mistral_consecutive_inquiries -a
To get the results, execute:
 st2 execution get 5b6b7ece0a08a413aa7f8eda

To view output in real-time, execute:
 st2 execution tail 5b6b7ece0a08a413aa7f8eda
ubuntu@cadmus:~/st2$ st2 execution get 5b6b7ece0a08a413aa7f8eda
id: 5b6b7ece0a08a413aa7f8eda
action.ref: sandbox.mistral_consecutive_inquiries
parameters: None
status: paused
start_timestamp: Wed, 08 Aug 2018 23:37:50 UTC
end_timestamp: 
+--------------------------+---------+-------+----------+-----------------+
| id                       | status  | task  | action   | start_timestamp |
+--------------------------+---------+-------+----------+-----------------+
| 5b6b7ece0a08a413aa7f8edd | pending | task1 | core.ask | Wed, 08 Aug     |
|                          |         |       |          | 2018 23:37:50   |
|                          |         |       |          | UTC             |
+--------------------------+---------+-------+----------+-----------------+
```

```
ubuntu@cadmus:~/st2$ st2 inquiry respond 5b6b7ece0a08a413aa7f8edd
approved (boolean): Yes

Response accepted for inquiry 5b6b7ece0a08a413aa7f8edd.
```

```
ubuntu@cadmus:~/st2$ st2 execution get 5b6b7ece0a08a413aa7f8eda
id: 5b6b7ece0a08a413aa7f8eda
action.ref: sandbox.mistral_consecutive_inquiries
parameters: None
status: paused
start_timestamp: Wed, 08 Aug 2018 23:37:50 UTC
end_timestamp: 
result: 
  extra:
    state: RUNNING
    state_info: null
+--------------------------+------------------------+-------+-----------+-----------------+
| id                       | status                 | task  | action    | start_timestamp |
+--------------------------+------------------------+-------+-----------+-----------------+
| 5b6b7ece0a08a413aa7f8edd | succeeded (1s elapsed) | task1 | core.ask  | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:37:50   |
|                          |                        |       |           | UTC             |
| 5b6b7eea0a08a413aa7f8edf | succeeded (1s elapsed) | task2 | core.noop | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:38:18   |
|                          |                        |       |           | UTC             |
| 5b6b7eeb0a08a413aa7f8ee1 | pending                | task3 | core.ask  | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:38:19   |
|                          |                        |       |           | UTC             |
+--------------------------+------------------------+-------+-----------+-----------------+

```

```
ubuntu@cadmus:~/st2$ st2 inquiry respond 5b6b7eeb0a08a413aa7f8ee1
approved (boolean): Yes

Response accepted for inquiry 5b6b7eeb0a08a413aa7f8ee1.
```

```
ubuntu@cadmus:~/st2$ st2 execution get 5b6b7ece0a08a413aa7f8eda
id: 5b6b7ece0a08a413aa7f8eda
action.ref: sandbox.mistral_consecutive_inquiries
parameters: None
status: succeeded (58s elapsed)
result_task: task4
result: 
  failed: false
  return_code: 0
  succeeded: true
start_timestamp: Wed, 08 Aug 2018 23:37:50 UTC
end_timestamp: Wed, 08 Aug 2018 23:38:48 UTC
+--------------------------+------------------------+-------+-----------+-----------------+
| id                       | status                 | task  | action    | start_timestamp |
+--------------------------+------------------------+-------+-----------+-----------------+
| 5b6b7ece0a08a413aa7f8edd | succeeded (1s elapsed) | task1 | core.ask  | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:37:50   |
|                          |                        |       |           | UTC             |
| 5b6b7eea0a08a413aa7f8edf | succeeded (1s elapsed) | task2 | core.noop | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:38:18   |
|                          |                        |       |           | UTC             |
| 5b6b7eeb0a08a413aa7f8ee1 | succeeded (0s elapsed) | task3 | core.ask  | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:38:19   |
|                          |                        |       |           | UTC             |
| 5b6b7f060a08a413aa7f8ee3 | succeeded (0s elapsed) | task4 | core.noop | Wed, 08 Aug     |
|                          |                        |       |           | 2018 23:38:46   |
|                          |                        |       |           | UTC             |
+--------------------------+------------------------+-------+-----------+-----------------+
```

Can you provide an example workflow that I can use to reproduce the issue?
