### ISSUE TITLE
Orquesta - Support output-on-error semantics

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4336]
##### SUMMARY

In Mistral workflows there was an option for an `output-on-error` stanza. This block allowed workflow authors to return data in the event of an error within the workflow. We use this feature internally do things like:

- Returning meaningful error messages from workflows
- Returning the data that caused the error from a workflow
- Returning a list of tasks that completed and those that failed within a variable (used for emails, ticketing systems and dashboards)

I would be open to a different mechanism (does not need to be `output-on-error`). But some way to replicate this functionality would be great!

##### ISSUE TYPE
 - Feature Request

##### STACKSTORM VERSION
```shell
$ st2 --version
st2 2.8.1, on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD

```
OS = CentOS 7.5
Install method = puppet-st2
```

##### Example Mistral workflow

```yaml
encore.preprovision:
  type: direct
  input:
    - domain_type
    - dns_domain
    - hostname
    - task_list: []
    - vm_os

  output:
    ip_address: "{{ _.ip_address | default(None) }}"
    task_list: "{{ _.task_list }}"
    vm_dns_records: "{{ _.dns_records | default(None) }}"
    vm_os_name: "{{ _.vm_os_name | default(None) }}"
  output-on-error:
    task_list: "{{ _.task_list }}"
    vm_dns_records: "{{ _.dns_records | default(None) }}"

  tasks:

...

    validate_ipam_hostname_unique:
      action: encore.mm_check_hostname
      input:
        hostname: "{{ _.hostname }}"
        dns_domain: "{{ _.dns_domain }}"
      publish:
        task_list: "{{ _.task_list + [{'name': 'validate_ipam_hostname_unique', 'status': 'SUCCESS'}] }}"
      publish-on-error:
        task_list: "{{ _.task_list + [{'name': 'validate_ipam_hostname_unique', 'status': 'ERROR', 'err_reason': 'Host already exists with name: ' + _.hostname + '.' + _.dns_domain }] }}"
      on-success:
        - validate_ad_computer_unique: "{{ _.vm_os.type == 'windows' and _.domain_type.lower() == 'domain' }}"
        - build_dns_records: "{{ _.vm_os.type != 'windows' or _.domain_type.lower() != 'domain' }}"
      on-error:
        - send_error_email
...
```

**Comment by m4dcoder** [comment]
Here's another variation. We can add a log entry to be included in the errors of orquesta workflow result.  Orquesta workflow currently has list of errors and output in the result.

```
version: 1.0

description: A workflow demonstrating fail command.

tasks:
  task1:
    action: core.local
    input:
      cmd: '>&2 echo "boom!"; exit 1'
    next:
      - when: <% failed() %>
        publish:
          - err_msg: 'task1 failed'
          - extra_data: <% result().stderr %>
        log:
          - message: <% ctx(err_msg) %>
            result: <% ctx(extra_data) %>
        do: fail
```
