### ISSUE TITLE
Ability to support large datasets

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4343]
##### SUMMARY

StackStorm actions+workflows works great on small datasets. However, as datasets grow StackStorm begins to slow down significantly. For example, i'm working with some data that is a few 100KB in size and StackStorm workflows runs in about 60 seconds, the majority of the time is spent reading/writing data from MongoDB. Also, this puts a large load on the `st2rulesengine` when triggers for these actions come through, as it needs to query the database for the large datasets.

This feature request is to support large datasets in a more performant way (desired outcome). How this is achieved is flexible.

##### ISSUE TYPE
 - Feature Idea

##### EXPECTED RESULTS
Handling medium-large datasets in workflows has minimal performance impact.

**Comment by Kami** [comment]
StackStorm v2.9.0 will include some changes which will help a bit with that.

As discussed before, other changes which are needed to reduce the overhead of mongoengine and message bus publish layer are much more involved and will require a lot more work and thought into it. 

We will basically need to rewrite one of our core abstraction layers on which most of the code relies so it won't be an easy or smooth change (again, a lot of it is due to some "bad" / inefficient decisions made very early on like publishing whole database objects on the message bus instead of just the ID + attributes which are needed, etc.).

One of the tasks will definitely be moving performance critical code paths away from mongoengine, but because of the high reliance of our code on this existing document and publish abstraction it will be a hard change.

Having said that - we should discuss the options, plan the work and try to start working on it incrementally (as much as possible) post v2.9.0 / v3.0.0.

**Comment by nmaludy** [comment]
Brain storming a little here, i thought of maybe adding the ability to read/write from an external system for inputs/outputs?

Something like (just a mock up):
```yaml
task1:
  action: mypack.myaction
  input-ext:
    mysql:
      connection: mysql://user:pass@database.domain.tld
      query: SELECT id,name,date FROM orders ORDER BY date DESC;
  input:
    data: "{{ input_ext().result }}"
  publish-ext:
    mysql:
      connection: mysql://user:pass@database.domain.tld
      context:
        data: "{{ task('task1').result }}"
      query: "INSERT INTO orders VALUES {{ _.data }}"
```
