### ISSUE TITLE
Orquesta - ChatOps - Duplicate chatops.post_result tasks triggered

### ISSUE THREAD

**Issue by kingsleyadam** [StackStorm/st2#4362]
##### SUMMARY

When an orquesta action is triggered via ChatOps (Slack in my Case) chatops.post_result task would be triggered twice.

From a very quick conversation on Slack "looks like the Orquesta runner doesn't have a `skip_notify` parameter on it"

It seems as though it's triggering the action twice because ChatOps and Orquesta are running the trigger, posting the same results.

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION

st2 2.8.1, on Python 2.7.12

##### OS / ENVIRONMENT / INSTALL METHOD
Ubuntu 16.04 
One line install

##### STEPS TO REPRODUCE
Using any Orquesta workflow trigger it from a ChatOps action alias. See the duplicate chatops.notify tasks being run after the Orquesta action.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/5278244/46014386-59134b00-c0cf-11e8-8da2-d3dd49b5b34c.png">

##### EXPECTED RESULTS
I would expect that just one chatops.post_result task would be triggered

##### ACTUAL RESULTS
Two chatops.post_result tasks are being triggered.

**Comment by LindsayHill** [comment]
What does `st2 rule list` show you?

**Comment by kingsleyadam** [comment]
Here's what I've got:

```
+-------------------------------------------+----------+--------------------------------------------------------+---------+
| ref                                       | pack     | description                                            | enabled |
+-------------------------------------------+----------+--------------------------------------------------------+---------+
| chatops.notify                            | chatops  | Notification rule to send results of action executions | True    |
|                                           |          | to stream for chatops                                  |         |
| email.Sample                              | email    | Rule which sends an email when an email from           | False   |
|                                           |          | johndoe@gmail.com is received                          |         |
| examples.notify_inquiry                   | examples | Notify relevant users of an Inquiry action             | False   |
| examples.notify_slack                     | examples | Sample rule firing on action completion.               | True    |
| examples.sample_rule_file_watch           | examples | Sample rule custom trigger type - add a file to be     | True    |
|                                           |          | watched by file_watch_sensor in linux pack.            |         |
| examples.sample_rule_with_actiontrigger   | examples | Sample rule firing on action completion.               | True    |
| examples.sample_rule_with_timer           | examples | Sample rule using an Interval Timer.                   | False   |
| examples.sample_rule_with_webhook         | examples | Sample rule dumping webhook payload to a file.         | True    |
| git.st2.webhook.github.pulls.merge.sample | git      | Sample rule dumping webhook payload to a file.         | True    |
+-------------------------------------------+----------+--------------------------------------------------------+---------+
```

**Comment by LindsayHill** [comment]
I would check out the contents of `examples.notify_slack` - it looks like you've set up a rule that duplicates what `chatops.notify` does.

**Comment by kingsleyadam** [comment]
I've disabled all the example rules and I'm still getting duplicates. I should also note, this ONLY happens with Orquesta workflows. All others don't product the duplicate tasks.

```
+-------------------------------------------+----------+--------------------------------------------------------+---------+
| ref                                       | pack     | description                                            | enabled |
+-------------------------------------------+----------+--------------------------------------------------------+---------+
| chatops.notify                            | chatops  | Notification rule to send results of action executions | True    |
|                                           |          | to stream for chatops                                  |         |
| email.Sample                              | email    | Rule which sends an email when an email from           | False   |
|                                           |          | johndoe@gmail.com is received                          |         |
| examples.notify_inquiry                   | examples | Notify relevant users of an Inquiry action             | False   |
| examples.notify_slack                     | examples | Sample rule firing on action completion.               | False   |
| examples.sample_rule_file_watch           | examples | Sample rule custom trigger type - add a file to be     | False   |
|                                           |          | watched by file_watch_sensor in linux pack.            |         |
| examples.sample_rule_with_actiontrigger   | examples | Sample rule firing on action completion.               | False   |
| examples.sample_rule_with_timer           | examples | Sample rule using an Interval Timer.                   | False   |
| examples.sample_rule_with_webhook         | examples | Sample rule dumping webhook payload to a file.         | False   |
| git.st2.webhook.github.pulls.merge.sample | git      | Sample rule dumping webhook payload to a file.         | True    |
+-------------------------------------------+----------+--------------------------------------------------------+---------+
```

**Comment by LindsayHill** [comment]
Look at the executions in the history tab in the Web UI. Click on each of them, and look at the details on the right-hand side. What does it say in the "Rule Details" section?

Should be something like this: 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/3607046/46046392-bb6f4a00-c0d5-11e8-914e-c6aca764f977.png">

**Comment by LindsayHill** [comment]
Also look at the output of `st2 trigger-instance list` - what does that show?

**Comment by kingsleyadam** [comment]
Thanks for your help @LindsayHill. Looking at the rules details, both chatops tasks show what you have:

![image](https://user-images.githubusercontent.com/5278244/46046942-43c80c00-c123-11e8-9dbc-73759434383c.png)

`st2 trigger-instance list` show's

```
+--------------------------+-------------------------------------------+-------------------------------+-----------+
| id                       | trigger                                   | occurrence_time               | status    |
+--------------------------+-------------------------------------------+-------------------------------+-----------+
| 5baab60319b7f304699e7cc1 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:11 UTC | processed |
| 5baab60819b7f304699e7cc3 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:16 UTC | processed |
| 5baab60d19b7f304699e7cc5 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:21 UTC | processed |
| 5baab61219b7f304699e7cc7 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:26 UTC | processed |
| 5baab61719b7f304699e7cc9 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:31 UTC | processed |
| 5baab61c19b7f304699e7ccb | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:36 UTC | processed |
| 5baab62119b7f304699e7ccd | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:41 UTC | processed |
| 5baab62619b7f304699e7ccf | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:46 UTC | processed |
| 5baab62b19b7f304699e7cd1 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:51 UTC | processed |
| 5baab63019b7f304699e7cd3 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:26:56 UTC | processed |
| 5baab63519b7f304699e7cd5 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:01 UTC | processed |
| 5baab63a19b7f304699e7cd7 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:06 UTC | processed |
| 5baab63f19b7f304699e7cd9 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:11 UTC | processed |
| 5baab64419b7f304699e7cdb | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:16 UTC | processed |
| 5baab64919b7f304699e7cdd | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:21 UTC | processed |
| 5baab64e19b7f304699e7cdf | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:26 UTC | processed |
| 5baab65319b7f304699e7ce1 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:31 UTC | processed |
| 5baab65819b7f304699e7ce3 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:36 UTC | processed |
| 5baab65d19b7f304699e7ce5 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:41 UTC | processed |
| 5baab66219b7f304699e7ce7 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:46 UTC | processed |
| 5baab66719b7f304699e7ce9 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:51 UTC | processed |
| 5baab66c19b7f304699e7ceb | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:27:56 UTC | processed |
| 5baab67119b7f304699e7ced | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:01 UTC | processed |
| 5baab67619b7f304699e7cef | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:06 UTC | processed |
| 5baab67b19b7f304699e7cf1 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:11 UTC | processed |
| 5baab68019b7f304699e7cf3 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:16 UTC | processed |
| 5baab68519b7f304699e7cf5 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:21 UTC | processed |
| 5baab68a19b7f304699e7cf7 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:26 UTC | processed |
| 5baab68f19b7f304699e7cf9 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:31 UTC | processed |
| 5baab69419b7f304699e7cfb | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:36 UTC | processed |
| 5baab69919b7f304699e7cfd | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:41 UTC | processed |
| 5baab69e19b7f304699e7cff | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:46 UTC | processed |
| 5baab6a319b7f304699e7d01 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:51 UTC | processed |
| 5baab6a819b7f304699e7d03 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:28:56 UTC | processed |
| 5baab6ad19b7f304699e7d05 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:01 UTC | processed |
| 5baab6b219b7f304699e7d07 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:06 UTC | processed |
| 5baab6b719b7f304699e7d09 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:11 UTC | processed |
| 5baab6bc19b7f304699e7d0b | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:16 UTC | processed |
| 5baab6c119b7f304699e7d0d | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:21 UTC | processed |
| 5baab6c619b7f304699e7d0f | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:26 UTC | processed |
| 5baab6cb19b7f304699e7d11 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:31 UTC | processed |
| 5baab6d019b7f304699e7d13 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:36 UTC | processed |
| 5baab6d519b7f304699e7d15 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:41 UTC | processed |
| 5baab6da19b7f304699e7d17 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:46 UTC | processed |
| 5baab6df19b7f304699e7d19 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:51 UTC | processed |
| 5baab6e419b7f304699e7d1b | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:29:56 UTC | processed |
| 5baab6e919b7f304699e7d1d | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:30:01 UTC | processed |
| 5baab6ee19b7f304699e7d1f | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:30:06 UTC | processed |
| 5baab6f319b7f304699e7d21 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:30:11 UTC | processed |
| 5baab6f819b7f304699e7d23 | core.218ade32-ef5c-4cf1-9009-2a28f64657b1 | Tue, 25 Sep 2018 22:30:16 UTC | processed |
+--------------------------+-------------------------------------------+-------------------------------+-----------+
+------------------------------------------------------------------------------------------------------------------+
| Note: Only first 50 triggerinstances are displayed. Use -n/--last flag for more results.                         |
+------------------------------------------------------------------------------------------------------------------+
```

**Comment by LindsayHill** [comment]
Those trigger instances look like they’re based on a 5s timer rule. They’re not related to chatops notification. 

Disable that rule, re-run your workflow, and look at trigger instances again

**Comment by kingsleyadam** [comment]
Got it. Here's an updated list removing those extra triggers.

```
+--------------------------+-------------------------------------------+-------------------------------+-----------+
| id                       | trigger                                   | occurrence_time               | status    |
+--------------------------+-------------------------------------------+-------------------------------+-----------+
| 5baabbde19b7f304699e7f1f | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:10 UTC | processed |
| 5baabbdf19b7f304699e7f20 | core.st2.generic.notifytrigger            | Tue, 25 Sep 2018 22:51:11 UTC | processed |
| 5baabbdf19b7f304699e7f21 | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:11 UTC | processed |
| 5baabbdf19b7f304699e7f22 | core.st2.generic.notifytrigger            | Tue, 25 Sep 2018 22:51:11 UTC | processed |
| 5baabbdf19b7f304699e7f23 | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:11 UTC | processed |
| 5baabbe019b7f304699e7f2c | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:12 UTC | processed |
| 5baabbe019b7f304699e7f2d | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:12 UTC | processed |
| 5baabbe119b7f304699e7f2e | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:13 UTC | processed |
| 5baabbe119b7f304699e7f2f | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:13 UTC | processed |
| 5baabbe119b7f304699e7f30 | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:13 UTC | processed |
| 5baabbe119b7f304699e7f31 | core.st2.generic.actiontrigger            | Tue, 25 Sep 2018 22:51:13 UTC | processed |
+--------------------------+-------------------------------------------+-------------------------------+-----------+
+------------------------------------------------------------------------------------------------------------------+
| Note: Only first 50 triggerinstances are displayed. Use -n/--last flag for more results.                         |
+------------------------------------------------------------------------------------------------------------------+
```

**Comment by LindsayHill** [comment]
The next step would be to do `st2 trigger-instance get <ID>` on those, and find two that seem to be related to the same task in your workflow. Post that info here.

You should also post a workflow that reproduces this. It looks like you have multiple actions in your workflow?

Also: ST2 2.9 is now public. I haven't looked through the details to see if there is a related issue fixed in this version, but 2.9 includes the second beta of Orquesta, so there may be related bug fixes.

**Comment by kingsleyadam** [comment]
That's correct, I have 2 tasks in this workflow. But it doesn't matter the number of tasks I have in a workflow.

The two notify triggers in that list are identical.

The different actiontrigger's running at the exact same time as the notify are:

1. For the last task in the workflow
2. For the workflow task itself.

Here's the workflow I'm using:

```yaml
version: 1.0

description: A workflow to build in bamboo, then roll the realm.

input:
  - realm
  - be_git_branch
  - ui_git_branch

output:
  - context: <% ctx() %>

tasks:
  bamboo:
    action: my_pack.branch_realm_build_bamboo
    input:
      realm: <% ctx(realm) %>
      be_git_branch: <% ctx(be_git_branch) %>
      ui_git_branch: <% ctx(ui_git_branch) %>
    next:
      - when: <% succeeded() %>
        publish: bamboo=<% result().result %>
        do: bamboo_wait
      - when: <% failed() %>
        publish:
          - stderr: <% result().stderr %>
          - stdout: <% result().stdout %>
        do: notify_on_error
  bamboo_wait:
    action: my_pack.branch_realm_build_bamboo_wait
    input:
      bamboo_builds: <% ctx(bamboo) %>
    next:
      - when: <% failed() %>
        publish:
          - stderr: <% result().stderr %>
          - stdout: <% result().stdout %>
        do: notify_on_error
  notify_on_error:
    next:
    - do: fail
```

**Comment by LindsayHill** [comment]
> 1. For the last task in the workflow
> 2. For the workflow task itself.

Wait, I thought the problem was duplicate notifications - is it actually that you're getting individual task notifications, as well as overall workflow completion notification? Is the problem that `skip_notify` doesn't work for Orquesta?

What is the contents of those trigger-instances? Are they all identical?

**Comment by kingsleyadam** [comment]
It's not sending a notification for every task in the workflow. If that were the case I would have gotten 3 notifications (2 tasks + workflow). I also have workflows with up to 8 tasks and those only produce 2 notifications.

I just ran a workflow with 8 tasks and I got two notifications. One for the very last task in the workflow, and one for the workflow itself.

Is there a way to `skip_notify` in a orquesta workflow? Or the very least, customize it? I would really like to send notifications after certain tasks to keep the user up-to-date on the progress of their execution.

**Comment by LindsayHill** [comment]
> Is there a way to `skip_notify` in a task in an orquesta workflow? Or the very least, customize it? I would really like to send notifications after certain tasks to keep the user up-to-date on the progress of their execution.

`skip_notify` is not supported for Orquesta today. `notify` will be supported in a future release (will be reverse behavior of `skip_notify`).

Personally I'm not a big fan of automatic notification for tasks anyway - my preferred workaround is to explicitly call `chatops.post_message` at specific points in the workflow. That way I have much greater control over output message & formatting

**Comment by kingsleyadam** [comment]
Completely agree, I'd rather I explicitly notify rather than assume to notify.

After upgrading to 2.9 I no longer get double notifications, there must have been an issue with 2.8. Thanks for your help in troubleshooting, I really appreciate it!

I'm going to give the chatops.post_message a try. Still new this this and didn't even think of add this to the workflow.

**Comment by LindsayHill** [comment]
Check out some of the examples in this [workflow](https://github.com/StackStorm/st2_demos/blob/master/actions/workflows/link_flap_remed_workflow.yaml#L13) that use `chatops.post_message` - they show a few additional options around formatting. Might be useful.

Good to hear double notifications resolved somewhere in 2.9 branch. Not surprising, since 2.8 was first public beta fro Orquesta, and it's still a work in progress.

**Comment by NikonNLG** [comment]
Have the same issue with following versions:
st2:3.3.0-3
st2chatops:3.3.0-1

I found that I have two notifications only if at least one task has `-failed` parameter.
Workflow to reproduce:


```
---
version: 1.0

description: Update AWS Parameter Store

input:
  - environment

vars:
  - task_message: null
  - stdout: null
  - stderr: null

output:
  - task_message: <% ctx().task_message %>
  - stdout: <% ctx().stdout %>
  - stderr: <% ctx().stderr %>

tasks:
  main:
    action: core.noop
    next:
      - when: <% succeeded() %>
        publish:
          - task_message: "main ok"
        do:
          - test
          - notify_slack
      - when: <% failed() %>
        publish:
          - task_message: "main failed"
          - stderr: <% result().stderr %>
        do:
          - notify_slack

  test:
    action: core.noop
    next:
      - when: <% succeeded() %>
        publish:
          - task_message: "test ok"
        do:
          - test2
          - notify_slack
      - when: <% failed() %>
        publish:
          - task_message: "test failed"
          - stderr: <% result().stderr %>
        do:
          - notify_slack

  test2:
    action: core.local cmd="exit 0"
    next:
      - when: <% succeeded() %>
        publish:
          - task_message: "test2 ok"
          - stdout: <% result().stdout %>
        do:
          - test3
          - notify_slack
      - when: <% failed() %>
        publish:
          - task_message: "test2 failed"
          - stderr: <% result().stderr %>
        do:
          - fail
          - notify_slack

  test3:
    action: core.local cmd="exit 1"
    next:
      - when: <% succeeded() %>
        publish:
          - task_message: "test3 ok"
          - stdout: <% result().stdout %>
        do:
          - notify_slack
      - when: <% failed() %>
        publish:
          - task_message: "test3 failed"
          - stderr: <% result().stderr %>
        do:
          - fail
          - notify_slack

  notify_slack:
    action: chatops.post_message
    input:
      message: "<% ctx('task_message') %>"
      channel: "<% ctx().st2.source_channel %>"
    next:
      - when: <% succeeded() %>
        publish:
          - task_message: <% ctx('task_message') %>
          - stdout: <% ctx('stdout') %>
          - stderr: <% ctx('stderr') %>
```

If you replace `task3` to `exit 0` it will run chatops.post_message only once.
