### ISSUE TITLE
Bad error when passing a non-array input from a workflow into an action parameter of type array

### ISSUE THREAD

**Issue by jeking3** [StackStorm/st2#4375]
##### SUMMARY

With an action that takes a parameter of type `array`, I can run the action from the command line and I can even pass a regular string to it, and it seems to figure it out.  However if I do the same thing from a workflow (either mistral or orquesta, it doesn't matter, they both fail) and pass a string into an array parameter for an action, things error out badly without a good error message.  Improving the error message would be a sufficient remedy; in fact getting the parameter/input field name into the error message would be good too.

##### ISSUE TYPE

 - Bug Report

##### STACKSTORM VERSION

st2 3.0dev (3438b7c), on Python 2.7.6 (also happens on 2.9.0)

##### OS / ENVIRONMENT / INSTALL METHOD

st2-docker

##### STEPS TO REPRODUCE
Install the pack I made that demonstrates the issue:
>    `st2 pack install https://github.com/jeking3/st2-issue-badtype.git`

Run the action and pass in a string, see that it works even though the input is of type array - this is because the presence of just one argument is still handled as an array:
```
root@f34287ba9aa8:/# st2 run badtype.take_array value=hello
.
id: 5bb60780668fd406fff4d76f
status: succeeded
parameters:
  value:
  - hello
result:
  exit_code: 0
  result:
  - hello
  stderr: ''
  stdout: ''
```

Now run the `bad_workflow` which attempts to feed the same input from a workflow:
```
    input:
      value: hello
```
and the result:
```
root@f34287ba9aa8:/# st2 run badtype.bad_workflow
.
id: 5bb609d5668fd406fff4d781
action.ref: badtype.bad_workflow
parameters: None
status: failed
start_timestamp: Thu, 04 Oct 2018 12:38:45 UTC
end_timestamp: Thu, 04 Oct 2018 12:38:46 UTC
result:
  errors:
  - message: malformed string
    task_id: task1
  output: null
```

Do the same thing with `good_workflow` which sends in:
```
    input:
      value: [hello]
```
and the result:
```
root@f34287ba9aa8:/# st2 run badtype.good_workflow
..
id: 5bb60adc668fd406fff4d78a
action.ref: badtype.good_workflow
parameters: None
status: succeeded
start_timestamp: Thu, 04 Oct 2018 12:43:08 UTC
end_timestamp: Thu, 04 Oct 2018 12:43:11 UTC
result:
  output: null
+--------------------------+------------------------+-------+--------------------+-------------------------------+
| id                       | status                 | task  | action             | start_timestamp               |
+--------------------------+------------------------+-------+--------------------+-------------------------------+
| 5bb60add668fd407a23a2d0e | succeeded (1s elapsed) | task1 | badtype.take_array | Thu, 04 Oct 2018 12:43:09 UTC |
+--------------------------+------------------------+-------+--------------------+-------------------------------+
```

##### EXPECTED RESULTS
I expected to either have it "just work" like the direct action run works, or to have it error out with a message indicating the parameter name that was bad, and why it was bad.  In this case saying, "not an array" perhaps instead of "malformed string".  I guess the command line argument processing is smart enough to convert all instances of value into array members, but this doesn't happen from a workflow.

##### ACTUAL RESULTS
See steps to reproduce.
