### ISSUE TITLE
Actions with immutable=true, default set and enum cannot be run from UI

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#4377]
##### SUMMARY

While trying to run example from https://github.com/StackStorm/st2/blob/ddd3aba57d8cccaaaef64babd07dd48e0b68c42a/contrib/examples/actions/weather.yaml from the web UI I ran into an issue when the call to API would fail with 
```
{
    "faultstring": "Override of immutable parameter(s) [u'method'] is unsupported."
}
```
Running the same action from CLI worked just fine. Also, removing enum helps.

##### ISSUE TYPE

 - Bug Report

##### STACKSTORM VERSION
Paste the output of `st2 --version`:

st2 2.9.0, on Python 2.7.10

##### OS / ENVIRONMENT / INSTALL METHOD

RPM packages on CentOS 6.

##### STEPS TO REPRODUCE
```yaml
---
description: Look up weather via http://openweathermap.org
# Free weather API is provided under the terms of the Creative Commons Attribution-ShareAlike 4.0 Generic License.
# Terms of service http://openweathermap.org/terms
enabled: true
entry_point: ''
name: weather
parameters:
  auth:
    type: string
  headers:
    type: object
  method:
    default: GET
    type: string
    enum:
    - GET
    - POST
    - PUT
    - DELETE
    immutable: true
  params:
    type: string
  timeout:
    default: 60
    type: integer
  url:
    default: http://api.openweathermap.org/data/2.5/weather?q={{zip}}&units=imperial
    immutable: true
    type: string
  zip:
    type: string
runner_type: "http-request"
```

Going to st2 web and trying to execute this action fails. The UI is adding `method: GET` into params passed to st2api, which it rejects with the explanation shown above and below.

##### EXPECTED RESULTS
Expect it to be run successfully both from the UI and CLI.

##### ACTUAL RESULTS
Got 400 Bad Request with
```
{
    "faultstring": "Override of immutable parameter(s) [u'method'] is unsupported."
}
```
