### ISSUE TITLE
Orquesta - default jinja filter with context vars

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#4413]
##### SUMMARY

Please make it possible to use the `default` jinja filter with context vars.

##### ISSUE TYPE
 - Bug Report
(might be a Feature Idea)

##### STACKSTORM VERSION
```
st2 2.9.1, on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
CentOS 7
Installed via ansible-st2

##### STEPS TO REPRODUCE
```yaml
version: '1.0'
description: default filter with a context variable
tasks:
  foobar:
    action: some.action
    input:
      foobar: '{{ ctx().qwerty | default(false) }}'
```
(mocked up example from a workflow I wrote. a real test case needs a real action, or maybe core.noop with a publish line)

##### EXPECTED RESULTS
Publish foobar = asdf

##### ACTUAL RESULTS
error message
```
    {
      "language": "jinja",
      "type": "context",
      "spec_path": "tasks.foobar.input",
      "schema_path": "properties.tasks.patternProperties.^\\w+$.properties.input",
      "message": "Variable \"qwerty\" is referenced before assignment.",
      "expression": "{{ ctx().qwerty | default(false) }}"
    }
```
(munged error message to match mocked up example above)
