### ISSUE TITLE
Jinja/Yaql values are not evaluated while loading concurrency policy

### ISSUE THREAD

**Issue by sumeetisp** [StackStorm/st2#4417]
##### SUMMARY

Provide a quick summary of your bug or feature request.

Consider the following concurrency policy with threshold value being referred from datastore
```
name: my_action.concurrency
description: Limits the concurrent executions for my action.
enabled: true
resource_ref: demo.my_action
policy_type: action.concurrency
parameters:
    action: delay
    threshold: "{{ st2kv.system.action_concurrency }}"
```
When loading the policy this jinja expression is not evaluated and fails with following error.
```
MESSAGE: u'{{ st2kv.system.action_concurrency }}' is not of type u'integer' for url: http://127.0.0.1:9101/v1/policies .
```
##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report
 - Feature Idea
 - Other

##### STACKSTORM VERSION
st2 2.7.2, on Python 2.7

##### STEPS TO REPRODUCE

```yaml

```
