### ISSUE TITLE
Orquesta publish error message could be more friendly

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4429]
##### SUMMARY

When trying to publish a variable and i accidentally put in a dict instead of an array, the error message was confusing and not obvious what i needed to change the data type to.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
```
$ st2 --version
st2 3.0dev (3ac37d0), on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
```
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 

# Install method = puppet-st2
```

##### STEPS TO REPRODUCE
Action
```
---
name: basic_workflow
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/basic_workflow.yaml
enabled: true
parameters:
  key:
    required: true
    type: string
    default: test.datastore.key
```

Workflow
```yaml
version: 1.0
  
description: A basic sequential workflow.

input:
  - key

vars:
  - read: null

output:
  - read: "{{ ctx().read }}"

tasks:
  get:
    action: st2.kv.get
    input:
      key: "{{ ctx().key }}"
    next:
      - when: "{{ succeeded() }}"
        publish:
          read: "{{ result() }}"
```

##### EXPECTED RESULTS

I was able to quickly determine where in the workflow the error was (the publish statement). However, the error message `'{''read'': ''{{ result() }}''} is not valid under any of the given schemas'` did not provide what the valid schemas were. It would be nice if it told you what the expected schema was and what data type you provided. In this case i provided a dict instead of an array of one-key dicts.

##### ACTUAL RESULTS
```
$ st2 run default.basic_workflow
.
id: 5be2ea719387ef099b022feb
action.ref: default.basic_workflow
parameters: None
status: failed
start_timestamp: Wed, 07 Nov 2018 13:36:49 UTC
end_timestamp: Wed, 07 Nov 2018 13:36:49 UTC
result: 
  errors:
  - message: '{''read'': ''{{ result() }}''} is not valid under any of the given schemas'
    schema_path: properties.tasks.patternProperties.^\w+$.properties.next.items.properties.publish.oneOf
    spec_path: tasks.get.next[0].publish
    type: syntax
  output: null
```
