### ISSUE TITLE
Orquesta workflow outputs are not directly accessible on it result()

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4430]
##### SUMMARY

It appears that orquesta writes its output data to an embedded dictionary in the `output` key.

This is a change from Mistral where output variables were directly accessible in the result.

Example:
```
# mistral
{{ task('abc').myoutputvar }}

# orquesta
{{ result().output.myoutputvar }}
```

This causes issues when converting workflows from Mistral to Orquesta where the tasks are workflow actions.

##### ISSUE TYPE
 - Bug Report
 - Other

##### STACKSTORM VERSION

```
$ st2 --version
st2 3.0dev (3ac37d0), on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
```
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 

# Install method = puppet-st2
```

##### STEPS TO REPRODUCE

Root workflow action
```yaml
---
name: orquesta_root
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/orquesta_root.yaml
enabled: true
parameters:
  name:
    required: true
    type: string
    default: Lakshmi
```

Root workflow
```yaml
version: 1.0
  
description: A basic sequential workflow.

input:
  - name

vars:
  - data: null

output:
  - data: "{{ ctx().data }}"

tasks:
  orquesta_wf:
    action: default.orquesta_wf
    input:
      name: "{{ ctx().name }}"
    next:
      - publish:
          - data: "{{ result().data }}"
```

Nested workflow action:
```yaml
---
name: orquesta_nested
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/orquesta_nested.yaml
enabled: true
parameters:
  name:
    required: true
    type: string
    default: Lakshmi
```

Nested workflow:
```yaml
version: 1.0
  
description: A basic sequential workflow.

input:
  - name

vars:
  - data: null

output:
  - data: "{{ ctx().data }}"

tasks:
  get:
    action: st2.kv.get
    input:
      key: "orquest.mistral.test"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - data: "{{ result() }}"
```

##### EXPECTED RESULTS

The workflow to succeed and access the `data` variable in the output of the nested Orquesta workflow.

##### ACTUAL RESULTS

```
$ st2 run default.orquesta_mistral
.
id: 5be3014f9387ef099b023038
action.ref: default.orquesta_mistral
parameters: None
status: failed
start_timestamp: Wed, 07 Nov 2018 15:14:23 UTC
end_timestamp: Wed, 07 Nov 2018 15:14:25 UTC
result: 
  errors:
  - message: 'There are unresolved variables: result().data'
    task_id: orquesta_wf
    task_transition_id: noop__0
  output: null
+-----------------------------+------------------------+-------------+---------------------+-----------------+
| id                          | status                 | task        | action              | start_timestamp |
+-----------------------------+------------------------+-------------+---------------------+-----------------+
| + 5be3014f9387ef099f55ea5d  | succeeded (1s elapsed) | orquesta_wf | default.orquesta_wf | Wed, 07 Nov     |
|                             |                        |             |                     | 2018 15:14:23   |
|                             |                        |             |                     | UTC             |
|    5be301509387ef099f55ea60 | succeeded (0s elapsed) | get         | st2.kv.get          | Wed, 07 Nov     |
|                             |                        |             |                     | 2018 15:14:24   |
|                             |                        |             |                     | UTC             |
+-----------------------------+------------------------+-------------+---------------------+-----------------+
```
