### ISSUE TITLE
Orquesta workflow does not fail when a 'next' is present (even just to publish)

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4432]
##### SUMMARY

In an Orquesta workflow, if a task fails and there are no `next` items then the workflow itself fails. If you specify `next` item (even just to publish data) then the workflow doesn't fail even though the task fails.

##### ISSUE TYPE
 - Bug Report
 
##### STACKSTORM VERSION
```shell
$ st2 --version
st2 3.0dev (3ac37d0), on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
```shell
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 

# Install method = puppet-st2
```

##### STEPS TO REPRODUCE

Workflow
```yaml
version: 1.0
  
description: A basic sequential workflow.

input:
  - name

vars:
  - data: null

output:
  - data: "{{ ctx().data }}"

tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - publish:
          - data: "{{ result() }}"
```

Action
```yaml
---
name: orquesta_wf
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/orquesta_wf.yaml
enabled: true
parameters:
  name:
    required: true
    type: string
    default: Lakshmi
```

##### EXPECTED RESULTS
If you remove the `next` section from the workflow above:
```yaml
version: 1.0
  
description: A basic sequential workflow.

input:
  - name

vars:
  - data: null

output:
  - data: "{{ ctx().data }}"

tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
```

Then this workflow fails:
```shell
$ st2 run default.orquesta_wf
.
id: 5be384159387ef0629584a6c
action.ref: default.orquesta_wf
parameters: None
status: failed
start_timestamp: Thu, 08 Nov 2018 00:32:21 UTC
end_timestamp: Thu, 08 Nov 2018 00:32:21 UTC
result: 
  errors:
  - message: Execution failed. See result for details.
    result:
      failed: true
      return_code: 1
      stderr: ''
      stdout: ''
      succeeded: false
    task_id: demo
  output: null
+--------------------------+---------------------+------+------------+-----------------+
| id                       | status              | task | action     | start_timestamp |
+--------------------------+---------------------+------+------------+-----------------+
| 5be384159387ef03c1133fea | failed (0s elapsed) | demo | core.local | Thu, 08 Nov     |
|                          |                     |      |            | 2018 00:32:21   |
|                          |                     |      |            | UTC             |
+--------------------------+---------------------+------+------------+-----------------+
```

##### ACTUAL RESULTS
The workflow succeeds
```shell
$ st2 run default.orquesta_wf
.
id: 5be383a59387ef0629584a69
action.ref: default.orquesta_wf
parameters: None
status: succeeded
start_timestamp: Thu, 08 Nov 2018 00:30:29 UTC
end_timestamp: Thu, 08 Nov 2018 00:30:30 UTC
result: 
  output:
    data:
      failed: true
      return_code: 1
      stderr: ''
      stdout: ''
      succeeded: false
+--------------------------+---------------------+------+------------+-----------------+
| id                       | status              | task | action     | start_timestamp |
+--------------------------+---------------------+------+------------+-----------------+
| 5be383a59387ef03c1133fe7 | failed (0s elapsed) | demo | core.local | Thu, 08 Nov     |
|                          |                     |      |            | 2018 00:30:29   |
|                          |                     |      |            | UTC             |
+--------------------------+---------------------+------+------------+-----------------+
```

**Comment by m4dcoder** [comment]
@nmaludy This is an expected behavior. When `next` is specified, this means there is a handler. The workflow engine will assume it's a remediation.  If you want to fail, the correct pattern should be to do an explicit fail. Please note that `output` (or returned value) is not processed in the case of failure.

**Comment by nmaludy** [comment]
This seems pretty non-obvious to me because now we have to do something like:
```yaml
tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - data: "{{ result() }}"
        do: succeed
      - when: "{{ failed() }}"
        publish:
          - data: "{{ result() }}"
        do: fail
```

**Comment by shusugmt** [comment]
OT:

@m4dcoder 

> Please note that output (or returned value) is not processed in the case of failure.

Is this by design decision? With mistral it could return all the published value before it fails, and I could use them in triggers but with Orquesta it's not possible.

**Comment by m4dcoder** [comment]
It seems pretty obvious to me because if there's a transition, it means I don't want it to fail by default and there's additional operation I want to do and I want to handle the failure on my own. The use of `when` is to allow for flexibility in catching various conditions.

btw, the correct workflow would be the following.  only fail needs to be explicit when there is a transition.

```
tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - data: "{{ result() }}"
      - when: "{{ failed() }}"
        publish:
          - data: "{{ result() }}"
        do: fail
```

**Comment by m4dcoder** [comment]
> Is this by design decision? With mistral it could return all the published value before it fails, and I could use them in triggers but with Orquesta it's not possible.

Of course it is a design decision. Mistral doesn't output on failure either. You will have to explicitly define `output-on-error` in Mistral.

**Comment by nmaludy** [comment]
@m4dcoder right, but now every time i need to publish data in the same way for both success and failure i need to duplicate code, it's impossible for me to do something like:

```
tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - when: "{{ succeeded() or failed() }}"
        publish:
          - data: "{{ result() }}"
```

**Comment by shusugmt** [comment]
```
      - when: "{{ failed() }}"
        publish:
          - data: "{{ result() }}"
        do: fail
```

I guess the above part is totally useless since as you said "output (or returned value) is not processed in the case of failure"

**Comment by m4dcoder** [comment]
@shusugmt Yes, it is pretty useless.  But we plan to do something along the line where the action execution result will contain these log messages along with errors.

```
      - when: "{{ failed() }}"
        log:
          message: "blah blah blah"
          data: "{{ result() }}"
        do: fail
```

**Comment by m4dcoder** [comment]
@nmaludy how do you define this in mistral today?

**Comment by nmaludy** [comment]
@m4dcoder currently in Mistral it looks like this:

```
  tasks:
    demo:
      action: core.local
      input:
        cmd: "exit 1"
      publish:
        data: "{{ task('demo').result }}"
      publish-on-error:
        data: "{{ task('demo').result }}"
```

The duplication is necessary due to the `publish` vs `publish-on-error`. However the failure of the workflow is implicit when the task fails. If i wanted to explicitly make it succeed when the task fails i would need to do:

```
  tasks:
    demo:
      action: core.local
      input:
        cmd: "exit 1"
      publish:
        data: "{{ task('demo').result }}"
      publish-on-error:
        data: "{{ task('demo').result }}"
      on-error:
         - succeed
```

I feel like the way Orquesta currently handles it almost "masks" error conditions, which could be dangerous.

**Comment by m4dcoder** [comment]
> but now every time i need to publish data in the same way for both success and failure i need to duplicate code

**Comment by m4dcoder** [comment]
Also, we designed Orquesta to handle cases where success and error isn't clear cut.  For example, a HTTP call that succeed with a 404 error cannot be caught with publish-on-error.

**Comment by nmaludy** [comment]
Sure, but then should i be able to do this at least:

```
tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - data: "{{ result() }}"
      - when: "{{ failed() }}"
        publish:
          - data: "{{ result() }}"
```

This should be identical even with duplicated code.

**Comment by m4dcoder** [comment]
I'm not sure what you mean.  As I understand, you want  to log the result regardless of failure and then fail the task and output the result.  Is that correct?  perhaps you can do the following when we implement the `log` spec.

If you want to fail the workflow on task failure
```
tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - when: "{{ succeeded() }}"
         log:
           - data: "{{ result() }}"
      - when: "{{ failed() }}"
         log:
           - data: "{{ result() }}"
         do: fail
```

If you DO NOT want to fail the workflow on task failure
```
tasks:
  demo:
    action: core.local
    input:
      cmd: "exit 1"
    next:
      - when: "{{ succeeded() or failed() }}"
         log:
           - data: "{{ result() }}"
```
