### ISSUE TITLE
Idea - list of values for default in action parameters

### ISSUE THREAD

**Issue by namachieli** [StackStorm/st2#4434]
##### SUMMARY

Some input fields, depending on the application, can have a finite number of values. For example, an API that allows you to specify a color word from a strict list for the parameter `color`.

Currently there is not a great way (that i know of) to inform that list without it being explicitly listed in the description.

##### PROPOSED

I would think a way to add this in cleanly is allow default to be a list, which in turn is displayed in the WebGUI as a drop down.

```
parameters:
  color:
    type: string
    default:
      - red
      - blue
      - green
```

**Comment by blag** [comment]
NAK. Dropdowns are already possible using [`enum`](https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/weather.yaml#L16):

```yaml
parameters:
  color:
    description: Color for the thing
    type: string
    enum:
      - red
      - blue
      - green
```

Additionally, if the type of a parameter is string, then the default value should not be a YAML array - it should be a string.
