### ISSUE TITLE
changed console output behavior when running a workflow

### ISSUE THREAD

**Issue by mlalmi** [StackStorm/st2#4506]
##### 

- [ ] SUMMARY

since the last update i've noticed a diffrence in cli output when running a workflow action, the "result_task" shows the first task result instead of the last one

st2 is still running but this change bother me, is there a way to set the content of  "result_task" ?

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION
st2 --version :
st2 2.10.1, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD
Centos7

##### STEPS TO REPRODUCE
to reproduce the issue, i've created a simple testpack with a  workflow that displays the date than tails the content of pack.yaml, below the yaml files : 

pack.yaml
```
---
ref: testpack
name: test pack
description: test pack
keywords:
    - test
version: 0.1.0
author: mlalmi.
email: localhost@localhost.local
```
action test.yaml
```
---
name: test
pack: testpack
description: test
runner_type: mistral-v2
entry_point: "workflows/test.yaml"
enabled: true
parameters:
    path:
        type: string
        description: path to displayed file
        required: true
        position: 0
        default: /opt/stackstorm/packs/testpack/pack.yaml
```
workflow test.yaml
```
---
version: '2.0'
name: testpack.test
description: test
workflows:
    main:
        type: direct
        input:
        - path
        tasks:
            show_date:
                action: core.local
                input:
                    cmd: date
                on-success:
                    - show_conf
            show_conf:
                action: core.local
                input:
                    cmd: "tail -vn +1 <% $.path %>"
```

##### EXPECTED RESULTS
according to my example it's expected to see the value "show_conf" for the key "result_task:" in console output, 

##### ACTUAL RESULTS
```
st2 run testpack.test
..
id: 5c45f8374eb8883a50704670
action.ref: testpack.test
parameters: None
status: succeeded
result_task: show_date
result: 
  failed: false
  return_code: 0
  stderr: ''
  stdout: Mon Jan 21 17:50:00 CET 2019
  succeeded: true
start_timestamp: Mon, 21 Jan 2019 16:49:59 UTC
end_timestamp: Mon, 21 Jan 2019 16:50:02 UTC
+--------------------------+------------------------+-----------+------------+--------------------+
| id                       | status                 | task      | action     | start_timestamp    |
+--------------------------+------------------------+-----------+------------+--------------------+
| 5c45f8374eb8883a50704673 | succeeded (1s elapsed) | show_date | core.local | Mon, 21 Jan 2019   |
|                          |                        |           |            | 16:49:59 UTC       |
| 5c45f8384eb8883a50704675 | succeeded (1s elapsed) | show_conf | core.local | Mon, 21 Jan 2019   |
|                          |                        |           |            | 16:50:00 UTC       |
+--------------------------+------------------------+-----------+------------+--------------------+
```
