### ISSUE TITLE
Allow passing in expressions in to do: in orquesta

### ISSUE THREAD

**Issue by dbillor** [StackStorm/st2#4576]
##### SUMMARY
We use a lot of human assisted workflows and we really need the ability to dynamically pass in the next action to be performed in a do: block.

for example

```
post_check_failed:
    action: core.ask
         input:
           schema:
             type: object
             properties:
                retry:
                  type: boolean
                  required: True
                bypass:
                  type: boolean
                  required: True
          next:
            - when: <%  task(post_check_failed).result.response.retry = true %>
              do : perform_post_checks
            - when: <%  task(post_check_failed).result.response.bypass = true %>
              do: disable_module_locators
            - when: <% task(post_check_failed).result.response.bypass = false and task(post_check_failed).result.response.retry = false %>
              do: perform_post_checks

```
I need to repeat this pattern for each task I want to retry like this.  This makes my workflows 2x as long harder to manage and fragile.

Essentially after a task fails i want to be able to go to an inquiry that asks the user if they want to retry task that just failed or if they want to bypass to next step:

so:  do: pause_retry:  "action to retry"  ,  "next action upon bypass"

##### ISSUE TYPE

 - Feature Idea

**Comment by m4dcoder** [comment]
This is an interesting idea. We are going to need some time to figure out how to support this feature. Currently, the workflow definition is translated into a static graph that drives execution so this feature is not easy to implement without rethinking the underlying design concept of if there is an alternative to address your intended use case.

**Comment by dbillor** [comment]
How would you recommend we handle this right now, makes orquesta extremely painful

**Comment by m4dcoder** [comment]
For one thing, you can make the core.action and the input schema into a separate action that you can called instead of having to define the input schema every time.

This is an example st2 action that wraps around a custom inquiry.

```
---
name: "my_custom_ask"
pack: "my_custom_pack"
runner_type: "inquirer"
description: "Action for initiating an Inquiry (usually in a workflow)"
enabled: true
parameters:
  schema:
    default:
      type: object
      properties:
        retry:
          type: boolean
          required: True
        bypass:
          type: boolean
          required: True
```

When the above action is registered, you can call the custom inquiry action w/o specifying the input schema.

```
post_check_failed:
    action: my_custom_pack. my_custom_ask
          next:
            - when: <%  task(post_check_failed).result.response.retry = true %>
              do : perform_post_checks
            - when: <%  task(post_check_failed).result.response.bypass = true %>
              do: disable_module_locators
            - when: <% task(post_check_failed).result.response.bypass = false and task(post_check_failed).result.response.retry = false %>
              do: perform_post_checks
```

Unfortunately, the feature you're asking for isn't going to be easily turned around.  We are focused on getting the current scope to GA in st2 v3.0.
