### ISSUE TITLE
Improve st2client error messages when parameter missing type 

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#4612]
##### SUMMARY

`st2 run` error message when action parameter has undefined `type` is unhelpful. Should be improved.

##### ISSUE TYPE
 - Minor enhancement

##### STACKSTORM VERSION

2.10.4.

##### OS / ENVIRONMENT / INSTALL METHOD

Ansible.

##### STEPS TO REPRODUCE

Create an action that has a parameter with a default value, but no type defined, e.g. `username` in this action:
```yaml
---
  name: "wait_for_ssh"
  runner_type: "python-script"
  description: "Action which waits for a SSH server to become accessible. By default, if no credentials are provided, this action will try to authenticate using the system user username and key file."
  enabled: true
  entry_point: "wait_for_ssh.py"
  parameters:
    hostname:
      description: "Remote hostname."
      type: "string"
      required: true
    port:
      description: "Remote SSH port."
      type: "integer"
      required: true
      default: 22
    username:
      description: "Username used to authenticate."
      required: true
      default: "stanley"
```

If the action is run via CLI without specifying username, it works. If you specify a username, it throws an unhelpful error. 

##### ACTUAL RESULTS

```sh
lhill@st2:~$ st2 run linux.wait_for_ssh hostname="127.0.0.1" port="22" username=stanley
ERROR: 'type'
```

I think there's three options here:

1/ Update st2client to assume that the `type` is `string` if not otherwise specified. That is what the rest of our codebase does.
2/ Update the code around [here](https://github.com/StackStorm/st2/blob/master/st2client/st2client/commands/action.py#L714) to catch this Exception & log a nicer error message
3/ Change action validation rules to enforce specification of `type:` parameter, rather than defaulting to `string`.

I think (1) is the best option, to be consistent with all other usage, and not require user updates to their existing actions. (2) is helpful. (3) should be avoided due to change in behavior requiring widespread re-work.
