### ISSUE TITLE
Feature Request: Honor `secret: true` in output schema in CLI & UI

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#4631]
##### SUMMARY

Action responses marked as `secret` should be masked in CLI & UI, similar to action input parameters masked as secret.

##### ISSUE TYPE
 - Feature Idea

##### STACKSTORM VERSION

`st2 3.0dev (44c4953), on Python 2.7.12`

##### DETAILS

We support [Secrets Masking](https://docs.stackstorm.com/reference/secrets_masking.html), and we now support [Action Output Schema](https://docs.stackstorm.com/latest/actions.html#output-schema). 

[action_output_schema.json](https://github.com/StackStorm/st2/blob/master/st2common/st2common/util/schema/action_output_schema.json#L96) has a flag for `secret`. 

But today that flag doesn't do anything. If our action metadata contains this:

```yaml
output_schema:
  version:
    type: string
    required: true
    secret: true
  executable:
    type: string
    required: true
```

Then running the action produces this output:
```sh
vagrant@ubuntu-xenial:~$ st2 execution get 5ca6dbd90761290dc50f165b
id: 5ca6dbd90761290dc50f165b
status: succeeded (1s elapsed)
parameters: None
result:
  exit_code: 0
  result:
    executable: /opt/stackstorm/virtualenvs/examples/bin/python
    version: 2.7.12
  stderr: ''
  stdout: 'Using Python executable: 2.7.12
    Using Python version: /opt/stackstorm/virtualenvs/examples/bin/python
    '
vagrant@ubuntu-xenial:~$
```

Similarly, in the Web UI, `version` is not masked. 

We should mask this by default in the CLI & Web UI, with `show-secrets`, as a flag available to admin users (similar to the way it works today with input secrets).

This also applies to workflows, the main use case for hiding secrets - e.g. task1 retrieves a secret, which then passes it to task2. That should be masked by default.

**Comment by Kami** [comment]
Thanks for opening this issue (I also wanted to do it, but you beat me to it :)).

**Comment by winem** [comment]
I just verified that this is no longer an issue with st2 v3.5.0. 

The cli output of a midified examples.python_runner_print_python_version execution with `version` being defined as secret in the output_schema: 
```
root@st2-launchdev-u20:/opt/stackstorm/packs/examples/actions# st2 run examples.python_runner_print_python_version
.
id: 613d335206bb9e4cf97a8b05
action.ref: examples.python_runner_print_python_version
context.user: st2admin
parameters: None
status: succeeded
start_timestamp: Sat, 11 Sep 2021 22:53:06 UTC
end_timestamp: Sat, 11 Sep 2021 22:53:06 UTC
result: 
  exit_code: 0
  result:
    version: '********'
  stderr: ''
  stdout:
```

And the corresponding UI output: 
![Selection_287](https://user-images.githubusercontent.com/1457899/132963501-e65c01b5-6765-4b74-90ef-c8d6fc9e4ab3.png)
