### ISSUE TITLE
core.st2.CronTimer runs action on every worker instead of only one

### ISSUE THREAD

**Issue by GuiTeK** [StackStorm/st2#4651]
##### SUMMARY

* We have a StackStorm installation with **2 controllers and 3 workers**, each on a separate machine (AWS EC2 instances).
* We have a trigger rule (C.F. below) which should trigger an action at 5AM UTC everyday.
* The problem is that this action is triggered **3 times** (one time on every worker) **instead of one time in total**.

```yaml
---
pack: 'foo'
name: 'health_check_daily'
description: 'Runs foo.wf-health_check daily at 5 AM UTC'
enabled: true

trigger:
  type: 'core.st2.CronTimer'
  parameters:
    timezone: 'UTC'
    hour: '5'
    minute: '0'
    second: '0'

action:
  ref: 'foo.wf-health_check'
```

##### ISSUE TYPE
Bug Report

##### STACKSTORM VERSION
st2 2.9.3, on Python 2.7.12

##### OS / ENVIRONMENT / INSTALL METHOD
* Custom install on Ubuntu 16.04.5 LTS
* Deployed on AWS EC2 instances
* 2 controllers, 3 workers
* We're using Mistral + Jinja for our workflows

##### STEPS TO REPRODUCE
rules/test_rule.yaml
```yaml
---
pack: 'test-pack'
name: 'test-rule'
description: ''
enabled: true

trigger:
  type: 'core.st2.CronTimer'
  parameters:
    timezone: 'UTC'
    hour: '5'
    minute: '0'
    second: '0'

action:
  ref: 'test-pack.test-action'
```

actions/test_action.yaml
```yaml
---
description: "Test Action"
runner_type: "local-shell-cmd"
enabled: true
entry_point: ''
name: "test-action"
pack: "test-pack"
parameters:
  cmd:
    description: ""
    required: true
    type: "string"
    default: 'echo test'
    immutable: true
```

##### EXPECTED RESULTS
The action should be executed only one time **in total**.

##### ACTUAL RESULTS
The action is executed one time **for each worker**.
