### ISSUE TITLE
Orquesta and st2kv() bug/regression

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#4678]
##### SUMMARY

Orquesta st2kv() behavior changed drastically, making it hard to migrate from Mistral engine.
1. It now throws exception if the specified key doesn't exist in the datastore (previously it would return null). Exceptions seem to be impossible to handle within YAQL/Jinja expressions.
2. Even if the key exists, but has an empty string value, it still throws an exception. See https://github.com/StackStorm/st2/blob/master/contrib/runners/orquesta_runner/orquesta_functions/st2kv.py#L48 - this is not the best option chosen for the if condition, in my humble opinion.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
Paste the output of `st2 --version`:
```
$ st2 --version
st2 3.0.0, on Python 2.7.10
```

##### OS / ENVIRONMENT / INSTALL METHOD
CentOS 6, custom install.

##### STEPS TO REPRODUCE

Meta:
```yaml
---
name: wf_orchestra_test
pack: playground
description: Test
runner_type: orquesta
entry_point: workflows/wf_orchestra_test.yaml
enabled: true
parameters:
  name:
    required: true
    type: string
```
Workflow:
```yaml
---
version: '1.0'
input: 
  - name
tasks:
  task1:
    action: core.noop
    next:
      - when: <% succeeded() %>
        publish:
          - val: <% st2kv('system.' + ctx().name) %>
```

##### EXPECTED RESULTS

`null` published to the `val` variable

##### ACTUAL RESULTS

```
$ st2 run playground.wf_orchestra_test name=ttt
.
id: 5cdc88702db7aa204ea689d9
action.ref: playground.wf_orchestra_test
parameters: 
  name: ttt
status: failed
start_timestamp: Wed, 15 May 2019 16:45:20 CDT
end_timestamp: Wed, 15 May 2019 16:45:21 CDT
result: 
  errors:
  - message: 'YaqlEvaluationException: Unable to evaluate expression ''<% st2kv(''system.'' + ctx().name) %>''. ExpressionEvaluationException: Key system.ttt does not exist in StackStorm datastore.'
    route: 0
    task_id: task1
    task_transition_id: noop__t0
    type: error
  output: null

```

And to illustrate item 2:

```
$ st2 key set ttt ''
+------------------+--------------+
| Property         | Value        |
+------------------+--------------+
| name             | ttt          |
| value            |              |
| scope            | st2kv.system |
| expire_timestamp |              |
+------------------+--------------+
$ st2 key get ttt
+------------------+--------------+
| Property         | Value        |
+------------------+--------------+
| name             | ttt          |
| value            |              |
| secret           | False        |
| encrypted        | False        |
| scope            | st2kv.system |
| expire_timestamp |              |
+------------------+--------------+
$ st2 run playground.wf_orchestra_test name=ttt
.
id: 5cdc88942db7aa204ea689dd
action.ref: playground.wf_orchestra_test
parameters: 
  name: ttt
status: failed
start_timestamp: Wed, 15 May 2019 16:45:56 CDT
end_timestamp: Wed, 15 May 2019 16:45:57 CDT
result: 
  errors:
  - message: 'YaqlEvaluationException: Unable to evaluate expression ''<% st2kv(''system.'' + ctx().name) %>''. ExpressionEvaluationException: Key system.ttt does not exist in StackStorm datastore.'
    route: 0
    task_id: task1
    task_transition_id: noop__t0
    type: error
  output: null
```
