### ISSUE TITLE
Orquesta - Unable to use loop variable in a Jinja for loop

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4701]
##### SUMMARY

When writing a Jinja `for` loop within an Orquesta workflow, the loop variable is inaccessible.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION

```
$ st2 --version
st2 3.0.0, on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
```
OS = Centos 7.6
Install = puppet-st2
```

##### STEPS TO REPRODUCE
Very simple test case is below. This also fails on more complicated places where for loops are used.

`/opt/stackstorm/packs/default/actions/orquesta_jinja_for_loop.yaml`
```yaml
---
name: orquesta_jinja_for_loop
description: A basic sequential workflow.
runner_type: orquesta
entry_point: workflows/orquesta_jinja_for_loop.yaml
enabled: true
parameters: {}
```

`/opt/stackstorm/packs/default/actions/workflows/orquesta_jinja_for_loop.yaml`
```
version: 1.0
  
description: A basic sequential workflow.

vars:
  - ip_routes:
      - host: host1
        routes:
          - a
      - host: host2
        routes:
          - b
      - host: host3
        routes:
          - c

tasks:
  demo:
    action: core.noop
    next:
      - when: "{{ succeeded() }}"
        publish:
          - data: |
              {% for ip_route in ctx().ip_routes %}
              {{ ip_route.host }}
              {% endfor -%}

output:
  - data: "{{ ctx().data }}"
```

##### EXPECTED RESULTS
Workflow to run and produce `data` where each host is on a new line.

##### ACTUAL RESULTS
```
$ st2 run default.orquesta_jinja_for_loop
.
id: 5cf5e5559387ef5a16b63f8a
action.ref: default.orquesta_jinja_for_loop
parameters: None
status: failed
start_timestamp: Tue, 04 Jun 2019 03:28:21 UTC
end_timestamp: Tue, 04 Jun 2019 03:28:22 UTC
result: 
  errors:
  - message: 'JinjaEvaluationException: Unable to evaluate expression ''{{ ip_route.host }}''. UndefinedError: ''ip_route'' is undefined'
    route: 0
    task_id: demo
    task_transition_id: noop__t0
    type: error
  - message: 'JinjaEvaluationException: There are unresolved variables: ctx().data'
    type: error
  output: null
+--------------------------+------------------------+------+-----------+-----------------+
| id                       | status                 | task | action    | start_timestamp |
+--------------------------+------------------------+------+-----------+-----------------+
| 5cf5e5559387ef7ed9bd42a4 | succeeded (1s elapsed) | demo | core.noop | Tue, 04 Jun     |
|                          |                        |      |           | 2019 03:28:21   |
|                          |                        |      |           | UTC             |
+--------------------------+------------------------+------+-----------+-----------------+
```
