### ISSUE TITLE
With enterprise LDAP, retrieve single execution returns 500

### ISSUE THREAD

**Issue by jdmeyer3** [StackStorm/st2#4758]
## SUMMARY

With st2 rbac enterprise enabled and the user is using a custom defined role, retrieving a single execution's result returns a 500 internal server error.

### STACKSTORM VERSION

st2 3.1.0, on Python 2.7.5

##### OS, environment, install method

Kubernetes with custom CentOS image.
BWC enterprise edition

## Steps to reproduce the problem
With BWC enterprise edition installed, put 
```
[auth]
enable = True
backend = ldap
```
in the `/etc/st2/st2.conf` or the `/etc/st2/st2.docker.conf` in the k8s version.

Then in the `/opt/stackstorm/rbac/roles` add the following role
```
---
    name: "custom"
    description: "some custom role"
    enabled: true
    permission_grants:
        -
            permission_types:
               - "api_key_create"
               - "pack_install"
               - "pack_uninstall"
               - "pack_config"
               - "pack_create"
               - "pack_register"
               - "pack_list"
               - "pack_search"
               - "pack_views_index_health"
               - "action_alias_match"
               - "action_alias_help"
               - "action_list"
               - "policy_create"
               - "policy_list"
               - "policy_type_list"
               - "execution_views_filters_list"
               - "execution_list"
               - "stream_view"
               - "inquiry_list"
               - "inquiry_respond"
               - "inquiry_view"
               - "api_key_list"
               - "trace_list"
               - "runner_type_list"
               - "rule_enforcement_list"
               - "webhook_list"
               - "rule_list"
               - "action_alias_list"
               - "sensor_type_list"
               - "trigger_list"
               - "timer_list"
        -
            resource_uid: "pack:packs"
            permission_types:
               - "pack_view"
               - "pack_all"
               - "pack_config"
               - "rule_all"
               - "action_all"
               - "sensor_type_all"
```

In the `/opt/stackstorm/mappings` add a file to map this role to a user
```
---
group: "<some ldap backend that maps to a user>"
description: "grants custom role to a user"
roles:
  - "custom"
```

Apply the rbac settings and login to StackStorm.

Run any action in the packs, then try to expand the output from the history page.

![image](https://user-images.githubusercontent.com/25443446/62571829-9304c000-b84f-11e9-99e9-d0fc0bc1fecb.png)

## Expected Results

The api to return the results of the execution
![image](https://user-images.githubusercontent.com/25443446/62571907-c34c5e80-b84f-11e9-9ecc-15bedc64399c.png)

## Actual Results

In the console, a 500 is returned and a blank page is shown
![image](https://user-images.githubusercontent.com/25443446/62571878-afa0f800-b84f-11e9-8bc6-171fec16e3e0.png)
![image](https://user-images.githubusercontent.com/25443446/62571989-f55dc080-b84f-11e9-9f54-de2402b87cb4.png)
