### ISSUE TITLE
Rule failing to launch an action which has Jinja expression for default action parameter

### ISSUE THREAD

**Issue by dsabsay** [StackStorm/st2#4781]
## SUMMARY

When a Jinja expression is used as the default parameter for an action, the action can be run directly but fails to be launched via a Rule. This appears to only happen when the Rule includes a Jinja expression(s) to pass input to the action.

### STACKSTORM VERSION

Paste the output of ``st2 --version``: st2 2.8.1, on Python 2.7.6

##### OS, environment, install method

Docker from official st2-docker repo.

## Steps to reproduce the problem

Consider an action with a parameter default defined by a Jinja expression that references the pack configuration:

```
---
name: test_default_param_with_rule_chain
pack: test
description: test
enabled: true
entry_point: chains/test_default_param_with_rule_chain.yaml
runner_type: action-chain
parameters:
  another_param:
    type: string
    required: true
  message_list:
    type: array
    required: true
    default: "{{ config_context.messages.list }}"
```

The pack's config file is below:
```
---
messages:
  list:
    - Message from pack config
    - Another message from pack config
```

A Rule used to launch this action:
```
---
name: test_default_param_with_rule
pack: test
description: A Rule that fails to launch the action due to not rendering Jinja in the action's parameter default.
enabled: true
trigger:
  type: test.test_default_param_with_rule_trigger
action:
  ref: test.test_default_param_with_rule_chain
  parameters:
    another_param: "{{ trigger.payload.message }}"
```

The action can be executed directly, i.e. via "st2 run".

But when the Rules Engine attempts to launch the execution, it fails with an error like the following:
```
root@d58bf661f7f5:~# st2 rule-enforcement get 5d6831250c23dd0037246695
+---------------------+--------------------------------------------------------------+
| Property            | Value                                                        |
+---------------------+--------------------------------------------------------------+
| id                  | 5d6831250c23dd0037246695                                     |
| rule.ref            | test.test_default_param_with_rule                            |
| trigger_instance_id | 5d6831250c23dd0037246693                                     |
| execution_id        |                                                              |
| failure_reason      | u'{{ config_context.messages.list }}' is not of type         |
|                     | u'array'                                                     |
|                     |                                                              |
|                     | Failed validating u'type' in                                 |
|                     | schema['properties'][u'message_list']:                       |
|                     |     {u'default': u'{{ config_context.messages.list }}',      |
|                     |      u'required': True,                                      |
|                     |      u'type': u'array'}                                      |
|                     |                                                              |
|                     | On instance[u'message_list']:                                |
|                     |     u'{{ config_context.messages.list }}'                    |
| enforced_at         | 2019-08-29T20:10:13.927126Z                                  |
+---------------------+--------------------------------------------------------------+
```

It appears as though the (unicode) string representing the Jinja expression, u'{{ config_context.messages.list }}', is getting passed as the action parameter. In other words, the Jinja expression isn't getting evaluated.

Oddly, removing the Jinja expression from the Rule fixes the issue. Re-emitting the trigger with the Rule below results in a successful action execution:
```
---
name: test_default_param_with_rule
pack: test
description: A Rule that fails to launch the action due to not rendering Jinja in the action's parameter default.
enabled: true
trigger:
  type: test.test_default_param_with_rule_trigger
action:
  ref: test.test_default_param_with_rule_chain
  parameters:
    another_param: "testing"
```

The problem appears to be that when a Jinja expression is used in a Rule to pass parameters to the action, Jinja expressions that define the action's default parameters are not getting evaluated.

Related issues:

- #4050 may be related. Supposedly resolved in version 2.7.0 but notice that the Rule in that report did not include a Jinja expression for action input.
- #4156 is still open. I suspect this report is reporting the same underlying bug, but can't be sure.

**Comment by dsabsay** [comment]
The error message I showed above turns out to be a red herring...

I realized my Jinja expression in the Rule was probably failing. `"{{ trigger.payload.message }}" is an invalid reference. The proper reference is `"{{ trigger.message }}". So, changing the rule to the following fixes this issue; the rule engine successfully launches executions:
```
---
name: test_default_param_with_rule
pack: test
description: A Rule that fails to launch the action due to not rendering Jinja in the action's parameter default.
enabled: true
trigger:
  type: test.test_default_param_with_rule_trigger
action:
  ref: test.test_default_param_with_rule_chain
  parameters:
    another_param: "{{ trigger.message }}"
```

Changing the Jinja expression to `"{{ trigger.invalid_payload_param }}"` results in the same error in the rule engine as reported above:
```
root@d58bf661f7f5:~# st2 rule-enforcement get 5d684fbf0c23dd0037247311
+---------------------+--------------------------------------------------------------+
| Property            | Value                                                        |
+---------------------+--------------------------------------------------------------+
| id                  | 5d684fbf0c23dd0037247311                                     |
| rule.ref            | test.test_default_param_with_rule                            |
| trigger_instance_id | 5d684fbf0c23dd003724730f                                     |
| execution_id        |                                                              |
| failure_reason      | u'{{ config_context.messages.list }}' is not of type         |
|                     | u'array'                                                     |
|                     |                                                              |
|                     | Failed validating u'type' in                                 |
|                     | schema['properties'][u'message_list']:                       |
|                     |     {u'default': u'{{ config_context.messages.list }}',      |
|                     |      u'required': True,                                      |
|                     |      u'type': u'array'}                                      |
|                     |                                                              |
|                     | On instance[u'message_list']:                                |
|                     |     u'{{ config_context.messages.list }}'                    |
| enforced_at         | 2019-08-29T22:20:47.608804Z                                  |
+---------------------+--------------------------------------------------------------+
```

This error message is **incredibly** misleading. It makes me think the problem is with the rule engine not evaluating the Jinja expression for the default action parameter. Instead, the problem actually seems to be caused by the invalid Jinja expression/reference in the Rule.

This may not qualify as a "bug" under some people's interpretation, but it is certainly an area where the error message was misleading enough to cost me a couple days worth of work to resolve.

**Comment by dsabsay** [comment]
**In summary:**
This is mostly user-error :-) However, the error message given in this scenario is **very** misleading. So, if presented with similar errors, double-check that the Jinja expressions in your Rule are valid.

**Comment by stevemuskiewicz** [comment]
I will confirm what @dsabsay reports here, I just experienced a problem with a rule validation where one of my parameter jinja expressions didn't match the action definition (the parameter was a string called `build_results_url` but in my payload I had `build_result_url` instead).

However the validation error in my `st2rulesengine.log` was instead reporting that _another_ one of my parameters (`build_params` which I had correctly defined and passed in my payload) was not validating, causing me to chase my tail trying to figure out what was wrong with this parameter. 

>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
>     raise error
> ValidationError: u'{{trigger.body.builder_params}}' is not of type u'object'
> 
> Failed validating u'type' in schema['properties'][u'build_params']:
>     {u'description': u'Plexxi Builder parameters for this build',
>      u'required': True,
>      u'type': u'object'}
> 


In this case it was a parameter type of "object" and it wasn't until I tried changing this to "string" that the rule validator then finally reported the validation on the actual parameter that was causing the problem

>   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2reactor/rules/enforcer.py", line 216, in _invoke_action
>     raise validation_exc.ValueValidationException(six.text_type(e))
> ValueValidationException: Failed to render parameter "build_result_url": 'mongoengine.base.datastructures.BaseDict object' has no attribute 'build_result_url' (

So as reported here the validation is incredibly misleading as although it is catching a real issue with the parameter validation, the specific parameter being noted in the exception is not the actual one that is causing the validation to fail, making this very difficult to debug.  It almost seems like something is off by one element in a list somewhere as (maybe coincidentally), the 2 parameters were next to each other in the rule (and action) definitions:

```
    action:
         ref: "MYPACK.build_completed"
         parameters:
            build_spec: "{{trigger.body.build_spec}}"
            build_result_url: "{{trigger.body.build_result_url}}"
            builder_params: "{{ trigger.body.builder_params }}"
            repo_prefix: "{{ trigger.body.repo_prefix | use_none }}"
```
