### ISSUE TITLE
"default" attribute value for action and runner parameters is not validated against parameter schema during content register time

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#4824]
Let's say we have an action metadata definition file which looks like this:

```yaml
parameters:
  cmds:
    description: Array of commands.
    #immutable: true
    type: array
    default: "foo"
...
```

During the register content phase, ``default`` value of that parameter won't be validated against the actual parameter type and schema and register step will succeed without any errors.

This value will only get validated during run time and that's when an error will be thrown if user tries to run that action.

For better end user experience and to go along with important "fail early and fast" mantra, we should also validate ``default`` attribute value for simple values (aka non-Jinja expressions which can only be validated during run time) and fail during content register time if this attribute fails the validation.
