### ISSUE TITLE
Tags filtering is not returning the expected result through the API

### ISSUE THREAD

**Issue by AngryDeveloper** [StackStorm/st2#4828]
**ISSUE TYPE**

Bug Report

**STACKSTORM VERSION**

`st2 3.0dev (367e117), on Python 2.7.12`

**OS / ENVIRONMENT / INSTALL METHOD**

stackstorm-ha helm chart

**SUMMARY**

When trying to filter all the actions based on the tags field an empty list is returned.
For example with the following action definition.

```yaml
---
name: "restart"
runner_type: "local-shell-script"
description: "Restart Gameworld"
enabled: true
entry_point: "webistrano.py"
tags:
  - name: portal-visible
    value: "yes"
parameters:
  gameworld:
    type: "string"
    description: "Enter Gameworld"
    required: true
    position: 0
```

I get this response:

```
GET https://stackstorm/api/v1/actions?tags=portal-visible

HTTP/1.1 200 OK
Server: nginx/1.16.0
Date: Tue, 03 Dec 2019 16:36:29 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
X-Total-Count: 0

[]

Response code: 200 (OK); Time: 97ms; Content length: 2 bytes
```
