### ISSUE TITLE
Rule:  Allow st2kv in criteria, for rules that does not have a payload

### ISSUE THREAD

**Issue by moejarv** [StackStorm/st2#4858]
Currently the criteria in rule always requires a payload. But besides webhook or sensor, there are still other type of rule that can see benefit from criteria. 

If I am setting up a cronjob rule, but only want it to run on the production st2, it would be helpful to allow st2kv inside criteria, so I can write something like this in rule to handle:
`criteria:
  st2kv.system.cronjob_a:
    type: "eq"
    pattern : "enable"
`

Would this be considered as a possible feature?

**Comment by nmaludy** [comment]
Duplicate of #3681

**Comment by moejarv** [comment]
Is it a duplicate? 3681 is about having st2kv in parameter of a crontimer triggered rule, and I am asking about using st2kv as a criteria key.

Imaging this use case, where we use st2 to run build and regress for release branch. This is on cronTimer, and it does not have a payload.

We wish to find a easier way to do code freeze, preferable to stop it at the rule instead of the action. 
This is why we are looking into if we can use st2kv in criteria.

It could look like this: 
```
trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: "UTC"
    day_of_week: "*"
    hour: "*/2"
    minute: 0
    second: 0

criteria:
  st2kv.system.release_branch_freeze:
    type: "eq"
    pattern : false

action:
  ref: devops.build_regress_submit_workflow
```
Does it make it more clear?
