### ISSUE TITLE
st2rulesengine keep high CPU

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2#4888]
## SUMMARY

Provide a quick summary of your bug report.

### STACKSTORM VERSION

Paste the output of ``st2 --version``:  

- st2 3.1.0, on Python 2.7.5

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/
>- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
>- e.g. one-line install, custom install, etc -->

- RHEL 7.6

- installed as instruction right here https://docs.stackstorm.com/install/rhel7.html

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

- define a rule for a webhook
```
---
    name: "sample_rule_with_webhook"
    pack: "mcm_chatops"
    description: "Sample rule dumping webhook payload to a file."
    enabled: true

    trigger:
        type: "core.st2.webhook"
        parameters:
            url: "cem-webhook"

    criteria:
        trigger.headers:
            type: "exists"
            pattern: "Content-Length"

    action:
        ref: "mcm_chatops.cem"
        parameters:
            headers: "{{trigger.headers}}"
            body:    "{{trigger.body}}"

```
- define an action
```
import re
import sys
import json
import requests
from datetime import datetime

from st2common.runners.base_action import Action

class CEMAction(Action):

    def run(self, headers, body):
        print('type(body)')
        print(type(body))
        print(body)

        print('type(headers)')
        print(type(headers))
        print(headers)

        if "eventsURL" in body:
            print(body["eventsURL"])
```
 - and 
```
---
    name: "cem"
    runner_type: "python-script"
    description: "query events from CEM"
    enabled: true
    entry_point: "cem.py"
    parameters:
        headers:
            type: "object"
            required: true
        body:
            type: "object"
            required: true
```
- here is the payload in `raw-pp.json`
```
{
  "correlationDetails": {
    "sourceid": "21494e29-5706-11ea-8197-00000a1a06b5"
  },
  "createdTime": "2020-03-18T05:47:55.558Z",
  "description": "Source ID: 21494e29-5706-11ea-8197-00000a1a06b5",
  "displayId": "#0290-69-0",
  "eventsURL": "https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/events",
  "id": "066d9480-68dc-11ea-b90a-9e92de0ab0d8",
  "incidentURL": "https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8",
  "lastChanged": "2020-03-18T05:49:59.861Z",
  "notificationState": "Notification",
  "owner": "-",
  "priority": 5,
  "state": "closed",
  "summary": "Source ID: 21494e29-5706-11ea-8197-00000a1a06b5",
  "team": "-",
  "timelineURL": "https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/timeline"
}
```
- then generate workload to the webhook
```
while true
do
  curl -k -X POST \
  https://mystackstorm.com/api/v1/webhooks/cem-webhook \
 -H "X-Auth-Token: $token" \
 -H "Content-Type: application/json" \
 --data '@raw-pp.json'
done
```

## Expected Results

What did you expect to happen when running the steps above?

## Actual Results

What happened? What output did you get?

- It takes several seconds for StackStorm to accomplish such a simple action.

```
st2 execution list --action mcm_chatops.cem --last 10
+--------------------------+-----------------+--------------+------------------------+----------------------+------------------+
| id                       | action.ref      | context.user | status                 | start_timestamp      | end_timestamp    |
+--------------------------+-----------------+--------------+------------------------+----------------------+------------------+
| 5e71db35b180db753e45c36b | mcm_chatops.cem | root         | succeeded (3s elapsed) | Wed, 18 Mar 2020     | Wed, 18 Mar 2020 |
|                          |                 |              |                        | 08:26:28 UTC         | 08:26:31 UTC     |
| 5e71db35b180db753e45c36c | mcm_chatops.cem | root         | succeeded (4s elapsed) | Wed, 18 Mar 2020     | Wed, 18 Mar 2020 |
|                          |                 |              |                        | 08:26:28 UTC         | 08:26:32 UTC     |
| 5e71db35b180db753e45c36f | mcm_chatops.cem | root         | running (4s elapsed)   | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:28 UTC         |                  |
| 5e71db35b180db753e45c374 | mcm_chatops.cem | root         | running (3s elapsed)   | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:29 UTC         |                  |
| 5e71db36b180db753e45c378 | mcm_chatops.cem | root         | running (3s elapsed)   | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:29 UTC         |                  |
| 5e71db36b180db753e45c37c | mcm_chatops.cem | root         | running (3s elapsed)   | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:29 UTC         |                  |
| 5e71db36b180db753e45c382 | mcm_chatops.cem | root         | running (2s elapsed)   | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:30 UTC         |                  |
| 5e71db37b180db753e45c385 | mcm_chatops.cem | root         | scheduled              | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:30 UTC         |                  |
| 5e71db37b180db753e45c391 | mcm_chatops.cem | root         | requested              | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:31 UTC         |                  |
| 5e71db38b180db753e45c393 | mcm_chatops.cem | root         | requested              | Wed, 18 Mar 2020     |                  |
|                          |                 |              |                        | 08:26:31 UTC         |                  |
+--------------------------+-----------------+--------------+------------------------+----------------------+------------------+
+------------------------------------------------------------------------------------------------------------------------------+
| Note: Only first 10 action executions are displayed. Use -n/--last flag for more results.                                    |
+------------------------------------------------------------------------------------------------------------------------------+
```

- and CPU usage are kept exhausted on 8 CPUs

<img width="1565" alt="截屏2020-03-1816 14 16" src="https://user-images.githubusercontent.com/606882/76940656-a0317380-6935-11ea-821a-99abc22b0e4c.png">

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

Here is my `/etc/st2/st2.conf`

```
# System-wide configuration

[api]
# Host and port to bind the API server.
host = 127.0.0.1
port = 9101
logging = /etc/st2/logging.api.gunicorn.conf
mask_secrets = True
# allow_origin is required for handling CORS in st2 web UI.
# allow_origin = http://myhost1.example.com:3000,http://myhost2.example.com:3000

[stream]
logging = /etc/st2/logging.stream.gunicorn.conf

[sensorcontainer]
logging = /etc/st2/logging.sensorcontainer.conf

[rulesengine]
logging = /etc/st2/logging.rulesengine.conf

[actionrunner]
logging = /etc/st2/logging.actionrunner.conf
virtualenv_opts =
workflows_pool_size = 8
actions_pool_size = 8

[resultstracker]
logging = /etc/st2/logging.resultstracker.conf

[notifier]
logging = /etc/st2/logging.notifier.conf

[exporter]
logging = /etc/st2/logging.exporter.conf

[garbagecollector]
logging = /etc/st2/logging.garbagecollector.conf

[timersengine]
logging = /etc/st2/logging.timersengine.conf

[auth]
#host = 127.0.0.1
host = mystackstorm.com
port = 9100
use_ssl = True
debug = False
enable = True
logging = /etc/st2/logging.auth.gunicorn.conf
# Note: Settings below are only used in "standalone" mode
backend = flat_file
backend_kwargs = {"file_path": "/etc/st2/htpasswd"}
#backend = pam
#backend_kwargs = {"service": "login"}
cert = /root/StackStorm/cacert/integrationca.crt
key =  /root/StackStorm/cacert/integrationca.key

# Base URL to the API endpoint excluding the version (e.g. http://myhost.net:9101/)
api_url = https://mystackstorm.com/api/

[system]
base_path = /opt/stackstorm

[webui]
# webui_base_url = https://mywebhost.domain
webui_base_url=https://mystackstorm.com

[syslog]
host = 127.0.0.1
port = 514
facility = local7
protocol = udp

[log]
excludes = requests,paramiko
redirect_stderr = False
mask_secrets = True

[system_user]
user = root
ssh_key_file = /home/stanley/.ssh/id_rsa

[messaging]
url = amqp://guest:guest@127.0.0.1:5672/

[ssh_runner]
remote_dir = /tmp

[workflow_engine]
logging = /etc/st2/logging.workflowengine.conf

[scheduler]
logging = /etc/st2/logging.scheduler.conf

[keyvalue]
encryption_key_path = /etc/st2/keys/datastore_key.json
```

**Comment by dove-young** [comment]
Here is one of its `trigger_instance` and `execution`.  It really takes 3 seconds to accomplish such as simple action, which merely print some object type. 

- action content

```
class CEMAction(Action):

    def run(self, headers, body):
        print('type(body)')
        print(type(body))
        print(body)

        print('type(headers)')
        print(type(headers))
        print(headers)

        if "eventsURL" in body:
            print(body["eventsURL"])
```

- trigger_instance

```
st2 trigger-instance get 5e722262a96d9c1ae3120017
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 5e722262a96d9c1ae3120017                                     |
| trigger         | core.st2.generic.actiontrigger                               |
| occurrence_time | 2020-03-18T13:30:10.000000Z                                  |
| payload         | {                                                            |
|                 |     "status": "succeeded",                                   |
|                 |     "start_timestamp": "2020-03-18 13:29:57.061049+00:00",   |
|                 |     "parameters": {                                          |
|                 |         "body": {                                            |
|                 |             "correlationDetails": {                          |
|                 |                 "sourceid":                                  |
|                 | "21494e29-5706-11ea-8197-00000a1a06b5"                       |
|                 |             },                                               |
|                 |             "description": "Source ID:                       |
|                 | 21494e29-5706-11ea-8197-00000a1a06b5",                       |
|                 |             "lastChanged": "2020-03-18T05:49:59.861Z",       |
|                 |             "timelineURL":                                   |
|                 | "https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-   |
|                 | 9e92de0ab0d8/timeline",                                      |
|                 |             "owner": "-",                                    |
|                 |             "incidentURL":                                   |
|                 | "https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-   |
|                 | 9e92de0ab0d8",                                               |
|                 |             "summary": "Source ID:                           |
|                 | 21494e29-5706-11ea-8197-00000a1a06b5",                       |
|                 |             "priority": 5,                                   |
|                 |             "createdTime": "2020-03-18T05:47:55.558Z",       |
|                 |             "state": "closed",                               |
|                 |             "notificationState": "Notification",             |
|                 |             "team": "-",                                     |
|                 |             "displayId": "#0290-69-0",                       |
|                 |             "id": "066d9480-68dc-11ea-b90a-9e92de0ab0d8",    |
|                 |             "eventsURL":                                     |
|                 | "https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-   |
|                 | 9e92de0ab0d8/events"                                         |
|                 |         },                                                   |
|                 |         "headers": {                                         |
|                 |             "X-Request-Id":                                  |
|                 | "7f1f6fd3-8566-4c09-85e1-c1c66690444c",                      |
|                 |             "X-Forwarded-For": "myhost_ip",                |
|                 |             "Content-Length": "761",                         |
|                 |             "Accept": "*/*",                                 |
|                 |             "User-Agent": "curl/7.29.0",                     |
|                 |             "Host": "myhost_ip,myhost_ip",               |
|                 |             "X-Real-Ip": "myhost_ip",                      |
|                 |             "X-Subscription-Id": "id-mycluster-account",     |
|                 |             "X-Auth-Token":                                  |
|                 | "mytoken",                          |
|                 |             "Content-Type": "application/json"               |
|                 |         }                                                    |
|                 |     },                                                       |
|                 |     "runner_ref": "python-script",                           |
|                 |     "action_name": "mcm_chatops.cem",                        |
|                 |     "result": {                                              |
|                 |         "stdout": "type(body)                                |
|                 | <class 'dict'>                                               |
|                 | {'displayId': '#0290-69-0', 'correlationDetails':            |
|                 | {'sourceid': '21494e29-5706-11ea-8197-00000a1a06b5'},        |
|                 | 'description': 'Source ID:                                   |
|                 | 21494e29-5706-11ea-8197-00000a1a06b5', 'lastChanged':        |
|                 | '2020-03-18T05:49:59.861Z', 'team': '-', 'incidentURL':      |
|                 | 'https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-   |
|                 | 9e92de0ab0d8', 'summary': 'Source ID:                        |
|                 | 21494e29-5706-11ea-8197-00000a1a06b5', 'priority': 5,        |
|                 | 'createdTime': '2020-03-18T05:47:55.558Z', 'state':          |
|                 | 'closed', 'notificationState': 'Notification',               |
|                 | 'timelineURL': 'https://example.com/api/query/v1/066d9480    |
|                 | -68dc-11ea-b90a-9e92de0ab0d8/timeline', 'owner': '-', 'id':  |
|                 | '066d9480-68dc-11ea-b90a-9e92de0ab0d8', 'eventsURL':         |
|                 | 'https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-   |
|                 | 9e92de0ab0d8/events'}                                        |
|                 | type(headers)                                                |
|                 | <class 'dict'>                                               |
|                 | {'X-Request-Id': '7f1f6fd3-8566-4c09-85e1-c1c66690444c', 'X  |
|                 | -Forwarded-For': 'myhost_ip', 'Content-Length': '761',     |
|                 | 'Accept': '*/*', 'User-Agent': 'curl/7.29.0', 'Host':        |
|                 | 'myhost_ip,myhost_ip', 'X-Real-Ip': 'myhost_ip', 'X    |
|                 | -Subscription-Id': 'id-mycluster-account', 'X-Auth-Token':   |
|                 | '2a1ad439e5034721a6a7b67eaad7ef44', 'Content-Type':          |
|                 | 'application/json'}                                          |
|                 | https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-    |
|                 | 9e92de0ab0d8/events                                          |
|                 | ",                                                           |
|                 |         "result": null,                                      |
|                 |         "stderr": "",                                        |
|                 |         "exit_code": 0                                       |
|                 |     },                                                       |
|                 |     "action_ref": "mcm_chatops.cem",                         |
|                 |     "execution_id": "5e722255a96d9c1ae311ff80"               |
|                 | }                                                            |
| status          | processed                                                    |
+-----------------+--------------------------------------------------------------+
```

- execution record

```
st2 execution get 5e722255a96d9c1ae311ff80
id: 5e722255a96d9c1ae311ff80
status: succeeded (3s elapsed)
parameters:
  body:
    correlationDetails:
      sourceid: 21494e29-5706-11ea-8197-00000a1a06b5
    createdTime: '2020-03-18T05:47:55.558Z'
    description: 'Source ID: 21494e29-5706-11ea-8197-00000a1a06b5'
    displayId: '#0290-69-0'
    eventsURL: https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/events
    id: 066d9480-68dc-11ea-b90a-9e92de0ab0d8
    incidentURL: https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8
    lastChanged: '2020-03-18T05:49:59.861Z'
    notificationState: Notification
    owner: '-'
    priority: 5
    state: closed
    summary: 'Source ID: 21494e29-5706-11ea-8197-00000a1a06b5'
    team: '-'
    timelineURL: https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/timeline
  headers:
    Accept: '*/*'
    Content-Length: '761'
    Content-Type: application/json
    Host: my_host_ip,my_host_ip
    User-Agent: curl/7.29.0
    X-Auth-Token: my_token
    X-Forwarded-For: my_host_ip
    X-Real-Ip: my_host_ip
    X-Request-Id: 7f1f6fd3-8566-4c09-85e1-c1c66690444c
    X-Subscription-Id: id-mycluster-account
result:
  exit_code: 0
  result: null
  stderr: ''
  stdout: 'type(body)
    <class ''dict''>
    {''displayId'': ''#0290-69-0'', ''correlationDetails'': {''sourceid'': ''21494e29-5706-11ea-8197-00000a1a06b5''}, ''description'': ''Source ID: 21494e29-5706-11ea-8197-00000a1a06b5'', ''lastChanged'': ''2020-03-18T05:49:59.861Z'', ''team'': ''-'', ''incidentURL'': ''https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8'', ''summary'': ''Source ID: 21494e29-5706-11ea-8197-00000a1a06b5'', ''priority'': 5, ''createdTime'': ''2020-03-18T05:47:55.558Z'', ''state'': ''closed'', ''notificationState'': ''Notification'', ''timelineURL'': ''https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/timeline'', ''owner'': ''-'', ''id'': ''066d9480-68dc-11ea-b90a-9e92de0ab0d8'', ''eventsURL'': ''https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/events''}
    type(headers)
    <class ''dict''>
    {''X-Request-Id'': ''7f1f6fd3-8566-4c09-85e1-c1c66690444c'', ''X-Forwarded-For'': ''my_host_ip'', ''Content-Length'': ''761'', ''Accept'': ''*/*'', ''User-Agent'': ''curl/7.29.0'', ''Host'': ''my_host_ip,my_host_ip'', ''X-Real-Ip'': ''my_host_ip'', ''X-Subscription-Id'': ''id-mycluster-account'', ''X-Auth-Token'': ''2a1ad439e5034721a6a7b67eaad7ef44'', ''Content-Type'': ''application/json''}
    https://example.com/api/query/v1/066d9480-68dc-11ea-b90a-9e92de0ab0d8/events
    '
```
