### ISSUE TITLE
Does workflow scheme support custom field?such as label,output

### ISSUE THREAD

**Issue by wcc526** [StackStorm/st2#4906]
```
---
name: aq_detect
description: xxx
runner_type: orquesta
entry_point: workflows/aq_detect.yaml
enabled: true
parameters:
  target:
    type: "string" 
    required: true
    description: xx
```

add custom label,and results

```
---
labels: xxx
results:
  output:
    type: "string" 
    required: true
    description: xx
```
