### ISSUE TITLE
Orquesta vars can no longer contain '.' in 3.2

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4932]
## SUMMARY

In StackStorm 3.2, if an Orquesta workflow contains a `.` in any of its `vars` (ie context) then the workflow will fail to run with an error:
```shell
$ st2 run default.orquesta_vars_with_periods.
id: 5eac3faeca07c849e9b4f280
action.ref: default.orquesta_vars_with_periods
parameters: None
status: failed
start_timestamp: Fri, 01 May 2020 15:26:38 UTC
end_timestamp: Fri, 01 May 2020 15:26:38 UTC
result: 
  errors:
  - message: key 'with.period' must not contain '.'
  output: null
```

### STACKSTORM VERSION

```shell
$ st2 --version
st2 3.2.0, on Python 2.7.5
```

##### OS, environment, install method

```shell
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.8 (Maipo)

# install method = puppet-st2
```

## Steps to reproduce the problem

/opt/stackstorm/packs/default/actions/orquesta_vars_with_periods.yaml 
```yaml
---
description: "Demos bug with orquesta vars with periods"
enabled: true
runner_type: orquesta
entry_point: workflows/orquesta_vars_with_periods.yaml
name: orquesta_vars_with_periods
pack: default
parameters:
  demo:
    type: string
    default: "demo"
```

/opt/stackstorm/packs/default/actions/workflows/orquesta_vars_with_periods.yaml 
```
---
version: 1.0

description: "Demos bug with orquesta vars with periods"

input:
  - demo

vars:
  - myvar.with.period: 'this line is going to cause an error'

tasks:
  dispatch:
    action: core.noop
```

Register and run the action
```shell
$ st2 action create /opt/stackstorm/packs/default/actions/orquesta_vars_with_periods.yaml 
$ st2 run default.orquesta_vars_with_periods
.
id: 5eac47b9ca07c849e9b4f289
action.ref: default.orquesta_vars_with_periods
parameters: None
status: failed
start_timestamp: Fri, 01 May 2020 16:00:57 UTC
end_timestamp: Fri, 01 May 2020 16:00:58 UTC
result: 
  errors:
  - message: key 'myvar.with.period' must not contain '.'
  output: null
```

## Expected Results

Workflow runs without error

## Actual Results

Workflow errors trying to write state to the database
