### ISSUE TITLE
how to run linux.netstat action with arguments

### ISSUE THREAD

**Issue by scguoi** [StackStorm/st2#4946]
**PLEASE READ**: If you are a paid Extreme Workflow (EWC) customer, please contant [Extreme
Network GTAC](https://gtacknowledge.extremenetworks.com/articles/How_To/How-to-contact-Extreme-Networks-Global-Technical-Assistance-Center-GTAC)
or send an email to support@stackstorm.com

For free community support, please use out forum at [https://forum.stackstorm.com](https://forum.stackstorm.com)

I try to run linux.netstat action with args, but result are error as follow.

$ st2 run linux.netstat hosts=172.31.114.68 args="-antp"
ERROR: 'type'

**Comment by Sheshagiri** [comment]
looks like `type` attribute is missing for `netstat` action. I hope #4947 will fix that permanently. 

In the meantime, you can add the type attribute and re-register the Linux pack and that should fix the issue.
update `/opt/stackstorm/packs/linux/actions/netstat.yaml` to
```
---
  name: "netstat"
  runner_type: "remote-shell-cmd"
  description: "Run netstat"
  enabled: true
  entry_point: ""
  parameters:
    cmd:
      immutable: true
      default: "netstat {{args}}"
    args:
      description: "Command line arguments"
      default: " "
      type: "string"
``` 
and re-register the Linux pack using the following command
```bash
st2 pack register linux
```
This should resolve the issue for you.
