### ISSUE TITLE
Orquesta's sub-workflow is the type of 'with', it can not work normally

### ISSUE THREAD

**Issue by Jooseph** [StackStorm/st2#4950]
## SUMMARY

The process cannot continue. 
The sub-workflow is the type of 'with', and it have inquiry task. when i response all inquiry, the sub-workflow’s status is still paused.

### STACKSTORM VERSION

Paste the output of ``st2 --version``: 
st2 3.1.0, on Python 2.7.6

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

docker, from https://github.com/StackStorm/st2-docker

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

### workflow

```yaml
version: 1.0

input:
  - inputA:

vars:
  - listA: [{"a": 1},{"a": 2},{"a": 3},{"a": 4}]
  - summary:

tasks:
  subWorkflow:
    with:
      items: <% ctx().listA %>
    action: default.sub-test
    input:
      inputA: <% item() %>
    next:
      - do: echoTask
        publish:
          - summary: <% result().output %>

  echoTask:
    action: core.echo
    input:
      message: "test"
```

### sub workflow
```yaml
version: 1.0

input:
  - inputA

tasks:
  wait:
    action: core.local
    input:
      cmd: sleep 2
    next:
      - do: ask

  ask:
    action: core.ask

output:
  - inputA: <% ctx().inputA %>
```

1. run the workflow
2. when it created 4 inquiry , use postman response inquiries at the same time.(The time difference is very small)

## Expected Results

What did you expect to happen when running the steps above?

`subWorkflow` and `echoTask` should be succeeded.

## Actual Results

What happened? What output did you get?

![image](https://user-images.githubusercontent.com/14209724/81905740-b8e99d00-95f7-11ea-8f3a-0f4cdd3217f9.png)

the workflow status is still paused. the `echoTask` is not running

**Comment by guzzijones** [comment]
Do you have the redis coordinator service installed?  That fixed it for me.

**Comment by Jooseph** [comment]
No, it not installed. stackstorm is running in docker, from https://github.com/StackStorm/st2-docker

**Comment by Jooseph** [comment]
That sounds pretty good. But i see https://github.com/StackStorm/st2-docker is deprecated. Would you create a new repository to Maintain Docker project?

**Comment by armab** [comment]
Current `st2-docker` is deprecated and will be replaced with another working blueprint.
However even old `st2-docker` deployment had `redis` as a coordination backend: https://github.com/StackStorm/st2-docker/blob/master/docker-compose.yml#L63

**Comment by Jooseph** [comment]
My local `st2-docker` current commit id is `2c20325`.
And I check the `docker-compose.yml`, it defined redis service.

**Comment by Jooseph** [comment]
Is not work for centos too. 

`action.with` is  the concurrent executions ?

I have configured the parameters based on the docs https://docs.stackstorm.com/reference/policies.html?highlight=redis

## SUMMARY

The process cannot continue. 
The sub-workflow is the type of 'with', and it have inquiry task. when i response all inquiry(The time difference is very small), the workflow’s status is still paused, the workflow not continue to run.

### STACKSTORM VERSION

Paste the output of ``st2 --version``: 
st2 3.2.0, on Python 2.7.5

##### OS, environment, install method

OS:  ``cat /etc/redhat-release``
CentOS Linux release 7.7.1908 (Core)

env: 

rabbitmq
`docker run -d -p 5672:5672 rabbitmq:3.6-management`

mongodb
`docker run -d -p 27017:27017 mongo:4.0`

postgres
`docker run -d -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:9.6`

redis
`docker run -d -p 6379:6379 redis:4.0 redis-server`

install method
https://docs.stackstorm.com/install/rhel7.html
https://docs.stackstorm.com/reference/policies.html?highlight=redis

st2.conf
```
[messaging]
url = amqp://guest:guest@127.0.0.1:5672/

[database]
host = mongodb://username:password@127.0.0.1:27017/st2?authSource=admin

[coordination]
url = redis://:password@127.0.0.1:6379
```

mistral.conf
```
[DEFAULT]
transport_url = rabbit://guest:guest@127.0.0.1:5672
[database]
connection = postgresql+psycopg2://mistral:StackStorm@localhost/mistral
```

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

### workflow

```yaml
version: 1.0

input:
  - inputA:

vars:
  - listA: [{"a": 1},{"a": 2},{"a": 3},{"a": 4}]
  - summary:

tasks:
  subWorkflow:
    with:
      items: <% ctx().listA %>
    action: default.sub-test
    input:
      inputA: <% item() %>
    next:
      - do: echoTask
        publish:
          - summary: <% result().output %>

  echoTask:
    action: core.echo
    input:
      message: "test"
```

### sub workflow
```yaml
version: 1.0

input:
  - inputA

tasks:
  wait:
    action: core.local
    input:
      cmd: sleep 2
    next:
      - do: ask

  ask:
    action: core.ask

output:
  - inputA: <% ctx().inputA %>
```

1. run the workflow
2. when it created 4 inquiry , use postman response inquiries at the same time.(The time difference is very small)

## Expected Results

What did you expect to happen when running the steps above?

`subWorkflow` and `echoTask` should be succeeded.

## Actual Results

What happened? What output did you get?

![image](https://user-images.githubusercontent.com/14209724/81905740-b8e99d00-95f7-11ea-8f3a-0f4cdd3217f9.png)

the workflow status is still paused. the `echoTask` is not running
