### ISSUE TITLE
how to get the a key value from an object?

### ISSUE THREAD

**Issue by nieyong1** [StackStorm/st2#4961]
## SUMMARY

how to get the a key value from an object?

### STACKSTORM VERSION
st2 3.2.0 on python 2.7.5

##### OS, environment, install method
 one-line install on centos 7

## Steps to reproduce the problem
I create a workflow like below. The input type of alert is object and I can't get the value of key 'status'.
```
version: 1.0
description: A ads workflow that handles webhook request alerts.
input:
  - alert
tasks:
  task1:
    action: core.echo message=<% ctx(alert).get('status') %>
```
## Actual Results

id: 5ed6fda8e2e0e298277380c1
action.ref: application_ads.application_ads_webhook
parameters: 
  alert:
    '''annotations''':
      '''description''': '''[Level: critical] Env: Prod, Jenkins Job: mwc_monitor/Prod_Tomcat_mscpro failed!'''
      '''summary''': '''[Level: critical] Env: Prod, Jenkins Job: mwc_monitor/Prod_Tomcat_mscpro failed!'''
    '''endsAt''': '''0001-01-01T00:00:00Z'''
    '''fingerprint''': '''15bcf5534ca45a9a'''
    '''generatorURL''': '''http://kwetst200001:9090/graph?g0.expr=avg_over_time%28default_jenkins_builds_last_build_result%7Bjenkins_job%3D%22mwc_monitor%2FProd_Tomcat_mscpro%22%2Crepo%3D%22NA%22%7D%5B30m%5D%29+%3C+0.5&g0.tab=1'''
    '''labels''':
      '''Lvl''': '''critical'''
      '''alertname''': '''prodTomcatAlert'''
      '''app''': '''mwc'''
      '''env''': '''Beta'''
      '''exporter''': '''jenkins'''
      '''instance''': '''kwetjks00001:8080'''
      '''jenkins_job''': '''mwc_monitor/Prod_Tomcat_mscpro'''
      '''job''': '''jenkins'''
      '''object_class''': '''avalability'''
      '''object_domain''': '''application'''
      '''object_subdomain''': '''ads'''
      '''repo''': '''NA'''
      '''site''': '''kwe'''
      '''subapp''': '''jenkins'''
    '''startsAt''': '''2020-05-29T09:25:21.982006478+08:00'''
    '''status''': '''firing'''
status: failed (1s elapsed)
start_timestamp: Wed, 03 Jun 2020 01:32:24 UTC
end_timestamp: Wed, 03 Jun 2020 01:32:25 UTC
result: 
  errors:
  - message: "ValidationError: None is not of type u'string'

Failed validating u'type' in schema['properties'][u'message']:
    {u'description': u'The message that the command will echo.',
     u'required': True,
     u'type': u'string'}

On instance[u'message']:
    None"
    route: 0
    task_id: task1
    type: error
  output: null

Thanks!

**Comment by mickmcgrath13** [comment]
assuming the action's metadata file looks something like this:
```
---
name: alert
runner_type: orquesta
entry_point: workflows/alert.yaml
enabled: true
parameters:
  status:
    type: object
```

Then, your workflow should look something like this:
```
version: 1.0
input:
  - status
tasks:
  task1:
    action: core.echo message=<% ctx().status %>
```

(note the defined `input:` in the workflow)
