### ISSUE TITLE
Rule criteria doesn't work with custom header

### ISSUE THREAD

**Issue by makandre** [StackStorm/st2#4995]
## SUMMARY

The doc states:

> If the criteria key contains any special characters (like -) then use the dictionary lookup format for specifying the criteria key. In case of a webhook based rule it is typical for the header of the posted event to contain such values:

> criteria:
    trigger.headers['X-Custom-Header']:
        type: "eq"
        pattern : "customvalue"

So I was trying a rule to receive a simple GitHub issues webhook, with the criteria defined like so:

![image](https://user-images.githubusercontent.com/17596240/87745708-ab4dc080-c7bc-11ea-8ba7-124c7c1dd40c.png)

But the rule is not run.

I know I have defined the webhook correctly, because if I changed the criteria to something else, like `trigger.body.action eq opened`, it works.

### STACKSTORM VERSION

Paste the output of ``st2 --version``: 
`st2 3.3dev (201c05882), on Python 3.6.9`

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
- e.g. one-line install, custom install, etc -->

Installed on Kubernetes cluster using Helm

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

- I have GitHub pack installed
- create a rule:
  - webhook trigger w/ url = `github`
  - criteria (as above)
  - action set to `github.add_comment`

## Expected Results

What did you expect to happen when running the steps above?

Rule runs the action upon receiving an issues webhook from GitHub

## Actual Results

What happened? What output did you get?

Nothing runs

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by amanda11** [comment]
I have managed to get this to work on a StackStorm 3.3 system with python 2. Example rule

```
---
  name: "test_webhook"
  enabled: true
  pack: amanda
  description: "Test hook"

  trigger:
    type: "core.st2.webhook"
    parameters:
       url: sampleamanda

  criteria:
    trigger.headers['X-Parse-Application-Id']:
      type: 'eq'
      pattern: 'hello'

  action:
    ref: core.echo
    parameters:
      message: 'Found header'
```

Tested with curl:
curl -H "St2-Api-Key: <key>" -k -H 'content-type: application/json' -H "X-Parse-Application-Id: hello" -d '{"arg1":"HELLOAMANDA"}' https://127.0.0.1/api/v1/webhooks/sampleamanda
