### ISSUE TITLE
Web Hook Rules check http headers in case sensitive manner

### ISSUE THREAD

**Issue by amanda11** [StackStorm/st2#4998]
## SUMMARY

The case used for the header name in trigger.headers[<headername>] in a web-hook rule is treated in a case sensitive manner. HTTP headers are case insensitive so the case of the name in the headers should not e relevant.

### STACKSTORM VERSION

3.2.0

##### OS, environment, install method

Seen on one-line install and HA

## Steps to reproduce the problem

See https://github.com/StackStorm/st2/issues/4995 for initial case.
1. Configure webhookrule with trigger.headers['X-GitHub-Event']
2. Send in header via curl of X-GitHub-Event to webhook
3. Rule doesn't match
4. Change rule to be trigger.headers['X-Github-Event'] - rule matches

## Expected Results

As http headers are case insensitive then it should not matter what case is used in the rule. Therefore no matter what case header is or case of rule then they should match.

## Actual Results

Only matched when rule defined as X-Github-Event

**Comment by amanda11** [comment]
@armab Issue raised as discussed. I can take a look at a PR fix for this.

**Comment by nmaludy** [comment]
Someone brought up this problem in slack today, so i started looking into it.

The hard part that i see is around backwards compatability. If someone has already written a rule with a criteria:

```yaml
trigger.headers['X-Github-Token']:
        type: "eq"
        pattern : "customvalue"
```

We need to provide this same key to them. The trigger instance itself is just a JSON blob and we used `jsonpath_rw` to render the key's expression into a value.

- https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/rules/filter.py#L140
- https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/rules/filter.py#L86
- https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/rules/filter.py#L31
- https://github.com/StackStorm/st2/blob/master/st2common/st2common/util/payload.py#L34-L39
- https://github.com/StackStorm/st2/blob/master/st2common/st2common/util/payload.py#L17

**Idea 1**
One thought i had on how to fix or workaround this and still provide backwards compatability:

In the webhook trigger instances we could return another parameter that is the exact same `headers` dictionary but with all of the keys set to lowercase, maybe call it something like `headers_lower` and then your code would look like: 
```yaml
trigger.headers_lower['x-github-token']:
        type: "eq"
        pattern : "customvalue"
```

**Idea 2**
My other thought would be to use some other expression language (Jinja, etc) to allow some more complex expressions so we can manipulate the header keys. Maybe providing a custom filter `dict_lower_keys` that takes a dictionary as input and returns a dictionary with all of the keys lowercased as output, example:

```yaml
"{{ (trigger.headers | dict_lower_keys)['x-github-token'] }}":
        type: "eq"
        pattern : "customvalue"
```

I think this would take a decent amount of work though in order to detect if the expression is Jinja or not and then render it properly. Might be useful in some other scenarios though?
