### ISSUE TITLE
Can't run example workflow

### ISSUE THREAD

**Issue by pavanfhw** [StackStorm/st2#5122]
I'm using StackStorm in k8s using [stackstorm-ha](https://github.com/StackStorm/stackstorm-ha) with all images on v 3.3.0

`st2 --version` inside client container:
st2 3.3.0, on Python 3.6.9

I'm trying to run a simple workflow using the examples: [action](https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/orquesta-ask-basic.yaml) and [workflow](https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/workflows/orquesta-ask-basic.yaml)

Trying to run the action gives the result:

```
id: 600b3ab84e0a1611ae30f7e8
action.ref: default.test-workflow
parameters: None
status: failed
start_timestamp: Fri, 22 Jan 2021 20:51:04 UTC
end_timestamp: Fri, 22 Jan 2021 20:51:08 UTC
result: 
  errors:
  - message: Execution failed. See result for details.
    task_id: start
    type: error
  - message: 'JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)'
    route: 0
    task_id: start
    type: error
  output: null
+--------------------------+------------------------+-------+-----------+-------------------------------+
| id                       | status                 | task  | action    | start_timestamp               |
+--------------------------+------------------------+-------+-----------+-------------------------------+
| 600b3ab94d953208ca22ac99 | succeeded (1s elapsed) | start | core.echo | Fri, 22 Jan 2021 20:51:05 UTC |
+--------------------------+------------------------+-------+-----------+-------------------------------+

```

I'm not being able to find the reason. The only error is `JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)`. I'm not even sure what file causes the JSONDecodeError

**Comment by armab** [comment]
I remember similar issue was fixed recently but can you try `3.4dev` images to verify if the bug still present?
We'll be releasing StackStorm 3.4 version soon.

**Comment by pavanfhw** [comment]
Ok, will try and return with the results

**Comment by pavanfhw** [comment]
The reulst is the same:

`$ st2 --version`:
st2 3.4dev (c422f0029), on Python 3.6.9

`$ st2 run linux.orquesta-ask-basic`

```
id: 600ed1c26f65155410d948f2
action.ref: default.orquesta-ask-basic
parameters: None
status: failed
start_timestamp: Mon, 25 Jan 2021 14:12:18 UTC
end_timestamp: Mon, 25 Jan 2021 14:12:19 UTC
result: 
  errors:
  - message: Execution failed. See result for details.
    task_id: start
    type: error
  - message: 'JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)'
    route: 0
    task_id: start
    type: error
  output: null
+--------------------------+------------------------+-------+-----------+-------------------------------+
| id                       | status                 | task  | action    | start_timestamp               |
+--------------------------+------------------------+-------+-----------+-------------------------------+
| 600ed1c21015ce2be3072a61 | succeeded (0s elapsed) | start | core.echo | Mon, 25 Jan 2021 14:12:18 UTC |
+--------------------------+------------------------+-------+-----------+-------------------------------+
```
