### ISSUE TITLE
Support Vault as a backend for st2kv

### ISSUE THREAD

**Issue by cydergoth** [StackStorm/st2#5401]
Vault is an easy sell as a verified secure KV store in high security environments. It would be nice to be able to use a Vault deployment as a backend for st2kv.

**Comment by chris3081** [comment]
I agree a plugin is a good way to cover this and allow for more then just hashi vault, though I think it would be simpler to leave it to the plugin to organise its own token be that from a file like st2kv or from an instance profile/Azure MSI or any other trust system. I think this will allow for an easier implementation.

**Comment by mjtice** [comment]
We've written a custom vault function within our deployment that makes secret retrieval from Vault a breeze.  IIRC, @xorso brought it up a while back (maybe in the Slack channel?) but because it requires upgrading Oslo it was turned down.

**Comment by chris3081** [comment]
How easy is it to add to the jinja filters? So at the moment you have {{ st2kv.* }}  is it difficult to add jinja filters to the engine for say {{ hashivault.* }} or {{ mycustomsecretengine.* }} ?

**Comment by mjtice** [comment]
I'm not sure I understand, but here's an example of a task:

```
get_device_id_from_fstab:
    action: core.remote
    input:
      cmd: grep -iw <% ctx().mount %> /etc/fstab | awk '{print $1}'
      hosts: <% ctx().cdb_host %>
      username: oracle
      password: "{{ vault_get('data/dbsa/operations/test/oracle', 'st2.dba_refresh', mount='kv') }}"
      cwd: /tmp/
      timeout: 180
```
Where the first param is the secret path (in this case it's a kv2 secret), the second parameter is the st2.kv entry that holds the approle, and the last parameter is the secret mount.
