### ISSUE TITLE
ctx in workflow seems to assign null after task execution

### ISSUE THREAD

**Issue by minsis** [StackStorm/st2#5488]
## SUMMARY

I have a simple workflow with a core.remote action to execute a shell script. The workflow input has a few variables and those are all accessible in the task itself, however, after the task is executed all these input variables are set to null values. It makes it difficult to get the hostname output from the results of the task. Even the vars are assigned null values if they're not being published.

action:
```yaml
name: "<my action>"
pack: "<my pack>"
description: "does stuff"
runner_type: "orquesta"
entry_point: "workflows/<my workflow>.yaml"
enabled: true
parameters:
  kitchen_params:
    type: "object"
    default:
      file: "<my file var>"

  timeout:
    default: 300

  failed_string:
    default: "Error"
```

workflow:
```yaml
version: 1.0
description: "does stuff"

input:
  - kitchen_params
  - hostname
  - failed_string
  - timeout
  - cwd

vars:
  - fail_str: <% ctx("failed_string") %>
  - host: <% ctx("hostname") %>

tasks:
  # [192, 55]
  execute_job:
    action: "<my pack>.execute_my_job"
    input:
      kitchen_params: <% ctx("kitchen_params") %>
      hosts: <% ctx("hostname") %>
      timeout: <% ctx("timeout") %>
      cwd: <% ctx("cwd") %>
     # next:
       # - when: <% ctx().failed_string and (result().get(ctx().hostname).get('stderr').matches(ctx().failed_string) or result().get(ctx().hostname).get('stdout').matches(ctx().failed_string)) %>
         # do: fail

output:
  - msg: <% ctx() %>
```

The output of msg is:
```json
{
  "output": {
    "msg": {
      "st2": {
        "action_execution_id": "<id>",
        "api_url": "https://<st2 url>/api/v1",
        "user": "<me>",
        "pack": "<my pack>",
        "action": "<my action>",
        "runner": "orquesta",
        "workflow_execution_id": "<id>"
      },
      "parent": {
        "re-run": {
          "ref": "<id>"
        },
        "trace_context": {
          "id_": "<id>"
        },
        "user": "<me>",
        "pack": "<pack>",
        "rbac": {
          "user": "<me>",
          "roles": [
            "admin"
          ]
        }
      },
      "kitchen_params": {
        "file": "<my file>",
      },
      "hostname": null,
      "failed_string": null,
      "timeout": 300,
      "cwd": null,
      "fail_str": null,
      "host": null
    }
  }
}
```

You can see everything except `timeout` is reassigned null values.  Even the vars `fail_str` and `host` are reassigned null values when they're assigned values early on. 

I'm not sure if I'm missing something here or if this is a bug.

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 3.6.0, on Python 3.6.8

##### OS, environment, install method

OL7 in an HA cluster

## Steps to reproduce the problem

View the action files above

## Expected Results

After task execution the previous input and vars shouldn't be reassigned null values.

## Actual Results

After task execution input and vars are reassigned null values.

**Comment by nzlosh** [comment]
Can you show how this `<my pack>.<my action>` is being called?

**Comment by minsis** [comment]
> Can you show how the action `<my pack>.<my action>` is being called?

Its listed below, but after looking at it I think I realize what's happening. 

The parent action executing the workflow doesn't have defaults set for those inputs so they're being set as null by default in the context. My assumption here was that `<my pack>.<my action>` defaults were being set in the context which isn't the case and makes sense that it isn't.

Is it Friday yet?

```yaml
name: "<my action>"
runner_type: "remote-shell-cmd"
description: "does stuff"
enabled: true
parameters:
  kitchen_params:
    type: "object"
    required: true

  timeout:
    default: 300
  kwarg_op:
    immutable: true
    default: "-"
  cwd:
    default: "{{ kitchen_params.file.rsplit('/', 1)[0] }}"
  cmd:
    immutable: true
    default: "sh <path to shell script> -no-rep {% for k,v in kitchen_params.items() %}{{ kwarg_op }}{{ k }}='{{ v }}' {% endfor %}"
  hosts:
    default: "<my host>"
  username:
    immutable: true
    default: "<service username>"
```
