### ISSUE TITLE
orquesta with-items-model for dict is error

### ISSUE THREAD

**Issue by jiangxianfu** [StackStorm/st2#5547]
## SUMMARY

orquesta with-items-model for dict is error

i compare two version ,data class type is different

stackstorm 3.5  
yaql: $.items() type is:
<class 'generator'> <generator object ItemsView.__iter__ at 0x7f5146a85d58>

stackstorm 3.6
yaql: $.items() type is:
class collections.abc.ItemsView

### STACKSTORM VERSION

stacstorm 3.6 is error
stackstorm 3.5 is ok

##### OS, environment, install method

in docker

## Steps to reproduce the problem

```
version: "1.0"
description: test with.
input:
  - input_num
tasks:
  task0:
    action: core.echo message=ok
    input:
      input_num: <% ctx().input_num %>
    next:
      - when: <% succeeded() %>
        publish:
          - messages: <% result().result %>
        do: task1

  task1:
    with: k, v in <% ctx(messages).items() %>
    action: core.echo message=<% item(v) %>
```

## Expected Results

YaqlEvaluationException: Unable to evaluate expression '<% ctx(messages).items() %>'. TypeError: unhashable type: 'list",

## Actual Results

stackstorm 3.5 is ok

stacstorm 3.6 is error

Thanks!
