### ISSUE TITLE
Actionchain failing

### ISSUE THREAD

**Issue by Anz14** [StackStorm/st2#5641]
I have stackstorm configured in Ubuntu VM. And I'm integrating stackstorm with alert-manager for alert auto remediation. 
I'm getting the below error while executing the actionchain.

Error:

"error": "Failed to run task \"kafka_demo_disk_action\". Parameter rendering failed.. Failed rendering value for action parameter \"triggers\" in task \"kafka_demo_disk_action\" (template string={{trigger}}): 'trigger' is undefined",
  
"traceback": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/action_chain_runner/action_chain_runner.py\", line 813, in _resolve_params\n    rendered_params = jinja_utils.render_values(\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/jinja.py\", line 149, in render_values\n    raise e\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/jinja.py\", line 144, in render_values\n    rendered_v = env.from_string(v).render(super_context)\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/jinja2/environment.py\", line 1090, in render\n    self.environment.handle_exception()\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/jinja2/environment.py\", line 832, in handle_exception\n    reraise(*rewrite_traceback_stack(source=source))\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/jinja2/_compat.py\", line 28, in reraise\n    raise value.with_traceback(tb)\n  File \"<template>\", line 1, in top-level template code\njinja2.exceptions.UndefinedError: 'trigger' is undefined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/action_chain_runner/action_chain_runner.py\", line 534, in _run_chain\n    liveaction = self._get_next_action(\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/action_chain_runner/action_chain_runner.py\", line 847, in _get_next_action\n    resolved_params = ActionChainRunner._resolve_params(\n  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/action_chain_runner/action_chain_runner.py\", line 825, in _resolve_params\n    raise action_exc.ParameterRenderingFailedException(msg)\nst2common.exceptions.action.ParameterRenderingFailedException: Failed rendering value for action parameter \"triggers\" in task \"kafka_demo_disk_action\" (template string={{trigger}}): 'trigger' is undefined\n"

Rule:

---
    name: "kafka_diskspace_remediation"
    pack: "demo"
    description: "kafka disk  event handler."
    enabled: true

    trigger:
        parameters:
            url: "sample"
        type: "core.st2.webhook"

    criteria:
        trigger.body.alerts[0].labels.alertname:
            type: "startswith"
            pattern : "Disk_usage_kafka"

    action:
        ref: "demo.demo_kafka_chain_meta"
        parameters:
            triggers: "{{ trigger }}"

Action definition metadata:

```
---
name: "demo_kafka_chain_meta"
description: "Simple Action Chain workflow for kafka disk alert"
pack: "demo"
runner_type: "action-chain"
entry_point: "chains/demo_kafka_chain.yaml"
enabled: true
parameters:
    triggers:
        type: "string"
        description: "Trigger received"
        required: true
```

Actionchain:

```
---
  chain:
    -
      name: "kafka_demo_disk_action"
      ref: "demo.kafka_demo_disk_action"
      parameters:
        triggers: "{{trigger}}"
      on-success: "post_success_to_slack"
      on-failure: "opsgenie_escalation"
    -
      name: "post_success_to_slack"
      ref: "slack.post_message"
      parameters:
        channel: "#slo-sli"
        message: "{{kafka_demo_disk_action.result}}"
    -
      name: "opsgenie_escalation"
      ref: "victorops.open_incident"
      parameters:
        message: "{{remote_kafka_disk_action.result}}"

```

**Comment by Anz14** [comment]
@amanda11 I tried changing the action chain parameter from  trigger to triggers and it worked.

```
---
  chain:
    -
      name: "kafka_demo_disk_action"
      ref: "demo.kafka_demo_disk_action"
      parameters:
        triggers: "{{ triggers }}"
      on-success: "post_success_to_slack"
      on-failure: "opsgenie_escalation"
    -
      name: "post_success_to_slack"
      ref: "slack.post_message"
      parameters:
        channel: "#slo-sli"
        message: "Current disk usage in / partition is less than 50% on <IP/Host>"
    -
      name: "opsgenie_escalation"
      ref: "opsgenie.create_alert"
      parameters:
        message: "Current disk usage in / partition is more than 50% on <IP/Host>"
```
