### ISSUE TITLE
Jinja templating does not work for data parameter (Notifications)

### ISSUE THREAD

**Issue by leonardo-zorzi** [StackStorm/st2#5750]
## SUMMARY

While the _message_ parameter works fine with jinja templating, the jinja syntax will stay as is in the _data_ parameter. The docs describe that this should work (https://docs.stackstorm.com/chatops/notifications.html#jinja-templating-in-message-and-data).

### STACKSTORM VERSION
st2 3.7.0, on Python 3.8.10

##### OS, environment, install method
Docker-compose

## Steps to reproduce the problem
Use the docs example:
```
name: "this_chain_will_fail"
description: "test"
runner_type: "orquesta"
entry_point: "fail_chain.yaml"
enabled: true
notify:
  on-failure:
    routes:
      - msteams
    message: '"@channel: Woohoo!". Action run by user {{action_context.user}} succeeded.'
    data:
      cmd: "{{action_parameters.cmd}}"
      stdout: "{{action_results.stdout}}"
parameters:
  test_param:
    type: "string"
    description: "test desc"
    required: true
```
Notify Rule:
```
name: "notify_msteams"
description: "test desc."
enabled: true

trigger:
    type: "core.st2.generic.notifytrigger"
    parameters: {}

criteria:
  trigger.channel:
    pattern: "msteams"
    type: "equals"

action:
    ref: "stackstorm_actions.stackstorm_notify_msteams"
    parameters:
        message: "{{trigger.message}}"
        data: "{{trigger.data}}"
```

## Expected Results

Rendered jinja like in the message payload.

## Actual Results

Payload output of triggered rule action:
```
"message": "\"@channel: Woohoo!\". Action run by user st2admin succeeded.",
    "data": {
      "cmd": "{{action_parameters.cmd}}",
      "stdout": "{{action_results.stdout}}"
```

Please let me know if i did anything wrong..
Thanks in advance! :)

**Comment by jamesdreid** [comment]
Not 100% certain on this, but it appears the variables you are attempting to extract in your Jinja ("{{action_parameters.cmd}}",{{action_results.stdout}}") are available when running an Action but are not part of the standard "orquesta" context.  This may explain why they are not getting resolved correctly, but it does not explain why the entire Jinja statement is rendered as text including the brackets.

**Comment by amanda11** [comment]
The example in the doc that shows the jinja templating on data, is for a notify rule for an action rather than an orquesta workflow. So the example uses data that is available after an action fails, rather than an orquesta failure - so for instance is the type of notification rule you'd have for a core.local failure for example - where the action has a cmd parameter.
Your orquesta workflow doesn't have a cmd parameter, and I'm not sure what output  your workflow has.

Although this issue https://github.com/StackStorm/st2/issues/5221 was about the number of notifications, it's syntax might be useful but I've not tested it. For example to get to a parameter of the workflow in the result they just used {{ paramname }} - where that is name of the parameter of the workflow, not an action within workflow. 

I'm guessing that the problem with the {{ }} not being replaced, is simply because you need to use context parameters that are valid for output of an orquesta workflow rather than an action. 
Looking at https://github.com/StackStorm/st2/blob/eeddc49d3858839da4a911719264748cac5f4c39/st2actions/st2actions/notifier/notifier.py#L175, it looks like if it failed to render the jinja then you will get the raw message instead, but you should also be getting an exception in the ST2 log files as well - so they may help you.

**Comment by leonardo-zorzi** [comment]
Thanks for your answer @jamesdreid @amanda11 !

I did run some new tests and it works now! 

Orquesta meta file
```
name: "this_chain_will_fail"
description: "test"
runner_type: "orquesta"
entry_point: "fail_chain.yaml"
enabled: true
notify:
  on-failure:
    routes:
      - msteams
    message: '"@channel: Woohoo!". Action run by user {{action_context.user}} succeeded. Org Parameter: {{action_parameters.organisation}}'
    data:
      cmd: "{{action_context.user}}"
      stdout: "{{action_parameters.organisation}}"
parameters:
  organisation:
    type: "string"
    description: "Name of the organisation"
    required: true
```

rule payload
```
{
  "trigger": "core.st2.generic.notifytrigger",
  "occurrence_time": "2022-10-07T15:26:54.642000Z",
  "status": "processed",
  "id": "6340453e82dc81513a39fb3f",
  "payload": {
    "message": "\"@channel: Woohoo!\". Action run by user st2admin succeeded. Org Parameter: asdf",
    "data": {
      "cmd": "st2admin",
      "stdout": "asdf",
```

'asdf' was indeed the parameter of the orquesta workflow!
