### ISSUE TITLE
sensor with parameters

### ISSUE THREAD

**Issue by Aliskaa** [StackStorm/st2#5866]
Hello,
When I tried to create a new sensor with an optionnal parameter.

I created a new rule without parameter, it works.
But when I tried to set a parameters, the st2rulesengine doesn't found the rule defined.

My sensor:
```
---
class_name: "WatchTickets"
entry_point: "watch_tickets.py"
description: "Test sensor that emits triggers."
poll_interval: 30
trigger_types:
  - name: "watch_tickets"
    description: "An example trigger."
    parameters_schema:
      type: "object"
      properties:
        delta:
          type: "number"
      additionalProperties: false
    payload_schema:
      type: "object"
      properties:
        ticket_id:
          type: "number"
```

My rule:
```
---
name: "rules.merge.watch_tickets"
pack: "example"
description: "Watch open tickets assigned"
enabled: true

trigger:
  type: "test.watch_tickets"
  parameters:
    delta: 15
action:
  ref: "core.echo"
  parameters:
    message: "{{ trigger.ticket_id }}"
```

Do you have a solution ?

st2 3.7.0, on Python 3.8.10

Thanks!
