### ISSUE TITLE
core.remote error handling in orchesta workflows

### ISSUE THREAD

**Issue by s-bed** [StackStorm/st2#5900]
## SUMMARY

When using core.remote in an Orchesta workflow and referencing its status or stdout in a following task, if the core.remote command has failed to connect to the specified host, it will error out as the task will not create an object

### STACKSTORM VERSION

st2 3.7.0, on Python 3.8.10

##### OS, environment, install method

Running the st2-docker container in a DEV environment

## Steps to reproduce the problem

```
version: 1.0
description: "Test job"

input:
  - recipients
  - hosts
  - username
  - cmd
  - timeout

vars:
  - runtime_error: "An error occurred while executing the workflow."
  - runtime_status: "unknown"

tasks:

  task1:
    action: core.remote 
    input:
      hosts: <% ctx().hosts %>
      username: <% ctx().username %>
      cmd: <% ctx().cmd %>
      timeout: <% ctx().timeout %>
    next:
      - when: <% succeeded() %>
        do: 
          - send_email
      - when: <% failed() %>
        do:
          - send_email
          - fail

  send_email:
      action: core.sendmail
      input:
        subject: "test - {{ task1.status }}"
        to: "{{ ctx().recipients }}"
        body: "{{ task1.stdout }}"
```

`st2 run pack_test.test hosts="test", username="test"`

In the above example, I understand that the **test** host does not exist and I'm expecting the first task to fail with an unreachable error

## Expected Results

I would be expecting that the **task1** object exist, with **status** containing a failed value

## Actual Results

```
{'type': 'error', 'message': 'Execution failed. See result for details.', 'task_id': 'fail'}
{'type': 'error', 'message': "JinjaEvaluationException: Unable to evaluate expression '{{ task1.status }}'. UndefinedError: 'task1' is undefined", 'task_id': 'send_email', 'route': 1}
The workflow execution is completed with status "failed".

Workflow execution completed with errors.
{'type': 'error', 'message': 'Execution failed. See result for details.', 'task_id': 'task1', 'result': {'error': 'Unable to connect to any one of the hosts: [\'test\'].

```

Thanks!
