### ISSUE TITLE
Parsing bug of yqal and jinja

### ISSUE THREAD

**Issue by chain312** [StackStorm/st2#5956]
## SUMMARY

When the input input contains the format of the yaql expression <% XXX% > or the jinja expression contains {{XXX}}, the input is considered to be part of the expression, and the content in the input has the format of the expression, but it is not a complete expression, so that the script will run with an error.

### STACKSTORM VERSION

st2 3.8.0

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

Vagrant

## Steps to reproduce the problem

I built a new playbook to test it.
![image](https://user-images.githubusercontent.com/30886624/229734823-d761a938-59f2-4aa5-8f52-8da8df9ff950.png)

```
version: 1.0
tasks:
  # [39, 67]
  task1:
    action: core.echo
    next:
      # #629e47
      - do:
          - task2
        when: <% ctx(data)[name]="2" %>
        publish:
          - key: success
      # #d1583b
      - do:
          - task3
        when: <% ctx(data)[name]!="2" %>
        publish:
          - key: success
    input:
      message: aaa
  # [139, 217]
  task2:
    action: core.echo
    input:
      message: <% ctx(data)[name]%>
  # [489, 217]
  task3:
    action: core.echo
    input:
      message: <% ctx(data)[name]%>
input:
  - data
```
The input to the playbook is {"name": "<% @% >"}
![image](https://user-images.githubusercontent.com/30886624/229734656-ef6d3c4c-5a1e-4c8d-bb77-5961b39fc17e.png)

## Expected Results

The playbook only executes the task1 output aaa, but does not report an error

## Actual Results

![image](https://user-images.githubusercontent.com/30886624/229734705-e4103358-0ce9-4ed7-b97c-6d1245a0363a.png)

```
{
  "output": null,
  "errors": [
    {
      "type": "error",
      "message": "YaqlEvaluationException: Unable to evaluate expression '<% @ %>'. YaqlLexicalException: Lexical error: illegal character '@' at position 0"
    }
  ]
}
```
Jinja has the same problem, please tell me how to fix it
