### ISSUE TITLE
Can't disable st2timersengine

### ISSUE THREAD

**Issue by DesireWithin** [StackStorm/st2#6039]
## SUMMARY
I followed the documentation(https://docs.stackstorm.com/reference/ha.html#blueprint-box) to install a highly available st2, 
I can't disable st2timersengine after I add:
```
[timer]
enable = False
```

### STACKSTORM VERSION

st2 3.8.0, on Python 3.6.9

##### OS, environment, install method
Ubuntu 18.04.6, install by apt. 

## Steps to reproduce the problem
add the configuration, and then restart st2:
```sh
root@prod-stackstorm-03:/etc/apt/sources.list.d# tail -n 10 /etc/st2/st2.conf
...
db_name = st2
username = stackstorm
password = XXXX
compressors = zstd

[coordination]
url = redis://:Redis_XXXXX@10.XX.XX.XXX:6379

[timer]
enable = False

root@prod-stackstorm-03:/etc/st2# st2ctl restart
Failed to stop st2chatops.service: Unit st2chatops.service not loaded.
Failed to start st2chatops.service: Unit st2chatops.service not found.
##### st2 components status #####
st2actionrunner PID: 102513
st2actionrunner PID: 102515
st2actionrunner PID: 102517
st2actionrunner PID: 102519
st2actionrunner PID: 102521
st2actionrunner PID: 102523
st2actionrunner PID: 102525
st2actionrunner PID: 102527
st2actionrunner PID: 102529
st2actionrunner PID: 102531
st2api PID: 102539
st2stream PID: 102549
st2auth PID: 102559
st2garbagecollector PID: 102562
st2notifier PID: 102565
st2rulesengine PID: 102569
st2sensorcontainer PID: 102572
st2chatops is not running.
st2timersengine PID: 102577
st2workflowengine PID: 102580
st2scheduler PID: 102583

```

## Expected Results

I expect st2timersengine  is not running.

## Actual Results

Now I have duplicate rule evaluations.

**Comment by nzlosh** [comment]
What coordination backend are you using?  I've observed this behaviour with HA setup and am using redis cluster as the coordination backend.  Until a fix is found and released I'm using a workaround by putting a simple lock in the workflow that uses the st2 kv store. (This could be adapted to be an action that any workflow can call)

```
version: 1.0

vars:
  - check_lock_delay: 2

tasks:
  write_execution_id:
    action: st2.kv.set
    input:
      key: <% ctx(st2).action %>_exec_id
      value: <% ctx(st2).action_execution_id %>
    next:
      - when: <% succeeded() %>
        do: wait_to_check_lock

# Delay to allow all nodes to write to the kv store. (Adjust if nodes are heavily loaded and exceed delay)    
  wait_to_check_lock:
    action: core.local
    input:
      cmd: sleep <% ctx(check_lock_delay) %>
    next: 
      - when: <% succeeded() %>
        do: read_execution_id

  read_execution_id:
    action: st2.kv.get
    input:
      key: <% ctx(st2).action %>_exec_id
    next: 
      - when: <% succeeded() and result().result = ctx().st2.action_execution_id %>
        do: proceed

  proceed:
    action: core.local
    input: 
      cmd: echo "ONLY A SINGLE WORKFLOW SHOULD REACH HERE"
```
