### ISSUE TITLE
st2kv : Non-hexadecimal digit found

### ISSUE THREAD

**Issue by Aliskaa** [StackStorm/st2#6148]
### STACKSTORM VERSION

Paste the output of ``st2 --version``: v3.9dev (Ubuntu 20.04.6 LTS GNU/Linux x86_64)

##### OS, environment, install method

Docker

## Steps to reproduce the problem

In v3.9dev, I tried to store a key with an encrypted value. The encrypted value contains special characters (., -, _)
When I use st2kv in my config file, Stackstorm asks me: 'Non-hexadecimal digit found'. But it's OK with version v3.8.

commands :
`st2 key set my_token 'my.fake-super_password' --encrypt`

The config file:
```
---
connections:
    my_token: "{{st2kv.system.my_token | decrypt_kv}}"
    url: "my_api.com"
```

Thanks!
