### ISSUE TITLE
Workflow finishes too early when parallel branches are running

### ISSUE THREAD

**Issue by Dupangel** [StackStorm/st2#6316]
## SUMMARY

While running our workflows, we found out that some that are supposed to branch under some conditions don't execute until the expected last task on the second branch.

As we created a loop in the workflow, we don't know if it's a real bug or if we have improper use of orquesta workflow engine.
In the last case, some docs may be missing as there's no warning regarding loops on tasks in orquesta engine.

### STACKSTORM VERSION

``st2 --version``: st2 3.5.0, on Python 3.6.8

##### OS, environment, install method

Running on CentOS Linux release 7.6.1810 (Core) and installed manually (with rpm + dependencies) following installation docs.

## Steps to reproduce the problem

Here are two simple workflows to reproduce the problem :

`tester_bug.yaml`
```yaml
version: 1.0

description: workflow to reproduce bug with task loop and parallel branching

vars:
  - nextstep: "step1"

tasks:
  entrypoint:
    action: core.noop
    next:
      - do: check_step

  check_step:
    action: core.noop
    next:
      - when: <% ctx(nextstep) = "step1" %>
        publish:
          - nextstep: "step2"
        do:
          - sleep_wf
          - sleep_action
      - when: <% ctx(nextstep) = "step2" %>
        publish:
          - nextstep: "step3"
        do:
          - sleep_action
      - when: <% ctx(nextstep) = "step3" %>
        publish:
          - nextstep: "step4"
        do:
          - sleep_action

  sleep_action:
    action: core.local
    input:
      cmd: "sleep 15"
    next:
      - do: check_step

  sleep_wf:
    action: bull.utilities.sleep_wf
    next:
      - do: check_step


output:
  - message: "toto"
```

`sleep_wf.yaml`
```yaml
version: 1.0

description: workflow that just sleeps

tasks:
  sleep_action:
    action: core.local
    input:
      cmd: "sleep 42"

output:
  - state: "OK"
```

And their associated metadatas :

`mdt_tester_bug.yaml`
```yaml
description: workflow to reproduce bug with task loop and parallel branching
enabled: true
name: tester_bug
notify: {}
pack: toto
runner_type: orquesta
entry_point: "workflows/tester_bug.yaml"
```

`mdt_sleep_wf.yaml`
```yaml
description: workflow that just sleeps
enabled: true
name: sleep_wf
notify: {}
pack: toto
runner_type: orquesta
entry_point: "workflows/sleep_wf.yaml"
 ```

## Expected Results

StackStorm should return a result only when both branches in `tester_bug.yaml` are finished.

## Actual Results

Instead of returning when both branches are finished, StackStorm terminates workflow when one of them is finished and kills the other.

Example output of this behaviour :
```
st2 run toto.tester_bug
.........................
id: 67d2d71c806560c75c1bb55c
action.ref: toto.tester_bug
parameters: None
status: succeeded
start_timestamp: Thu, 13 Mar 2025 14:01:16 CET
end_timestamp: Thu, 13 Mar 2025 14:02:06 CET
log:
  - status: requested
    timestamp: '2025-03-13T13:01:16.346000Z'
  - status: scheduled
    timestamp: '2025-03-13T13:01:16.499000Z'
  - status: running
    timestamp: '2025-03-13T13:01:16.559000Z'
  - status: succeeded
    timestamp: '2025-03-13T13:02:05.915000Z'
result:
  output:
    message: toto
+-----------------------------+-------------------------+--------------+-------------------------+-------------------------------+
| id                          | status                  | task         | action                  | start_timestamp               |
+-----------------------------+-------------------------+--------------+-------------------------+-------------------------------+
|   67d2d71c2db78f675e32168f  | succeeded (1s elapsed)  | entrypoint   | core.noop               | Thu, 13 Mar 2025 14:01:16 CET |
|   67d2d71d2db78f675e32169f  | succeeded (0s elapsed)  | check_step   | core.noop               | Thu, 13 Mar 2025 14:01:17 CET |
|   67d2d71d2db78f675e3216af  | succeeded (16s elapsed) | sleep_action | core.local              | Thu, 13 Mar 2025 14:01:17 CET |
| + 67d2d71d2db78f675e3216b5  | succeeded (44s elapsed) | sleep_wf     | toto.sleep_wf           | Thu, 13 Mar 2025 14:01:17 CET |
|    67d2d71e2db78f675e3216c7 | succeeded (42s elapsed) | sleep_action | core.local              | Thu, 13 Mar 2025 14:01:18 CET |
|   67d2d72d2db78f675e3216d8  | succeeded (0s elapsed)  | check_step   | core.noop               | Thu, 13 Mar 2025 14:01:33 CET |
|   67d2d72d2db78f675e3216e8  | succeeded (16s elapsed) | sleep_action | core.local              | Thu, 13 Mar 2025 14:01:33 CET |
|   67d2d73d2db78f675e3216f8  | succeeded (0s elapsed)  | check_step   | core.noop               | Thu, 13 Mar 2025 14:01:49 CET |
|   67d2d73d2db78f675e321708  | succeeded (16s elapsed) | sleep_action | core.local              | Thu, 13 Mar 2025 14:01:49 CET |
|   67d2d7492db78f675e321722  | succeeded (0s elapsed)  | check_step   | core.noop               | Thu, 13 Mar 2025 14:02:01 CET |
|   67d2d7492db78f675e321732  | running (5s elapsed)    | sleep_action | core.local              | Thu, 13 Mar 2025 14:02:01 CET |
|   67d2d74d2db78f675e321742  | succeeded (0s elapsed)  | check_step   | core.noop               | Thu, 13 Mar 2025 14:02:05 CET |
+-----------------------------+-------------------------+--------------+-------------------------+-------------------------------+
```

We see that a sleep action (not even the last one, only the one before the last) is running while StackStorm already returned a successful result).

**Comment by Dupangel** [comment]
Here are the schemas reprensenting expected execution result and the workflow logic :

![Image](https://github.com/user-attachments/assets/4fa22731-235d-402c-8eca-6676647d85b5)
![Image](https://github.com/user-attachments/assets/8eac61c8-5011-4f76-959d-a28193a01399)

**Comment by fdrab** [comment]
Not necessarily a bug, but rather you expecting it to do something it's not designed to do without explicit instructions. You can try to play around with "JOIN" on the "check_step". If I structure my workflow like this:

`
           / parallel task 1 wait 15 seconds \
Task                                                              task 3
           \ parallel task 2 wait 10 seconds /
`

And put a "join" on the task 3, it waits for both parallel branches to finish before executing. If I don't put a "join" on it, task 3 executes when whichever parallel branch finishes the first.

Reference: https://docs.stackstorm.com/orquesta/languages/orquesta.html#task-transition-model

**Comment by Dupangel** [comment]
Problem is that these two (or more) branches should finish on a final state (sometimes the same, sometimes different ones) without waiting for the other(s). I don't want a join state as from the first check_step execution, the two branches have to run separately.

From the docs I understand that Orquesta engine waits for the end of currently running tasks in parallel branches before exiting (in case of fail, the fail-fast design I suppose) but there's no fail here, and I can't see anything about ending of workflow in case of success with more than one branch running (and without a join).

I may be wrong, but I suppose that instead of "Orquesta engine exit the workflow once **all** parallel branches are in succeeded state or one of them is in failed state" we have "Orquesta engine exit the workflow once **one** parallel branch is in succeeded state or one of them is in failed state"

**Comment by nzlosh** [comment]
I altered the main workflow to include some output when the `check_step` and `sleep_action` are called.  The workflow is as follows

```
version: 1.0

description: workflow to reproduce bug with task loop and parallel branching

vars:
  - nextstep: "step1"
  - action_count: 0

tasks:
  entrypoint:
    action: core.noop
    next:
      - do: check_step

  check_step:
    action: core.local
    input:
      cmd: |
        echo [check_step] nextstep=<% ctx(nextstep) %>
    next:
      - when: <% ctx(nextstep) = "step1" %>
        publish:
          - nextstep: "step2"
        do:
          - sleep_action
          - sleep_wf
      - when: <% ctx(nextstep) = "step2" %>
        publish:
          - nextstep: "step3"
        do:
          - sleep_action
      - when: <% ctx(nextstep) = "step3" %>
        publish:
          - nextstep: "step4"
        do:
          - sleep_action

  sleep_action:
    action: core.local
    input:
      cmd: |
        echo [sleep_action][<% ctx(action_count) %>] nextstep=<% ctx(nextstep) %>
        sleep 2
    next:
      - do: check_step
        publish:
          - action_count: <% ctx(action_count) + 1 %>

  sleep_wf:
    action: playpen.sleep_wf
    next:
      - do: check_step

output:
  - message: "toto"
```
The delay in the `sleep_wf` is set to 50 seconds.  The execution of the workflow produces the below output:
```
+-----------------------------+-------------------------+-----------------+------------------+-------------------------------+
| id                          | status                  | task            | action           | start_timestamp               |
+-----------------------------+-------------------------+-----------------+------------------+-------------------------------+
|   67d4b2d9dd7fe35270479bab  | succeeded (0s elapsed)  | entrypoint      | core.noop        | Fri, 14 Mar 2025 22:51:05 UTC |
|   67d4b2d9dd7fe35270479bbb  | succeeded (0s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:05 UTC |
|   67d4b2d9dd7fe35270479bcb  | succeeded (3s elapsed)  | sleep_action    | core.local       | Fri, 14 Mar 2025 22:51:05 UTC |
| + 67d4b2d9dd7fe35270479bd1  | succeeded (50s elapsed) | sleep_wf        | playpen.sleep_wf | Fri, 14 Mar 2025 22:51:05 UTC |
|    67d4b2dadd7fe35270479be3 | succeeded (48s elapsed) | wf_sleep_action | core.local       | Fri, 14 Mar 2025 22:51:06 UTC |
|   67d4b2dcdd7fe35270479bf4  | succeeded (0s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:08 UTC |
|   67d4b2dcdd7fe35270479c04  | succeeded (2s elapsed)  | sleep_action    | core.local       | Fri, 14 Mar 2025 22:51:08 UTC |
|   67d4b2dedd7fe35270479c14  | succeeded (0s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:10 UTC |
|   67d4b2dedd7fe35270479c24  | succeeded (2s elapsed)  | sleep_action    | core.local       | Fri, 14 Mar 2025 22:51:10 UTC |
|   67d4b2e1dd7fe35270479c34  | succeeded (0s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:13 UTC |
|   67d4b30bdd7fe35270479c54  | succeeded (0s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:55 UTC |
|   67d4b30bdd7fe35270479c64  | succeeded (2s elapsed)  | sleep_action    | core.local       | Fri, 14 Mar 2025 22:51:55 UTC |
|   67d4b30ddd7fe35270479c74  | succeeded (0s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:57 UTC |
|   67d4b30ddd7fe35270479c84  | succeeded (2s elapsed)  | sleep_action    | core.local       | Fri, 14 Mar 2025 22:51:57 UTC |
|   67d4b30fdd7fe35270479c94  | succeeded (1s elapsed)  | check_step      | core.local       | Fri, 14 Mar 2025 22:51:59 UTC |
+-----------------------------+-------------------------+-----------------+------------------+-------------------------------+
```
We can see the step looping every 2 seconds from 22:51:05 to 22:51:13.  A second step loop begins at 22:51:55 which coincides with the exit from the `sleep_wf` workflow.  Iterating over the execution id's and searching for the stdout produces the following result
```
67d4b2d9dd7fe35270479bab
67d4b2d9dd7fe35270479bbb
  stdout: '[check_step] nextstep=step1'
67d4b2d9dd7fe35270479bcb
  stdout: '[sleep_action][0] nextstep=step2'
67d4b2d9dd7fe35270479bd1
67d4b2dadd7fe35270479be3
  stdout: '[sleep_action]'
67d4b2dcdd7fe35270479bf4
  stdout: '[check_step] nextstep=step2'
67d4b2dcdd7fe35270479c04
  stdout: '[sleep_action][1] nextstep=step3'
67d4b2dedd7fe35270479c14
  stdout: '[check_step] nextstep=step3'
67d4b2dedd7fe35270479c24
  stdout: '[sleep_action][2] nextstep=step4'
67d4b2e1dd7fe35270479c34
  stdout: '[check_step] nextstep=step4'
67d4b30bdd7fe35270479c54
  stdout: '[check_step] nextstep=step2'
67d4b30bdd7fe35270479c64
  stdout: '[sleep_action][0] nextstep=step3'
67d4b30ddd7fe35270479c74
  stdout: '[check_step] nextstep=step3'
67d4b30ddd7fe35270479c84
  stdout: '[sleep_action][1] nextstep=step4'
67d4b30fdd7fe35270479c94
  stdout: '[check_step] nextstep=step4'
```
What can be seen is that action count is *0* in execution `67d4b2d9dd7fe35270479bcb` (22:51:05) and again it is *0* in execution `67d4b30bdd7fe35270479c64` (22:51:55).

The workflow only increments the action counter which leads me to think the current execution context is being overwritten with stale data when the parallel task completes.  I suspect this is a bug in Orquesta, not StackStorm core, but needs to be investigated to be confirmed.

These tests were run on
```
st2 --version
st2 3.9dev (), on Python 3.8.10
```
