### ISSUE TITLE
BUG: Unable to use dashes in rules for YAML values

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2#893]
Turns out, this rule is invalid.

``` yaml

---
    name: 'st2.webhook.cicd.github.events'
    description: 'Webhook listening for pushes to our CI/CD (SeatShare) repository'
    trigger:
        type: core.st2.webhook
        parameters:
            url: cicd/github/events
    criteria:
        trigger.header.X-GitHub-Event:
            pattern: push
            type: equals
    action:
        ref: jenkins.build_job
        parameters:
            project: {{trigger.body.repository.name}}
    enabled: true

```

Yields this:

```
ConstructorError: while constructing a mapping               |
|                 |   in "/opt/stackstorm/packs/cicd/rules/github-push.yaml",    |
|                 | line 15, column 22                                           |
|                 | found unacceptable key (unhashable type: 'dict')             |
|                 |   in "/opt/stackstorm/packs/cicd/rules/github-push.yaml",    |
|                 | line 15, column 23                                           |
```

Going to try rewriting in JSON to see if I can work around it...
